### ISSUE TITLE
libhdf5 not found when importing a package that depends on HDF5

### ISSUE THREAD

**Issue by rkube** [JuliaIO/HDF5.jl#1033]
Hi,
`HDF5.jl` fails to load when I'm importing a package that depends on HDF5 from another package. The situation is like this:

```
repos/package_A  <-- Depends on HDF5.jl
repos/package_B
```

Importing  and using `package_A`by itself is fine. However, loading `package_A` from within `package_B` raises an error:
```
ERROR: LoadError: UndefVarError: libhdf5 not defined
```

My workflow is like this:

```
$ julia
julia> push!(LOAD_PATH, "../package_A")
julia> using package_A
ERROR: LoadError: UndefVarError: libhdf5 not defined
```

A workaround is this:
```
$ julia
julia> import Pkg; Pkg.add("HDF5")
julia> push!(LOAD_PATH, "../package_A")
julia> using package_A
julia>
```

Why is it necessary to add `HDF5.jl` to `package_B`?

**Comment by mkitti** [comment]
Can you provide the stack trace?

**Comment by mkitti** [comment]
Also we should consider alternatives other than `LOAD_PATH` manipulation. For example, could you use `Pkg.dev` instead?

**Comment by simonbyrne** [comment]
It's hard to understand exactly what is going on: can you give the Project.toml and Manifest.toml, or a simple way to reproduce the error?
