### ISSUE TITLE
Switch to Preferences for using system hdf5

### ISSUE THREAD

**Issue by simonbyrne** [JuliaIO/HDF5.jl#1037]
Technically this is already possible, by overriding the HDF5_jll paths, e.g. https://github.com/CliMA/ClimaCore.jl/blob/3e250b1f75d3bd3f4f7353cb9c1892e318b9e809/.buildkite/JuliaProject.toml

However I'm not sure that this will work on systems where JLL's aren't already available.

**Comment by simonbyrne** [comment]
Unfortunately setting the HDF5_jll paths can then break other packages, like NetCDF_jll.

**Comment by mkitti** [comment]
How so?

**Comment by simonbyrne** [comment]
Because the library in NetCDF_jll is linked against the library name which includes the version number, and this may not be the same as on the system:
https://buildkite.com/clima/climacore-ci/builds/1880#0186f6b7-490c-4439-8c42-ef21dc99fbed/986-1211

**Comment by mkitti** [comment]
Ah yes. That situation is particularly confusing. Would a symlink work? Is there another solution that works better?

**Comment by mkitti** [comment]
I'm this particular case perhaps you should just rebuild the NetCDF and HDF5 JLLs... then maintain a fork.

**Comment by mkitti** [comment]
Also have we considered using Preferences.jl separately from the JLL override mechanism?

**Comment by simonbyrne** [comment]
> Also have we considered using Preferences.jl separately from the JLL override mechanism?

This is probably the easiest option for now. PRs welcome?
