### ISSUE TITLE
Juliacon 2023?

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#1039]
Are you of you planning on attending JuliaCon 2023? Directing this in particular to @musm, @simonbyrne, and @jmert .

I know it's past the CFP deadline, but I think we might be able to squeeze in a presentation on HDF5.jl since I'm one of the organizers. Would anyone be interested in this?

**Comment by simonbyrne** [comment]
I'm planning on going. I do have two other proposals, so not sure I have the bandwidth to put together another talk, but am happy to help out.

**Comment by simonbyrne** [comment]
@mkitti what did you have in mind? We could do a package overview presentation:

- what is HDF5
  - how it fits into related formats/software (NetCDF, MAT, PyTables)
  - when to use it (lots of numbers, array-like data)
  - when to not (tabular, lots of strings)
- using HDF5.jl
  - basic usage
  - advanced features (chunking, compression, MPI)
- relationship to other packages (e.g. JLD2.jl)
- future plans

I think something like that would work as either a 10 minute or poster (in fact, given our somewhat distributed and asynchronous collaboration, a poster might be the easier option)

**Comment by musm** [comment]
@mkitti and @simonbyrne  I am interested in helping with this. I think I can also make arrangements to be there in person.

**Comment by musm** [comment]
I'm open to both options, but I think a short talk that is recorded could also be helpful for new users looking to quickly get up and running with HDF5.  What are the steps to submit for the CFP given we are past the deadline?

**Comment by mkitti** [comment]
Basically contact the organizers, @logankilpatrick in particular. I'm currently the Finance Chair of JuliaCon 2023. Since you two seem interested, I will pursue this.

**Comment by mkitti** [comment]
As for the outline, that's pretty much what I had in mind. I would maybe make it more of a tutorial. It may also be useful to contrast it to other bindings.

**Comment by simonbyrne** [comment]
> I'm open to both options, but I think a short talk that is recorded could also be helpful for new users looking to quickly get up and running with HDF5.

That's a good point. Let's go for the 10 minute talk then.

**Comment by simonbyrne** [comment]
For the background on HDF5, here is a write up I did a while ago: https://github.com/CliMA/ClimateMachine.jl/issues/114#issuecomment-643722513

**Comment by mkitti** [comment]
I do have the submission link now, so it's time to start drafting the proposal.

**Comment by musm** [comment]
Great  @mkitti  do you want to communicate the link over email or DM ?

**Comment by mkitti** [comment]
Sorry I got really busy over the past week. We don't have much more time to get it in. 

I'll start drafting it based on the pointers above. Send your preferred email address to mark@julialang.org, ans I can send you thr link.

**Comment by mkitti** [comment]
I also noticed that HDF5 User Group meeting in August in Columbus, Ohio at OSU. @musm , @simonbyrne or anyone else, are you attending this event?

https://www.hdfgroup.org/hug/hug23/

**Comment by musm** [comment]
> I also noticed that HDF5 User Group meeting in August in Columbus, Ohio at OSU. @musm , @simonbyrne or anyone else, are you attending this event?

Thanks for bringing this to attention, but I won't have the chance to attend.
