### ISSUE TITLE
Finalizer error when rapidly writing to HDF5

### ISSUE THREAD

**Issue by TacHawkes** [JuliaIO/HDF5.jl#1048]
Hi,

I have the following setup:

1. A main thread which is idling
2. A thread which writes to a HDF5 dataset faster than 1 ms delay between successive writes, i.e. (just pseudo-MWE)
```julia
Threads.@spawn begin
     for i=1:1_000_000
          lock(some_filelock) do
              hdf5_dataset[startidx:stopidx,1] = somedata
          end
     end
end
```

If the writes are too fast, the task/thread crashes with the following trace:

```
error in running finalizer: ErrorException("val already in a list")
error at .\error.jl:35
push! at .\linked_list.jl:53 [inlined]
_wait2 at .\condition.jl:87
#wait#621 at .\condition.jl:127
wait at .\condition.jl:125 [inlined]
slowlock at .\lock.jl:156
lock at .\lock.jl:147 [inlined]
h5i_is_valid at C:\Users\user\.julia\packages\HDF5\TcavY\src\api\functions.jl:1960
isvalid at C:\Users\user\.julia\packages\HDF5\TcavY\src\objects.jl:2 [inlined]
close at C:\Users\user\.julia\packages\HDF5\TcavY\src\dataspaces.jl:25
unknown function (ip: 000002027f7c9b96)
run_finalizer at C:/workdir/src\gc.c:298
jl_gc_run_finalizers_in_list at C:/workdir/src\gc.c:388
run_finalizers at C:/workdir/src\gc.c:434
jl_mutex_unlock at C:/workdir/src\julia_locks.h:81 [inlined]
ijl_task_get_next at C:/workdir/src\partr.c:385
poptask at .\task.jl:963
wait at .\task.jl:972
#wait#621 at .\condition.jl:130
wait at .\condition.jl:125 [inlined]
take_buffered at .\channels.jl:456
take! at .\channels.jl:450 [inlined]
iterate at .\channels.jl:592
macro expansion at c:\Users\user\.vscode\extensions\julialang.language-julia-1.41.1\scripts\packages\JSONRPC\src\core.jl:103 [inlined]
#1 at .\task.jl:514
unknown function (ip: 000002027f6ffb33)
jl_apply at C:/workdir/src\julia.h:1874 [inlined]
start_task at C:/workdir/src\task.c:1092
```

Versioninfo:

```
Julia Version 1.9.0-beta3
Commit 24204a7344 (2023-01-18 07:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8
```

**Comment by mkitti** [comment]
https://github.com/JuliaIO/HDF5.jl/pull/1024 might be able to help with this.

It might help to call `GC.gc()` to manually engage garbage collection.

Another alternative would be to use `GC.enable(false)` or `GC.enable_finalizers(false)` before entering the tight loop.

**Comment by simonbyrne** [comment]
What version of HDF5.jl are you using?

**Comment by simonbyrne** [comment]
Also, it would be helpful if you can give a full minimal reproducible example.

**Comment by TacHawkes** [comment]
This is with v0.16.13

**Comment by simonbyrne** [comment]
Huh, we added locking around API calls in #1021, which should be in that version.

Do you still see the same issue if you remove the `lock`?

**Comment by TacHawkes** [comment]
Yes, here is a MWE. Run the whole block at once for it to happen. Adding GC.disable/enable fixes the problem seemingly...

```julia
using HDF5

fid = h5open(tempname() * ".h5", "w")

d = create_dataset(fid, "data", datatype(Int), ((1_000_000,1), (-1,1)), chunk=(1,1))

t = Threads.@spawn begin
    #GC.enable(false)
    for i=1:1_000_000
        d[i,1] = 1
    end
    #GC.enable(true)
end

wait(t)

close(fid)
```

**Comment by simonbyrne** [comment]
I am unable to replicate it on my Mac. I don't have a Windows machine to try it on, unfortunately.

Do you see it if you run it outside VSCode? (i.e. if you just run it in a script from the command line)

**Comment by simonbyrne** [comment]
I still can't replicate it. What is your full `status -m`?

Can you also try running it with `--startup-file=no` to make sure you're not picking up anything in your startup file?

**Comment by mkitti** [comment]
My guess is that we also need to be under low memory conditions for the GC to be attempting to finalize things in the middle of this loop.

Nonetheless, this points to a fundamental issue. We should not be locking and unlocking during finalization from a different task.

**Comment by simonbyrne** [comment]
I guess I still don't understand how this can happen after #1021.

**Comment by mkitti** [comment]
> I guess I still don't understand how this can happen after #1021.

The problem was caused by #1021. It is because the finalizer tries to call `close`. As of #1021, `close` tries to `lock` and `unlock`, which causes a potential task switch in the finalizer and that is not allowed.

I raised this and you responded in https://github.com/JuliaIO/HDF5.jl/pull/1021#issuecomment-1306659168 . So either https://github.com/JuliaLang/julia/pull/38487 does not actually address this or there has been a regression.

**Comment by simonbyrne** [comment]
> My guess is that we also need to be under low memory conditions for the GC to be attempting to finalize things in the middle of this loop.

You're right: I was able to trigger it with `--heap-size-hint=50M`.

**Comment by mkitti** [comment]
> Yes, here is a MWE. Run the whole block at once for it to happen. Adding GC.disable/enable fixes the problem seemingly...

Does `GC.enable_finalizers(false)` / `GC.enable_finalizers(true)` also fix the issue?

**Comment by simonbyrne** [comment]
> Does `GC.enable_finalizers(false)` / `GC.enable_finalizers(true)` also fix the issue?

Yes.

**Comment by mkitti** [comment]
So far I am unable to replicate on Windows.

**Comment by mkitti** [comment]
I can replicate on macOS but not consistently. It seemed to occur more frequently when I first logged in.

**Comment by simonbyrne** [comment]
Possible related: https://github.com/JuliaLang/julia/issues/47612

**Comment by mkitti** [comment]
I think we need to use `trylock` in the finalizers.

```Julia
function try_close_finalizer(x)
   # Test and test lock, see trylock docstring
   # Only proceed if the finalizer thread can acquire the lock, do not wait
   if(!islocked(API.lock) && trylock(API.lock))
       try
           close(x)
       finally
           unlock(API.lock)
       end
   else
       # try again later
       # TODO: consider exponential backoff
       finalizer(try_close_finalizer, x) 
   end
end
```

**Comment by mkitti** [comment]
User code may want to try to acquire the API lock. Shouldn't this disable finalizers due to https://github.com/JuliaLang/julia/blob/72bebdf2715f94bad52c701cfb867744a5b070d6/base/lock.jl#L96 ?

```Julia
t = Threads.@spawn begin
    lock(HDF5.API.liblock)
    try
        for i=1:1_000_000
            d[i,1] = 1
        end
    finally
        unlock(HDF5.API.liblock)
    end
    #GC.enable(true)
end
```

**Comment by mkitti** [comment]
On macOS, once I find a terminal process that causes the error, then this reliably creates a problem:

```julia
$ julia +1.9 -t auto --heap-size-hint=50M --banner = no
julia> begin
           using HDF5

           fid = h5open(tempname() * ".h5", "w")

           d = create_dataset(fid, "data", datatype(Int), ((1_000_000,1), (-1,1)), chunk=(1,1))

           t = Threads.@spawn begin
               #GC.enable(false)
               for i=1:1_000_000
                   d[i,1] = 1
               end
               #GC.enable(true)
           end

           wait(t)

           close(fid)
       end
error in running finalizer: ErrorException("val already in a list")
error at ./error.jl:35
push! at ./linked_list.jl:53 [inlined]
_wait2 at ./condition.jl:87
#wait#621 at ./condition.jl:127
wait at ./condition.jl:125 [inlined]
slowlock at ./lock.jl:156
lock at ./lock.jl:147 [inlined]
h5i_is_valid at /Users/kittisopikulm/.julia/packages/HDF5/TcavY/src/api/functions.jl:1960
isvalid at /Users/kittisopikulm/.julia/packages/HDF5/TcavY/src/properties.jl:19 [inlined]
close at /Users/kittisopikulm/.julia/packages/HDF5/TcavY/src/properties.jl:11
unknown function (ip: 0x1170d405f)
ijl_apply_generic at /Users/kittisopikulm/.julia/juliaup/julia-1.9.0-beta3+0.aarch64.apple.darwin14/lib/julia/libjulia-internal.1.9.dylib (unknown line)
run_finalizer at /Users/kittisopikulm/.julia/juliaup/julia-1.9.0-beta3+0.aarch64.apple.darwin14/lib/julia/libjulia-internal.1.9.dylib (unknown line)
jl_gc_run_finalizers_in_list at /Users/kittisopikulm/.julia/juliaup/julia-1.9.0-beta3+0.aarch64.apple.darwin14/lib/julia/libjulia-internal.1.9.dylib (unknown line)
...
```

Meanwhile, the using `do` with `h5open` does not create a problem:

```julia
$ julia +1.9 -t auto --heap-size-hint=50M --banner = no
julia> begin
           using HDF5

           h5open(tempname() * ".h5", "w") do fid

              d = create_dataset(fid, "data", datatype(Int), ((1_000_000,1), (-1,1)), chunk=(1,1))

              t = Threads.@spawn begin
                  for i=1:1_000_000
                       d[i,1] = 1
                  end
              end
              wait(t)
           end
       end
```

**Comment by mkitti** [comment]
Hmm... acquiring the lock causes a lot of error message scrolling.

```
julia> begin
       using HDF5

       fid = h5open(tempname() * ".h5", "w")

       d = create_dataset(fid, "data", datatype(Int), ((1_000_000,1), (-1,1)), chunk=(1,1))

       t = Threads.@spawn @lock HDF5.API.liblock begin
           #GC.enable(false)
           for i=1:1_000_000
               d[i,1] = 1
           end
           #GC.enable(true)
       end

       wait(t)

       close(fid)
       end
```

Using the `do` block seems to not cause the problem:

```julia
julia> begin
       using HDF5

       h5open(tempname() * ".h5", "w") do fid

       d = create_dataset(fid, "data", datatype(Int), ((1_000_000,1), (-1,1)), chunk=(1,1))

       t = Threads.@spawn @lock HDF5.API.liblock begin
           #GC.enable(false)
           for i=1:1_000_000
               d[i,1] = 1
           end
           #GC.enable(true)
       end

       wait(t)

       close(fid)
       end
       end
```

**Comment by mkitti** [comment]
> > Does `GC.enable_finalizers(false)` / `GC.enable_finalizers(true)` also fix the issue?
> 
> Yes.

This only avoids the error if I use `GC.enable_finalizers` outside of the `Threads.@spawn`. Using then inside causes much error scrolling.

**Comment by TacHawkes** [comment]
https://github.com/JuliaIO/HDF5.jl/pull/1049 fixes this. Big thanks to @mkitti  for the fast fix!

**Comment by laborg** [comment]
I've stumbled over this bug too. Any chance to land the fix and cut a quick bugfix release?

**Comment by mkitti** [comment]
Could you confirm that #1049 fixes the issue for you? If so, I will accelerate the merge.

cc: @musm

**Comment by laborg** [comment]
Yes, the branch worked.
