### ISSUE TITLE
Copy a group of data from a file to another

### ISSUE THREAD

**Issue by linwaytin** [JuliaIO/HDF5.jl#1070]
I have a file `old.h5` with data group like `data/foo1`, `data/foo2`, and so on. I want to copy this group to another file `new.h5`. The following seems to work.
```julia
copy_object(fid_old["data"], fid_new, "data")
```
where `fid_old` and `fid_new` are the corresponding file handles. 

My question is that this function `copy_object` is not documented. I found it in the source code. Is this function not stable enough, or it just hasn't been put in the document?

By the way, I want to thank the developers of this package. It is easy to use. Especially the Dictionary syntax is super convenient!

**Comment by mkitti** [comment]
Could you submit a pull request with a docstring for it?

You could also look at the Documenter.jl and include the docstring somewhere.

Also double check that we test this function.

Let me know if you need help.

**Comment by linwaytin** [comment]
Yes, I can do that. So the function is considered to be stable, just not documented yet? 
I'm gonna use it so I would like to know what the status is. Thank you.

**Comment by mkitti** [comment]
> So the function is considered to be stable, just not documented yet?

It will be once it's added to the documentation. That's why I'm encouraging you to send the pull request. Otherwise, I'll add it to my long queue of things to do.

**Comment by linwaytin** [comment]
Ok I will try to work on that. I would also like to add documentation to `delete_object`, which is another very useful function.

**Comment by mkitti** [comment]
Closed by #1071
