### ISSUE TITLE
HDF5.jl logo not optimal for dark mode

### ISSUE THREAD

**Issue by sloede** [JuliaIO/HDF5.jl#1081]
The HDF5.jl color scheme is not optimal when using dark mode, e.g., on GitHub
<img width="431" alt="image" src="https://github.com/JuliaIO/HDF5.jl/assets/3637659/29131718-295a-473a-ba9b-40e25f77dac8">

or in Documenter.jl
<img width="461" alt="image" src="https://github.com/JuliaIO/HDF5.jl/assets/3637659/4921bce5-b154-42f4-8fed-ce405cfe9ebc">

Either something more colorful or with a background color would probably be more suitable if dark mode clients are to be supported equally.

**Comment by mkitti** [comment]
@cormullion Can I commission you to create a better logo for HDF5.jl?

**Comment by cormullion** [comment]
Cool, I'd be happy to. The switch to dark-mode has affected many logos...

**Comment by cormullion** [comment]
Here's a 1280x640 (for social media preview, readme, etc)

![hdf5-social-media-preview](https://github.com/JuliaIO/HDF5.jl/assets/52289/7b66bdca-d103-414e-a38a-a1a1ec6d9b50)

icon in SVG: [hdf5.svg.zip](https://github.com/JuliaIO/HDF5.jl/files/11904579/hdf5.svg.zip)

**Comment by mkitti** [comment]
@cormullion this is fantastic, thank you.

**Comment by mkitti** [comment]
@cormullion thanks again for this. The JuliaCon organizers are trying to contact you via you m**.com email address.
