### ISSUE TITLE
`maxdims` or `max_dims` in `dataspace()`

### ISSUE THREAD

**Issue by NuCO-UNM** [JuliaIO/HDF5.jl#1083]
In `dataspaces.jl`, the documentation has `dataspace(dims::Tuple; maxdims::Tuple=dims)` while the actual code has `max_dims` as the keyword argument.

**Comment by mkitti** [comment]
Thank you. See https://github.com/JuliaIO/HDF5.jl/pull/1085 for the fix. Pull requests are welcome.
