### ISSUE TITLE
Add to list of known preferences

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#1112]
PreferenceTools.jl has a list of known preferences. 

https://github.com/cjdoris/PreferenceTools.jl/blob/main/KNOWN_PREFERENCES.md

@JoshuaLampert , would you be interested in adding the new ones in HDF5.jl v0.17 to that list?

**Comment by JoshuaLampert** [comment]
Sure, I created a PR over there: https://github.com/cjdoris/PreferenceTools.jl/pull/4.

**Comment by JoshuaLampert** [comment]
cjdoris/PreferenceTools.jl#4 is merged. So this issue can be closed.
