### ISSUE TITLE
Repo reorganizations?

### ISSUE THREAD

**Issue by timholy** [JuliaIO/HDF5.jl#137]
I'd be curious about people's thoughts on two possible changes:
- Should JLD be split out into a separate package, one that requires HDF5? The main advantage would be a slight simplification of usage (`using JLD` rather than `using HDF5, JLD`).
- Should this move to JuliaLang? For a long time, having this be under my name was basically a way of saying "I'll stand for this" and therefore being motivated to fix it if it broke. While I know some organization packages have flourished, there have been periods where some other JuliaLang packages (Tk, Cairo being ones I noticed especially) were not particularly well maintained---I think the problem is that if it's owned by a group, it can work out that no one person feels obliged to take responsibility. At this point, though, this package seems on solid footing and unlikely to decay even if I were to take less responsibility for it---especially since we have such an awesome community. Would some of you who have contributed so much feel that it were a little fairer if it belonged to a neutral organization?

**Comment by musm** [comment]
Nothing remains to be done here so closing
