### ISSUE TITLE
Enable Blosc compression of JLD files by default?

### ISSUE THREAD

**Issue by stevengj** [JuliaIO/HDF5.jl#178]
As discussed in #173 and #174, it is worth considering enabling `compress=true` by default when saving JLD files.  In all the benchmarks I've done so far, even with single-threaded Blosc this has a performance within a factor of two of uncompressed HDF5 (with the worst case being random data that does not benefit from compression), and is faster than uncompressed HDF5 for data that compresses well.

(This is dramatically better than zip/deflate compression, which can be orders of magnitude slower than uncompressed HDF5.)

Any other stress tests would be appreciated (just pass `compress=true` to `save` or `jldopen`).  Note that compression is not used for small datasets (< 8k).

cc: @jakebolewski, @dmbates, @kmsquire, @StefanKarpinski

**Comment by stevengj** [comment]
Note that Blosc has been working on Windows for a while.

However, I don't see a clamor of need for compressed HDF5/JLD files, so maybe we should just leave it as an option.

**Comment by davidssmith** [comment]
*clamors*

Doesn't Blosc improve read performance on large files?  If so, seems worth enabling.

**Comment by stevengj** [comment]
A downside of enabling it by default is that it will be harder for other HDF5 applications to extract data from the file (assuming they don't link to Blosc too).

**Comment by davidssmith** [comment]
Does it make any sense to enable by default on JLD but not for HDF5?

**Comment by stevengj** [comment]
@davidssmith, definitely this would only be for JLD, and it is true that most people saving files for interchange with other programs would probably use the raw HDF5 interface.

**Comment by timholy** [comment]
I'm fine with turning it on if (1) it doesn't substantially hurt performance for data that compress poorly, and (2) if people besides myself take responsibility for fixing any breakages :-).

**Comment by stevengj** [comment]
@jakebolewski, could you re-run your benchmarks now that things should be working?

**Comment by kleinhenz** [comment]
closing since it looks like the consensus is that we would only do this for JLD not HDF5.
