### ISSUE TITLE
Shared arrays no longer shared after loaded from jld file

### ISSUE THREAD

**Issue by skariel** [JuliaIO/HDF5.jl#182]
Consider the following simple example:

``` Julia
using HDF5, JLD

addprocs(2)

# create and save the shared array
a = SharedArray(Int64, 100)
save("example.jld", "a", a)

# clear the shared array...
a = nothing

# load what we saved...
a = load("example.jld")["a"]

# try to use it...
@parallel for i in 1:length(a)
    a[i] = i
end

# Now its filled with zeros, as if it were a normal array.
@show a
```

So two issues here:

1) is there a way to "reassign" a shared array to processes? This seems useful when adding/removing procs. Well, this has little to with JLD, but still, has to do with this issue :)
2) JLD should use the shared array constructor, I'm not sure how it constructs the array now

Thanks!

**Comment by kleinhenz** [comment]
closing this since it looks like a JLD issue. I think making this work automatically is definitely outside the scope of HDF5.jl
