### ISSUE TITLE
sparse jld file saved in win not work in linux

### ISSUE THREAD

**Issue by paulanalyst** [JuliaIO/HDF5.jl#202]
data=load("D_z_win.jld","D")
ERROR: .... on the end of bug
File D_z_win.jld was created at win 7/64 in this same way like this sparse (I,J,V)
On the win machine is julia 3.0

samsung2@samsung2:~$ julia
_
_ _ ()_ | A fresh approach to technical computing
() | () () | Documentation: http://docs.julialang.org
_ _ _| | __ _ | Type "help()" for help.
| | | | | | |/ ` | |
| | || | | | (| | | Version 0.3.3 (2014-10-21 20:18 UTC)
/ |\'|||_'| | Official http://julialang.org release
|_/ | i686-linux-gnu

julia> I=vec(readcsv("I.txt"));

julia> J=vec(readcsv("J.txt"));

julia> V=vec(readcsv("V.txt"));

julia> D=sparse(int(I),int(J),int(V));

julia> using HDF5,JLD

julia> save("D.jld","D",D)

julia> data=load("D.jld","D")
10000000x30000 sparse matrix with 1000000 Int32 entries:
[170590 , 1] = 1
[275820 , 1] = 1
[3131540 , 1] = 1
[3182060 , 1] = 1
[3286470 , 1] = 1
[3398480 , 1] = 1
[3690470 , 1] = 1
⋮
[3215620 , 30000] = 1
[3509960 , 30000] = 1
[4311630 , 30000] = 1
[4984860 , 30000] = 1
[5425410 , 30000] = 1
[6618640 , 30000] = 1
[6698030 , 30000] = 1
[7282230 , 30000] = 1

julia> data=load("D_z_win.jld","D")
ERROR: stored type Base.SparseMatrix.SparseMatrixCSC{Core.Float64,Core.Int64} does not match currently loaded type
in jldatatype at /home/samsung2/.julia/v0.3/HDF5/src/jld_types.jl:637
in read at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:331
in read at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:316
in anonymous at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:983
in jldopen at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:237
in load at /home/samsung2/.julia/v0.3/HDF5/src/JLD.jl:982

Paul

**Comment by simonster** [comment]
@paulanalyst Can you give the output of `versioninfo()` and `xdump(Base.SparseMatrix.SparseMatrixCSC{Core.Float64,Core.Int64})` on both systems?

**Comment by paulanalyst** [comment]
win 7 Home Premium 64, SP1

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-11-23 20:19 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> versioninfo()
Julia Version 0.3.3
Commit b24213b* (2014-11-23 20:19 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> xdump(Base.SparseMatrix.SparseMatrixCSC{Core.Float64,Core.Int64})
SparseMatrixCSC{Float64,Int64}::DataType  <: AbstractSparseArray{Float64,Int64,2}
  m::Int64::DataType  <: Signed
  n::Int64::DataType  <: Signed
  colptr::Array{Int64,1}::DataType  <: DenseArray{Int64,1}
  rowval::Array{Int64,1}::DataType  <: DenseArray{Int64,1}
  nzval::Array{Float64,1}::DataType  <: DenseArray{Float64,1}

--------------------------
Ubuntu 14.

samsung2@samsung2:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.3 (2014-10-21 20:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org release
|__/                   |  i686-linux-gnu

julia> versioninfo()
Julia Version 0.3.3
Commit 21d5433* (2014-10-21 20:18 UTC)
Platform Info:
  System: Linux (i686-linux-gnu)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 32
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> xdump(Base.SparseMatrix.SparseMatrixCSC{Core.Float64,Core.Int64})
SparseMatrixCSC{Float64,Int64}::DataType  <: AbstractSparseArray{Float64,Int64,2}
  m::Int32::DataType  <: Signed
  n::Int32::DataType  <: Signed
  colptr::Array{Int64,1}::DataType  <: DenseArray{Int64,1}
  rowval::Array{Int64,1}::DataType  <: DenseArray{Int64,1}
  nzval::Array{Float64,1}::DataType  <: DenseArray{Float64,1}
----------------------------------------------------------------------------------
Paul

**Comment by timholy** [comment]
Bingo. One machine is 32-bit, the other 64-bit. Given that `m` and `n` are declared as `Int`, this makes the two structures incompatible.

Next question is, what to do about it---fixing it in general runs up against the problem that a `typealias` doesn't leave fingerprints. Do we catch exceptions and then morph the structure to make it compatible? This is not easy to fix.

**Comment by timholy** [comment]
Also, should we store the `WORD_SIZE` in the `*.jld` file somewhere? Maybe also `ENDIAN_BOM` (it's not an issue now, but someday it might be).

**Comment by paulanalyst** [comment]
Tim
maybe to keep and save (in jld file) only vectors after 
findnz(SparseMatrix)
and at load jld file make sparse(vec1,vec2,vec3)

Paul

W dniu 2015-01-08 o 14:14, Tim Holy pisze:

**Comment by timholy** [comment]
One can always write a special-purpose function (you can do that locally, too---you'd also want to save the overall size), but for the package it's better to come up with a general solution that works for any type.

**Comment by kleinhenz** [comment]
closing since this looks like a JLD issue.
