### ISSUE TITLE
Allow non-literal bitstype immutables as type parameters

### ISSUE THREAD

**Issue by mbauman** [JuliaIO/HDF5.jl#204]
This is the unfinished work from #203: while types can now have arbitrary bitstype immutables as parameters, JLD does not support it.

Currently, the type is simply represented as a string, like `Foo{Bar(1)}`.  Unfortunately, to construct the type from such a string, we'd have to `eval` the contents as the inverse of 5c7db4d9fbf48b884e2333e46a9798ac4e89d997 does.  Since `Bar(1)` is printed without its module name and could do anything, we cannot do this safely (even if Bar is a bits immutable, its constructor could do something nasty).

So I think we'll have to look into a new way of serializing type parameters as @simonster suggested in [#203 (comment)](https://github.com/timholy/HDF5.jl/pull/203#issuecomment-69052365):

>  It seems that we either need to serialize the types/type parameters using JLD or come up with our own string representation of types that can be used to reconstruct them.

**Comment by kleinhenz** [comment]
closing since this seems like a JLD issue.
