### ISSUE TITLE
JLD interoperability between 32 and 64 bits

### ISSUE THREAD

**Issue by GunnarFarneback** [JuliaIO/HDF5.jl#209]
What are the ambitions with respect to interoperability between 32 and 64 bit Julia for the JLD format?

Saving a substring from 32 bit Julia 0.3

```
julia> using HDF5, JLD

julia> s = SubString{ASCIIString}("abc", 2, 3)
"bc"

julia> save("foo.jld", "s", s)
```

and then loading it in 64 bit Julia fails:

```
julia> using HDF5, JLD

julia> load("foo.jld")
ERROR: stored type Base.SubString{Core.ASCIIString} does not match currently loaded type
 in jldatatype at /home/gunnar/.julia/HDF5/src/jld_types.jl:637
 in read at /home/gunnar/.julia/HDF5/src/JLD.jl:299
 in read at /home/gunnar/.julia/HDF5/src/JLD.jl:284
 in anonymous at /home/gunnar/.julia/HDF5/src/JLD.jl:932
 in jldopen at /home/gunnar/.julia/HDF5/src/JLD.jl:205
 in load at /home/gunnar/.julia/HDF5/src/JLD.jl:931
```

Nothing terribly surprising about it since the SubString type contains fields of type Int, but rather annoying since substrings tend to crop up anytime you do string processing.

This is of course not limited to substrings but happens to any type with explicit Int fields, both those you define yourself and those you get from Base or packages. Is there anything constructive that can be done about it or should the problem just be documented?

**Comment by GunnarFarneback** [comment]
I see now that there's related discussion in #202.

**Comment by timholy** [comment]
This is important. I am pretty swamped right now, though, so I confess I haven't really gotten serious about a plan for a fix.

**Comment by kleinhenz** [comment]
closing since this looks like a JLD issue.
