### ISSUE TITLE
Cannot load variables in v0.4 that load fine in v0.3

### ISSUE THREAD

**Issue by milktrader** [JuliaIO/HDF5.jl#212]
This is breaking tests on Quandl for current nightlies and when I tried loading in REPL I likewise got this error

``` julia
julia> load(Pkg.dir("Quandl/test/response.jld"))["missing"]
WARNING: type JLD.AssociativeWrapper{Core.String,Core.String,Base.Dict{Core.String,Core.String}} not present in workspace; reconstructing
WARNING: type Core.String not present in workspace; interpreting array as Array{Any}
WARNING: type Core.String not present in workspace; interpreting array as Array{Any}
ERROR: `convert` has no method matching convert(::Type{Dict{AbstractString,AbstractString}}, ::##JLD.AssociativeWrapper{Core.String,Core.String,Base.Dict{Core.String,Core.String}}#12109)
 in jlconvert at /Users/Administrator/.julia/v0.4/HDF5/src/jld_types.jl:406
 in read_scalar at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:359
 in read at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:331
 in read at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:316
 in anonymous at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:978
 in jldopen at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:237
 in load at /Users/Administrator/.julia/v0.4/HDF5/src/JLD.jl:977
```

**Comment by milktrader** [comment]
https://github.com/milktrader/Quandl.jl/issues/74

**Comment by mbauman** [comment]
Thanks for the report.  Looks like we'll need a switch for `AbstractString` like that for `UInt` (https://github.com/timholy/HDF5.jl/blob/efbb3f636bbb477b48ae60dceee80ef0d5e7ec9c/src/JLD.jl#L14-L18).  I probably won't have time to fully test a solution for a few days, but I can do this if nobody beats me to it.

**Comment by timholy** [comment]
@mbauman, how about this for a deal: I'll solve this one, but if you haven't dealt with https://github.com/timholy/HDF5.jl/pull/203#issuecomment-69121466 I'd love to have that done sooner rather than later. Related: #211, although we should figure out how to implement that one.

**Comment by mbauman** [comment]
Deal. :)

**Comment by musm** [comment]
stale
