### ISSUE TITLE
Not yet supported error from dump

### ISSUE THREAD

**Issue by multidis** [JuliaIO/HDF5.jl#223]
Trying to see file structure for this [HDF5 file](https://www.coinsetter.com/resources/docs/COINSETTER_execution_reports_03_2014-10_2014.h5) downloaded from [this](https://www.coinsetter.com/api/historical-tick-data) page:

```
fid = h5open("COINSETTER_execution_reports_03_2014-10_2014.h5", "r")
dump(fid)
```

HDF5File len 2
  **DATA_TYPES**: HDF5Group len 7
    Compound_CoinsetterTick: HDF5Datatype 
      id: Int32 50331961
      toclose: Bool true
      file: #undef
    Enum_: HDF5Datatype 
      id: Int32 50331962
      toclose: Bool true
      file: #undef
    Enum_Boolean: HDF5Datatype 
      id: Int32 50331963
      toclose: Bool true
      file: #undef
    Enum___REPLACED_1: HDF5Datatype 
      id: Int32 50331964
      toclose: Bool true
      file: #undef
    Enum___REPLACED_2: HDF5Datatype 
      id: Int32 50331965
      toclose: Bool true
      file: #undef
    Enum___REPLACED_3: HDF5Datatype 
      id: Int32 50331966
      toclose: Bool true
      file: #undef
    String_VariableLength: HDF5Datatype 
      id: Int32 50331967
      toclose: Bool true
      file: #undef
  ticks.1414010709129_16:45:09: HDF5Dataset (246000,) : 
**ERROR: Not yet supported**

Which aspect of this file is not supported? Any alternative commands to explore the structure / data organization? Thanks.

**Comment by musm** [comment]
Stale, plus the download link is no longer available. Please open a new issue if this is still a problem, thanks.
