### ISSUE TITLE
Intermittent "H5Fget_obj_count(): not a file id" again

### ISSUE THREAD

**Issue by multidis** [JuliaIO/HDF5.jl#235]
Same problem as this issue
https://github.com/timholy/HDF5.jl/issues/194
Similar to this one as well
https://github.com/timholy/HDF5.jl/issues/95

**HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140524907227008:**
  #000: ../../../src/H5F.c line 447 in H5Fget_obj_count(): not a file id
    major: Invalid arguments to routine
    minor: Bad value
error in running finalizer: ErrorException("error getting object count")

Comes up once every 100 times or so when saving the same data type to jld:

```
save("filename.jld", "someType", someTypeObject)
```

Default HDF5 setup on Ubuntu Linux. Not really specific to any particular custom type.

Not completely sure but it appears that the error comes up only when Julia is **multicore**-started. Is it possible that the fix released for the referenced bugs fails when **one of several multicore threads is used**?

**Comment by multidis** [comment]
Pkg.status()

- HDF5                          0.4.12+            803a5955


    versioninfo()

Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: AMD FX(tm)-8350 Eight-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Piledriver)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by simonster** [comment]
Can you try updating HDF5? The latest version is 0.4.15. (`Pkg.update()` should work, unless you're on a branch, in which case you'll need to `Pkg.free("HDF5")` first.)

**Comment by multidis** [comment]
Strange, I do not recall ever pinning HDF5 to a specific commit... Did the update after `Pkg.free("HDF5")`, now 0.4.16. Starting to test again (takes a while for this non-reproducible error to come up).

**Comment by multidis** [comment]
Actually, the problem comes up in a Docker container running all the latest packages. And the fix mentioned in those issues was implemented quite a few versions ago anyway. Thus, the same error persists with the latest `HDF5.jl`.

**Comment by simonster** [comment]
I guess this could happen if you're passing JldFile objects between Julia processes as part of some data structure or unintentionally as part of a closure environment, which wouldn't actually work, but would give an error when one of the JldFile objects gets serialized. Otherwise I can't see how this would be possible.

**Comment by multidis** [comment]
No closures as far as I can tell. Confirming the same occasional error after some extensive testing:

HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 139867353823104:
  #000: ../../../src/H5F.c line 447 in H5Fget_obj_count(): not a file id
    major: Invalid arguments to routine
    minor: Bad value
error in running finalizer: ErrorException("error getting object count")

Still not sure if multicore run has something to do with it.

**Comment by musm** [comment]
stale. Reopen if this is still an issue.
