### ISSUE TITLE
Is it possible to delete a group or dataset from an HDF5 file opened with "r+"?

### ISSUE THREAD

**Issue by dmbates** [JuliaIO/HDF5.jl#255]
I have an HDF5 that stores data from several experiments.  The data from each experiment is in an HDF5 group.  When I was storing the data from one of these experiments I encountered an error midway through the process.  The incomplete group was left in the HDF5 file.  Can I drop that group entirely or, perhaps, overwrite it?  I can always fall back on creating a new file and copying each group except the problematic one from the old file to the new file, but I hope there is a better way.

**Comment by timholy** [comment]
Check just above this link: https://github.com/timholy/HDF5.jl/blob/master/doc/hdf5.md#low-level-routines

**Comment by bjarthur** [comment]
um, yea, but, the memory is not actually reclaimed per section 5.2 here:

https://www.hdfgroup.org/HDF5/doc1.6/UG/10_Datasets.html

**Comment by eschnett** [comment]
(1) In HDF5 1.8 and earlier, the memory is not reclaimed if the file was closed in the mean time. The solution is to copy the file with an HDF5-aware utility such as `h5repack`: `h5repack oldfile.h5 newfile.h5`. This will make a copy of all the file content, creating a smaller file if there was unused space in the old file. You can additionally also modify certain storage options such as compression or chunking.

(2) In HDF5 1.10, free space is reclaimed.

**Comment by lucianainpa** [comment]
HI,
I need use a old version of the hdf5 in my computer to R, but, I don't know where is it.
I need a old version because I need use functions like> hdf5load...
Can you help me?

**Comment by louisabraham** [comment]
@eschnett Do you have a reference for "In HDF5 1.10, free space is reclaimed"?

Also, when you delete a dataset, its becomes Unaccounted, not free.
