### ISSUE TITLE
attrs(h5)["a"]=1 saves as Int32

### ISSUE THREAD

**Issue by ggggggggg** [JuliaIO/HDF5.jl#260]
```julia
julia> attrs(h5)["b"]=typemax(Int)
9223372036854775807

julia> dump(attrs(h5)["b"])
HDF5.HDF5Attribute 
  id: Int32 100663297
  file: HDF5.HDF5File len 2
    a: HDF5Dataset () : 1
    b: HDF5Dataset (10,) : [1,2,3,4,5 

julia> Pkg.installed("HDF5")
v"0.5.5"
```
I'm pretty sure it should be saved as an Int64.

**Comment by timholy** [comment]
Agreed, or more precisely whatever type `Int` really is on your system.

**Comment by eschnett** [comment]
You are looking at the internal representation of a reference to an HDF5 attribute. The value of the attribute is not present there; instead, `id` is a pointer-like object that allows HDF5 to locate and read the attribute in the file:
```Julia
julia> a_read(h5,"b")
9223372036854775807
```
