### ISSUE TITLE
double free error

### ISSUE THREAD

**Issue by longqian95** [JuliaIO/HDF5.jl#275]
run the following code will cause double free error:

using HDF5
workspace()
using HDF5
exit()

**\* glibc detected **\* julia: double free or corruption (!prev): 0x000000000302e500 ***

Julia: Version 0.4.0 (2015-10-08 06:20 UTC)
HDF5: 0.5.6
OS: CentOS release 6.7

**Comment by yuyichao** [comment]
This is caused by `Blosc`

**Comment by musm** [comment]
I don't think this is a problem anymore
