### ISSUE TITLE
Set library version bounds to 1.8

### ISSUE THREAD

**Issue by eschnett** [JuliaIO/HDF5.jl#287]
HDF5 version 1.8 can produce a metadata layout that is more efficient than that of version 1.6. I gather this is most noticeable for groups that contain many entries. The disadvantage of using this metadata layout is that the respective files are not readable by HDF5 version 1.6. (Of course they can be converted; this only concerns the metadata, not the actual data stored in the file.)

I wonder whether this should be the default?

**Comment by eschnett** [comment]
Maybe this should be the default for the `JLD` package, which also uses a non-standard `Blosc` filter by default.

**Comment by timholy** [comment]
I don't know how big of a difference it is. But I would guess that few people are using anything earlier than 1.8 these days.

**Comment by simonster** [comment]
I think I tried this at some point with JLD. It made slightly smaller files but didn't actually seem any faster, but that may have been because I only tested with cases where IO was not really a factor and the overhead primarily came from libhdf5.

**Comment by eschnett** [comment]
HDF5 1.8 is faster if there are groups with many (hundreds or more) elements. If I understand correctly, the new layout uses a B-tree for the group's elements.

**Comment by musm** [comment]
closed by https://github.com/JuliaIO/HDF5.jl/pull/396
