### ISSUE TITLE
add method `isopen("file.h5")`

### ISSUE THREAD

**Issue by gasagna** [JuliaIO/HDF5.jl#294]
Hi, 

I need to test whether an hdf file is open or not. In `Base` we have `isopen`, maybe it might be useful to add a method to it.

Thanks

**Comment by stevengj** [comment]
`isopen` in Base does not work with a filename, and if you take a `String` argument there is no way to make it specific to HDF5.

We can (and probably should) certainly implement `isopen(fid::HDF5File)`, but this may not be what you want?

**Comment by stevengj** [comment]
[`H5Fget_obj_count`](https://support.hdfgroup.org/HDF5/doc/RM/RM_H5F.html#File-GetObjCount) can determine whether a file has been opened multiple times, I think?

**Comment by gasagna** [comment]
I actually do not remember what my use case was at the time I opened this issue, but a `isopen(fid::HDF5File)` method seems certainly worth having.

**Comment by simonster** [comment]
We set the `fid.id = -1` when the file is closed, so this could just be `isopen(fid::HDF5File) = fid.id != -1`. (`H5Fget_obj_count` is not quite right since HDF5 could reuse the same file ID for a different file after the file is closed.)
