### ISSUE TITLE
Reading HDF5 files containing boolean (H5T_BITFIELD) values

### ISSUE THREAD

**Issue by tamasgal** [JuliaIO/HDF5.jl#307]
I'm trying to open files which contain `Table`s written via pytables and getting this error:

```
    ERROR: Class id 4 is not yet supported
     in hdf5_to_julia_eltype at /Users/tamasgal/.julia/v0.4/HDF5/src/plain.jl:1828
     in read at /Users/tamasgal/.julia/v0.4/HDF5/src/plain.jl:1380
     in read at /Users/tamasgal/.julia/v0.4/HDF5/src/plain.jl:1197
     in h5read at /Users/tamasgal/.julia/v0.4/HDF5/src/plain.jl:622
```

This only occurs for tables containing the type `tables.BoolCol`, corresponding to `H5T_BITFIELD`. Is it planned to support this in near future? Or is there nice workaround? Currently I need to reprocess the HDF5 files and convert the boolean column to Int8 to have `0` and `1`, which is of course currently just a dirty workaround?

Here is a dummy example of the Python code, if you want to recreate `foo.h5` and see the error:

```
# Julia code to read the file
using HDF5
data = h5read("foo.h5", "event_info")
```

```
# Python script to create foo.h5, which holds a table with a boolean column
import tables

class EventInfoDesc(tables.IsDescription):
    event_id = tables.UIntCol()
    mc_t = tables.Float64Col()
    overlays = tables.UInt8Col()
    triggered = tables.BoolCol()   # This causes trouble

h5file = tables.open_file('foo.h5', mode="w", title="Foo")
filters = tables.Filters(complevel=5)
event_info = h5file.create_table('/', 'event_info',
                                 EventInfoDesc, "Event Info",
                                 filters=filters)

# Writing some random rows
for i in range(10):
    event_info.row['event_id'] = i
    event_info.row['mc_t'] = i*2
    event_info.row['overlays'] = i*3
    event_info.row['triggered'] = True
    event_info.row.append()

event_info.flush()
h5file.close()
```

**Comment by timholy** [comment]
As you noticed, H5T_BITFIELD isn't supported currently, presumably because no one who has contributed to the package has needed them yet. Obviously it would be good to have all types supported. If you need this soon, your best bet is to take a crack at adding it yourself, although I can't rule out the possibility that some enterprising soul will attempt it for you.

**Comment by tamasgal** [comment]
Yea, I already tried but I'm a bit confused about converting a bit entry into a byte structure. I hope I'll figure it out… I started learning Julia a few days ago ;-)

**Comment by timholy** [comment]
You're very ambitious! :+1:

I am traveling and so not checking very often, but you can post questions here and I or someone may be able to help answer questions. I haven't thought about this at all (either from the libhdf5 side or the Julia side), but I wonder if you can just leave it as a `UIntN` (where `N` is the correct # of bits). If there's a way to declare the structure of the bitfield, then presumably julia could automatically define some `Enum`s from the datatype?

If you really want to signal that these are bitfields, you could define
```
immutable BitField8
    val::UInt8
end
```
and so on, and use `reinterpret` as needed to convert arrays of `UIntN`<-->`BitFieldN`.

**Comment by tamasgal** [comment]
Alright, I'll do my best, thanks so far! ;-)

**Comment by kdmurray91** [comment]
@tamasgal Did you get anywhere with this? I need HDF5 IO support for `BitArray`s and can take a crack at this.

**Comment by tamasgal** [comment]
Not yet, sorry! It's currently on hold until October...

**Comment by kdmurray91** [comment]
Ok, so I have hit a wall where I need this functionality. Would someone more familiar with both HDF5 and HDF5.jl be able to supervise and/or review my attempt at an implementation? @timholy
