### ISSUE TITLE
Appveyor tests are very slow

### ISSUE THREAD

**Issue by eschnett** [JuliaIO/HDF5.jl#310]
While the Linux and OS X tests finish within minutes, the Appveyor tests take about an hour. It's hit or miss whether Appveyor finishes in time. This leads to many spurious failures.

Does anyone know why Appveyor is so slow?

If we can't correct this, then we should either pay for a plan that gives us more build time, or disable Appveyor. Having spurious failures like this is inconvenient in many ways.

**Comment by yuyichao** [comment]
Only the nightly takes that long and it's from depwarn.

**Comment by musm** [comment]
can we close this

**Comment by musm** [comment]
no longer the case
