### ISSUE TITLE
Installation problem - Mac OS X

### ISSUE THREAD

**Issue by pazzo83** [JuliaIO/HDF5.jl#315]
Hi,

I am having issues building HDF5 on my Mac.  It seems the creation of the libhdf5.la library is failing.

This is the error I'm getting

```
LoadError: File AbstractString["libhdf5.la"] was not created successfully 
(Tried to run BinDeps.SynchronousStepCollection ... 

while loading /Users/christopheralexander_nmp/.julia/v0.4/HDF5/deps/build.jl, 
in expression starting on line 27
```

During the build process, I keep seeing this warning:

```
ld: warning: directory not found for option '-L/Users/christopheralexander_nmp/.julia/v0.4/HDF5/deps/usr/lib'
```

That directory is never created.

Any ideas as to why this might be happening?  I've never had this issue building this package before.

Thanks!

**Comment by pazzo83** [comment]
Sorry about this, this was a stupid issue with permissions and OS X 10.11.

**Comment by mbrookhart** [comment]
I'm running into this error on a suse machine, what was your fix?
