### ISSUE TITLE
FYI: HDF5 query language [needs support?]

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaIO/HDF5.jl#322]
I just noticed: https://hdfgroup.org/wp/tag/query-language/

[It mentions e.g. Python, should also Julia..]

Should this package [and say JLD] add support? Or another (new) one [under JuliaIO]?

[I've not looked closely at the query language (or LINQ.jl). Or Searchlight ORM. See about that (while off-topic for HDF5(?), but on-topic for ORM/non-SQL quering) at https://github.com/essenciary/Genie.jl/issues/17 ]

**Comment by simonbyrne** [comment]
Based on https://www.hdfql.com/, it appears not to be open source (at least, I don't see the source anywhere).
