### ISSUE TITLE
Pkg.build fails with BinDeps.SynchronousStepCollection

### ISSUE THREAD

**Issue by GlenHertz** [JuliaIO/HDF5.jl#324]
On Julia 0.5.0-rc3 on RHEL6.4 I tried to `Pkg.add("HDF5")` and it fails with build errors:

```
LoadError: File AbstractString["libhdf5.la"] was not created successfully (Tried to run BinDeps.SynchronousStepCollection(`...
...
while loading /remote/us01home32/hertz/.julia/v0.5/HDF5/deps/build.jl, in expression starting on line 27
```

The line in question in build.jl:27 is:

`@compat @BinDeps.install Dict(:libhdf5 => :libhdf5)`

From `~/.julia/v0.5/HDF5/deps/builds/libhdf5` I checked `libhdf5.la`:

```
% du src/libhdf5.la
4   src/libhdf5.la

```

So it looks like the file isn't getting built correctly (since it is only 4 kB)...even though `make` completes successfully.   

I tried `Pkg.rm("HDF5")` to start from scratch but it did not help.  Any ideas?

**Comment by tkelman** [comment]
paste or gist the entire build output

**Comment by ulfworsoe** [comment]
Building on CentOS I had a similar problem. The missing file `libhdf5.la` is correctly built, but `BinDeps` does not find it. Manually making a symlink to the library in a place where BinDeps looks seems to fix it. Specifically, following made the build process succeed:
- Do `Pkg.add("HDF5")`, let it run until it fails.
- Manually make symlinks 
```
.../HDF5/deps/builds/libhdf5/lib/libhdf5.la -> deps/builds/libhdf5/src/libhdf5.la
.../HDF5/deps/builds/libhdf5/libhdf5.la -> deps/builds/libhdf5/src/libhdf5.la
```
- Run `Pkg.build("HDF5")`

**Comment by GlenHertz** [comment]
@tkelman I've uploaded my complete build output for HDF5 [here](https://gist.github.com/GlenHertz/830dd7c372bb698ef0781d5f4962d87f).

@ulfworsoe Thanks for the instructions, that fixes my issues.

**Comment by rohitvarkey** [comment]
Just ran into this issue while trying to install `LightGraphs` on my university cluster. 

@ulfworsoe's instructions fixes it though.

**Comment by sbromberger** [comment]
yup, this bit me just now as well on a Linux build. I will try the workaround.

**Comment by GordStephen** [comment]
Same issue, workaround worked for me as well. Also on RHEL, so it seems like that may be a common thread.

**Comment by omus** [comment]
Same issue on Amazon Linux. Unfortunately the proposed solution doesn't work for me as I need to have a solution which is non-interactive. My alternative is to install the [EPEL repository](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/) and install the "hdf5-devel" system package before installing HDF5.jl.

**Comment by musm** [comment]
Does https://github.com/JuliaIO/HDF5.jl/pull/367 fix this @omus ?

**Comment by omus** [comment]
@musm yes, it fixes the problem.

**Comment by musm** [comment]
ok thanks! Will merge #367 then

**Comment by musm** [comment]
I think I will close this now because I think #367  has fixed the issue, if not please open an another issue

**Comment by musm** [comment]
new version with the fix has been tagged and gone through metadata fyi
