### ISSUE TITLE
Pkg.add new

### ISSUE THREAD

**Issue by APEGeo** [JuliaIO/HDF5.jl#345]
I have tried  to delete and to reinstall  Julia,  because OpenCL package didn't work, so I did it in order to understand if it was due to some bad installation problem. But when I tried to reinstall Julia, it gave me problems for the building of other packages, including this. How can I fix it? 
![pkginstal1](https://cloud.githubusercontent.com/assets/18010044/20622162/d4a85392-b301-11e6-997d-ac657fecf15e.PNG)
![pkginstall2](https://cloud.githubusercontent.com/assets/18010044/20622163/d4a8d678-b301-11e6-8fa8-117b7b3ab335.PNG)

**Comment by juliohm** [comment]
Looking at the error message, it looks like a similar issue was reported in `BinDeps.jl`: https://github.com/JuliaLang/BinDeps.jl/issues/240

**Comment by musm** [comment]
is this still an issue?

**Comment by juliohm** [comment]
@APEGeo can you please check if the issue is still happening?

**Comment by musm** [comment]
closing, if this is still an issue please reopen with further logs
