### ISSUE TITLE
Reading in HDF5Compound types

### ISSUE THREAD

**Issue by tamasgal** [JuliaIO/HDF5.jl#347]
I am trying to read data from an HDF5 file, which was created by pytables and uses HDF5Compound types. I stumbled upon a few posts where I read that read reading compound types works well but could not find a single example. Well, I found one reading in an array with complex numbers using `reinterpret` but I did not manage to make it work with my data.

The reading procedure is clear:

```
hits = h5open("the_dataset.h5", "r") do file
    read(file, "/hits")
end
```

And this shows already:

```HDF5.HDF5Compound(UInt8[0x1d,0x00,0x00,0x00,0x00,0x00,0x00,0xf8,0x7f,0x00  …  0x07,0xe8,0xfa,0x02,0x1c,0x00,0xae,0x0c,0x00,0x00],Type[UInt8,Float64,Float64,Float64,UInt32,UInt32,UInt32,Float64,Float64,Float64,Int32,Int32,UInt8,UInt8,UInt32],String["channel_id","dir_x","dir_y","dir_z","dom_id","id","pmt_id","pos_x","pos_y","pos_z","t0","time","tot","triggered","event_id"],UInt64[0x0000000000000000,0x0000000000000001,0x0000000000000009,0x0000000000000011,0x0000000000000019,0x000000000000001d,0x0000000000000021,0x0000000000000025,0x000000000000002d,0x0000000000000035,0x000000000000003d,0x0000000000000041,0x0000000000000045,0x0000000000000046,0x0000000000000047])```

But then, no idea how to access the arrays inside it.

This is the output of `hits.membertype`:

```
15-element Array{Type,1}:
 UInt8  
 Float64
 Float64
 Float64
 UInt32 
 UInt32 
 UInt32 
 Float64
 Float64
 Float64
 Int32  
 Int32  
 UInt8  
 UInt8  
 UInt32
```

I tried to parse the data using`reinterpret()` but I suspect that even it would read in the whole file at once, which is problematic, since the usual file size is about 20GB.

However, this is how I thought it could work:

`reinterpret(hits.membertype, hits.data)`

But I get:

```
LoadError: MethodError: no method matching reinterpret(::Array{Type,1}, ::Array{UInt8,1})
Closest candidates are:
  reinterpret{T,S}(!Matched::Type{T}, ::Array{S,1}) at array.jl:73
  reinterpret{T,S}(!Matched::Type{T}, ::Array{S,N}) at array.jl:79
  reinterpret{T,S,N}(!Matched::Type{T}, ::Array{S,N}, !Matched::Tuple{Vararg{Int64,N}}) at array.jl:86
  ...
while loading In[24], in expression starting on line 1
```

So I am not sure how to extract and pass the data structure to reinterpret...

**Comment by tamasgal** [comment]
Alright, I did a tiny step forward.

I defined a new immutable:

```
immutable Hit
    channel_id::UInt8
    dir_x::Float64
    dir_y::Float64
    dir_z::Float64
    dom_id::UInt32
    id::UInt32
    pmt_id::UInt32
    pos_x::Float64
    pos_y::Float64
    pos_z::Float64
    t0::Int32
    time::Int32
    tot::UInt8
    triggered::UInt8
    event_id::UInt32
end
```

and then tried to `reinterpret` the data with this new type using:

```
new_hits = reinterpret(Hit, c.data)
```

This showed no errors, but it has the wrong length. I opened the file in Python and it should have 15853492 rows, it however got 13511498 in Julia/HDF5.

I also inspected the very first "Hit" but except the very first field (`tot == 29` in decimal) the values are not correct. This is the output in Julia:

`Hit(0x1d,-1.0565890622713603e270,-1.0565890622713603e270,1.89e-321,0x00000000,0x00000000,0xf8000000,2.71549148875e-312,2.71549148875e-312,1.1414172618576e-310,318767104,0,0x00,0x00,0x00000000)`

and this should be the correct one (via Python/pytables):

```
channel_id          29.0
dir_x                NaN
dir_y                NaN
dir_z                NaN
dom_id               1.0
id                   0.0
pmt_id               0.0
pos_x                NaN
pos_y                NaN
pos_z                NaN
t0                   0.0
time          49993723.0
tot                 21.0
triggered            0.0
event_id             0.0
Name: 0, dtype: float64
```

I am really not sure what is going on there. Any hints are appreciated!

**Comment by simonster** [comment]
The structure seems to be stored without padding in the file (according to the offsets above), whereas a Julia immutable has architecture-specific padding between fields. The easiest way to access the data would probably be to create an IOBuffer from `c.data` and read the fields from that, then construct whatever data type you want.

**Comment by tamasgal** [comment]
Many thanks for the quick answer, OK so it is the padding. I don't really understand what you mean with reading the fields from the `IOBuffer`, though...

I tried this:

```
buf = IOBuffer(c.data)
new_hits2 = reinterpret(Hit, buf)[1]
```

But it yields

`LoadError: reinterpret: target type not a leaf bitstype`

I then tried this:

```new_hits2 = reinterpret(Hit, takebuf_array(buf))[1]```

but this gives the same "wrong" values.

**Comment by simonster** [comment]
```julia
buf = IOBuffer(c.data)
channel_id = read(buf, UInt8)
dir_x = read(buf, Float64)
...
```

**Comment by tamasgal** [comment]
Many thanks, it works that way but uhm... doing this for tens of millions of hits is quite huge. :-/

**Comment by simonster** [comment]
I would write it something like this:

```julia
immutable Hit
    channel_id::UInt8
    dir_x::Float64
    dir_y::Float64
    dir_z::Float64
    dom_id::UInt32
    id::UInt32
    pmt_id::UInt32
    pos_x::Float64
    pos_y::Float64
    pos_z::Float64
    t0::Int32
    time::Int32
    tot::UInt8
    triggered::UInt8
    event_id::UInt32
end

@eval function Base.read(io::IO, ::Type{Hit})
    Hit($([:(read(io, $(x))) for x in Hit.types]...))
end

buf = IOBuffer(c.data)
hits = Hit[]
while !eof(buf)
    push!(hits, read(buf, Hit))
end
```

**Comment by tamasgal** [comment]
Many thanks Simon, that does it nicely! Now I need to sit down to understand the `eval` part ;)

I think it would be great if there was an adhoc-type-creation (this should be possible in Julia I think) in HDF5.jl so it would do this when reading in HDF5Compound types. I need to dive into the source...
