### ISSUE TITLE
Cannot create mmap file on windows

### ISSUE THREAD

**Issue by musm** [JuliaIO/HDF5.jl#357]
I keep getting the following error
`ERROR: LoadError: LoadError: could not create file mapping: Access is denied.`

**Comment by musm** [comment]
Tested another pc, issue remains

**Comment by simonster** [comment]
A while ago, @tkelman tried to figure out how to make `mmap` work on Windows, but he was unsuccessful (https://github.com/JuliaIO/HDF5.jl/issues/89).

**Comment by Cody-G** [comment]
+1 for giving it another try...though I may know too little about Windows to help

**Comment by musm** [comment]
Funny that you ask, I gave it another try today, but wasn't able to fix it (btw I believe this is an issue with base julia's mmap ccall, but I wasn't able to figure out what)

**Comment by Cody-G** [comment]
Yes it's definitely an issue with mmap, not Julia.  I run into this often without using HDF5.jl

**Comment by simonbyrne** [comment]
Closed by #545
