### ISSUE TITLE
Typo: extendible

### ISSUE THREAD

**Issue by spalato** [JuliaIO/HDF5.jl#358]
Hi,

There is a typo in the docs (`doc/hdf5.md`). It mentions "extendible" dimensions, instead of extensible. That makes searching for the feature a bit harder!

"You can use extendible dimensions,"

Otherwise, works great, thanks!

**Comment by ggggggggg** [comment]
"extendible" is the term used in the HDF5 documentation, eg [here](https://support.hdfgroup.org/HDF5/Tutor/extend.html). Other than the pre-existing usage by the HDF Group, I don't see a strong reason to prefer one over the other.

**Comment by spalato** [comment]
Damn... I learnt a new word today! My brain was doing the typo all the time then.
