### ISSUE TITLE
Not yet supported

### ISSUE THREAD

**Issue by lukasfischer83** [JuliaIO/HDF5.jl#379]
Hi, I would like to read the timestamps of the attached file and get an "Not yet supported" error. Is there a way to just extract the column with the timestamp? Will this be supported in future?
Thanks, Lukas

[example.h5.zip](https://github.com/JuliaIO/HDF5.jl/files/850928/example.h5.zip)

**Comment by lukasfischer83** [comment]
Any progress in that?

**Comment by ggggggggg** [comment]
Can you do a bit more to help us understand what is going on? Try running `h5dump` (the command line tool) on your file, and post the output. This should tell us exactly what is in the file. And then can you post the exact code you used (starting at `using HDF5`) to get to your error, along with the complete error message?

**Comment by lukasfischer83** [comment]
The file is attached in the first post, running h5dump gives:
h5dump example.h5 
`h5dump example.h5 
HDF5 "example.h5" {
GROUP "/" {
   GROUP "AcquisitionLog" {
      DATASET "Log" {
         DATATYPE  H5T_COMPOUND {
            H5T_STD_U64LE "timestamp";
            H5T_STRING {
               STRSIZE 20;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            } "timestring";
            H5T_STRING {
               STRSIZE 256;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            } "logtext";
         }
         DATASPACE  SIMPLE { ( 2 ) / ( H5S_UNLIMITED ) }
         DATA {
         (0): {
               131199159589280000,
               "02/10/2016 22:05:58",
               "Acquisition started"
            },
         (1): {
               131199165642100000,
               "02/10/2016 22:16:04",
               "End of acquisition"
            }
         }
      }
   }
}
}
`

![image](https://cloud.githubusercontent.com/assets/10271325/25960828/780c5660-3678-11e7-9ea4-7588c0e4c419.png)

**Comment by ggggggggg** [comment]
You must have an out of date version of HDF5, I get a different error. It has to do with 'sizeof(filetype)` being larger than `typemax(UInt8)` here:
https://github.com/JuliaIO/HDF5.jl/blob/68ff60c31e4aaf4ed1ae1d1a18d247482ef86ef0/src/HDF5.jl#L1401

If I change `membersize` to a `Vector{UInt16}` I get a different error saying 
```
ERROR: MethodError: no method matching unpad(::Array{UInt8,1}, ::Int64)
 in read_row(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Array{Type,1}, ::Array{UInt16,1}) at /Users/user/.julia/v0.5/HDF5/src/HDF5.jl:1407
```
I don't know much about reading compound types, so I don't know what else to try.

**Comment by lukasfischer83** [comment]
I tested again in with version 0.8.1, now I am getting this Error:
```

LoadError: InexactError()
while loading untitled, in expression starting on line 2
 in read(::HDF5.HDF5Dataset, ::Type{Array{HDF5.HDF5Compound{3},N}}) at HDF5.jl:1382
 in read(::HDF5.HDF5Dataset) at HDF5.jl:1196
 in read(::HDF5.HDF5File, ::String) at HDF5.jl:1184
 in h5read(::String, ::String) at HDF5.jl:623
 in include_string(::String, ::String) at loading.jl:441
 in include_string(::Module, ::String, ::String) at eval.jl:34
 in (::Atom.##59#62{String,String})() at eval.jl:73
 in withpath(::Atom.##59#62{String,String}, ::String) at utils.jl:30
 in withpath(::Function, ::String) at eval.jl:38
 in macro expansion at eval.jl:71 [inlined]
 in (::Atom.##58#61{Dict{String,Any}})() at task.jl:60

```
Any ideas how this could be fixed? Thanks, Lukas

**Comment by ggggggggg** [comment]
Thats the first error I mentioned. There is a `UInt8` array, and it tries to assign a number too large for `UInt8` into that array. I don't know how to fix it.

**Comment by tknopp** [comment]
I get the same error for the files located at:
https://sourceforge.net/projects/ismrmrd/files/data/
It is a data format for storing MRI data. Would be great if would be possible reading it in Julia.

**Comment by tknopp** [comment]
I have a fix

**Comment by lukasfischer83** [comment]
I tested your proposition and got several lines further, but with the original file (first post) I get a new error now:

`MethodError: no method matching unpad(::Array{UInt8,1}, ::Int64)
 in read_row(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Array{Type,1}, ::Array{UInt64,1}) at HDF5.jl:1350
 in read(::HDF5.HDF5Dataset, ::Type{Array{HDF5.HDF5Compound{3},N}}) at HDF5.jl:1403
 in read(::HDF5.HDF5Dataset) at HDF5.jl:1196
 in read(::HDF5.HDF5File, ::String) at HDF5.jl:1184
 in h5read(::String, ::String) at HDF5.jl:623
 in include_string(::String, ::String) at loading.jl:441
 in eval(::Module, ::Any) at boot.jl:234
 in (::Atom.##65#68)() at eval.jl:102
 in withpath(::Atom.##65#68, ::Void) at utils.jl:30
 in withpath(::Function, ::Void) at eval.jl:38
 in macro expansion at eval.jl:101 [inlined]
 in (::Atom.##64#67{Dict{String,Any}})() at task.jl:60
`

Any hints?

**Comment by tknopp** [comment]
no, I also get stuck in that code path, see #426. But your error is different.

**Comment by lukasfischer83** [comment]
Ok, I got it to work, at least in my case.
I changed the line 1350

`push!(row, unpad(read(io, UInt8, dsize), H5T_STR_NULLPAD))`

to 

`push!(row, unpad(String(read(io, UInt8, dsize)), Cint(H5T_STR_NULLPAD)))`

and it works now... I don't know exactly what was going on there, just tried to get the function signature right and it worked. Maybe someone with higher skill could fix this properly.

**Comment by tknopp** [comment]
see #393
