### ISSUE TITLE
Support SWMR for HDF5 v1.10 

### ISSUE THREAD

**Issue by oschulz** [JuliaIO/HDF5.jl#392]
HDF5 offers a new single-writer / multiple-reader (SWMR) feature:

* https://support.hdfgroup.org/HDF5/docNewFeatures/NewFeaturesSwmrDocs.html
* https://support.hdfgroup.org/HDF5/Tutor/swmr.html

Besides the fact that it allows for use cases like reading (and analysing) data during data aquisition, the SWMR mode is also interesting because it increases robustness (file recovery after crashes).

It would be great if HDF5.jl would support SWMR (when HDF5 v1.10 is installed).

**Comment by ggggggggg** [comment]
You may not have noticed if you didn't check this issue, I have a PR outstanding that would enable SWMR. You could take a look at it make comments if you wanted.

**Comment by oschulz** [comment]
@ggggggggg: Nice - I look forward to this!

**Comment by oschulz** [comment]
Just until #394 is merged.
