### ISSUE TITLE
Reading compound dataset with string contents errors

### ISSUE THREAD

**Issue by pfitzseb** [JuliaIO/HDF5.jl#393]
[This line](https://github.com/JuliaIO/HDF5.jl/blob/d2f8538d5d0efea992b6277830116faa91d093be/src/HDF5.jl#L1350) errors when trying to read a compound dataset with string contents. Specifically, `unpad` is defined to take a `String` and a `Cint` as inputs, while `read(io, UInt8, dsize)` is an Array of `UInt8`s and `H5T_STR_NULLPAD` is a `Int64` on my machine, while `Cint` is an alias for `Int32`.

Wrapping the `read` in a `String` constructor and relaxing `unpad`s second argument's type restriction should work imho, but with my sample dataset I'm then getting a `UnicodeError: invalid character index`. I'm not sure if that's specific to my dataset's layout though (the `Vector{UInt8}` `read` spits out doesn't seem to be related to the string I'm expecting there at all, which might be a deeper issue).

I'd be happy to investigate this more, but I think I'll need some guidance from someone more familiar with the codebase...

cc @grahamrow, because you implemented `read_row` in https://github.com/JuliaIO/HDF5.jl/pull/365

**Comment by musm** [comment]
@grahamrow could you please take a look at this? thanks

**Comment by pfitzseb** [comment]
Small file that reproduces this issue:
[compound_dataset.zip](https://github.com/JuliaIO/HDF5.jl/files/1487187/compound_dataset.zip)

**Comment by musm** [comment]
Hmm, so is it not correctly identifying the membertype? 
It fails for this 'string'
 `UInt8[0x60, 0xa2, 0x01, 0x00, 0xe8, 0x03, 0x00, 0x00]`
what are you expected there?

**Comment by kleinhenz** [comment]
This should be closed by #592.
