### ISSUE TITLE
Dealing with arrays of Booleans

### ISSUE THREAD

**Issue by dourouc05** [JuliaIO/HDF5.jl#403]
Currently, this package outputs horrible errors when trying to write an array of Booleans (`Array{Bool,1}`, for example): 

```
ERROR: LoadError: MethodError: `write` has no method matching write(::HDF5.HDF5File, ::ASCIIString, ::Array{Bool,1})
Closest candidates are:
  write(::Union{HDF5.HDF5File,HDF5.HDF5Group}, ::Union{ASCIIString,UTF8String}, ::Any, ::Union{ASCIIString,UTF8String}, ::Any, ::Any...)
  write{T<:Base.AbstractPipe}(::T<:Base.AbstractPipe, ::Any...)
  write(::IO, ::Any...)
  ...
 in h5write at C:\Users\Thibaut\.julia\v0.4\HDF5\src\plain.jl:626
```

(Julia 0.4.6, Windows 10 x64.)

I think a simple work around would be to provide the right `write` definition, which would just cast the Booleans to 8-bit integers (exactly like h5py does). I tried something like this, but it did not work (I can't get this method to be called, I always get the same errors as before): 

```
write(parent::Union{HDF5File, HDF5Group, HDF5Dataset}, name::String, data::Union{Bool, Array{Bool}}) = write(parent, name, round(Int8, data))
```

Or the best way to deal with this issue would be to revive #307?

**Comment by ggggggggg** [comment]
What you're trying should work, see below
```julia
julia> using HDF5

julia> a = [true,false]
2-element Array{Bool,1}:
  true
 false

julia> h5 = h5open(tempname(),"w")
HDF5 data file: /var/folders/_0/25kp6h7x25v6vyjv2yjlcnkm000wrm/T/juliajnaM0V

julia> h5["a"]=a
ERROR: MethodError: no method matching write(::HDF5.HDF5File, ::String, ::Array{Bool,1})
Closest candidates are:
  write(::Union{HDF5.HDF5File,HDF5.HDF5Group}, ::String, ::Any, ::String, ::Any, ::Any...) at /Users/oneilg/.julia/v0.5/HDF5/src/HDF5.jl:1565
  write(::AbstractString, ::Any...) at io.jl:107
  write(::IO, ::Any...) at io.jl:148
  ...
 in setindex!(::HDF5.HDF5File, ::Array{Bool,1}, ::String) at /Users/oneilg/.julia/v0.5/HDF5/src/HDF5.jl:908

julia> h5["a"]=convert(Vector{UInt8},a)
2-element Array{UInt8,1}:
 0x01
 0x00

julia> import Base: write

julia> write(parent::Union{HDF5File, HDF5Group, HDF5Dataset}, name::String, data::Union{Bool, Array{Bool}}) = write(parent, name, round(Int8, data))
write (generic function with 42 methods)

julia> write(h5,"a2",a)

julia> read(h5["a2"])
2-element Array{Int8,1}:
 1
 0
```

I think you need `import Base: write` before your method addition. I don't know where this is in the documentation, but what you were doing created a new function called `write` and replaced the existing `write` function, so you couldn't call the function you wanted on the right hand side. You should also upgrade from v0.4 soon. This package has stopped testing on v0.4. 

Please close the issue if this resolves your issue. It would still be a good idea to fix #307 but hopefully this lets you make progress.

**Comment by dourouc05** [comment]
Thank you for your answer! 

I was thinking of this rather as a potential contribution to the package, in order to make it easier to use for others (especially as this implementation is consistent with what other packages do). 

(And I know staying on Julia 0.4 makes I'm not getting the latest version of all packages, but that can be seen as an advantage when you do not want to keep rewriting your code. I am currently planning a migration to Julia 0.6, mostly due to https://github.com/JuliaLang/julia/issues/18725.)

**Comment by ggggggggg** [comment]
I think the package is designed so that you can write, then read, and get back the same thing you put in. I think it is probably worth maintaining consistency over making this easier. The JLD package might be worth considering. Writing and reading Arrays of Bools works out of the box:
```julia
julia> j5 = jldopen(tempname(),"w")
Julia data file version 0.1.1: /var/folders/_0/25kp6h7x25v6vyjv2yjlcnkm000wrm/T/juliaCm0lsb

julia> j5["a"] = [true,false]
2-element Array{Bool,1}:
  true
 false

julia> read(j5["a"])
2-element Array{Bool,1}:
  true
 false
```

**Comment by dourouc05** [comment]
This reasoning makes sense to me. However, I think it would be best to give a specific error message to the user in this case, something like "Writing binary values and arrays is not supported because HDF5 does not define the Boolean type"? I think the implementation would be straightforward: 

`write(parent::Union{HDF5File, HDF5Group, HDF5Dataset}, name::String, data::Union{Bool, Array{Bool}}) = error("Writing binary values and arrays is not supported because HDF5 does not define the Boolean type")`

(The issue I have with JLD are that I need compatibility with other software — which is why I first chose HDF5: I am unable to read JLD files from Mathematica, for one.)

**Comment by ggggggggg** [comment]
That seems like a good idea. What do you think about something like `error("Writing Bool and Array{Bool} are not supported by the HDF5 library. Consider converting to UInt8, or using the JLD package which supports all Julia types.")`

**Comment by dourouc05** [comment]
I would add a hint on how to make the conversion (especially for users discovering Julia, they will be afraid of such an error message), so maybe something like this? 

```"Writing Bool and Array{Bool} are not supported by the HDF5 library. Consider converting to UInt8 (instead of writing `data` as argument, use `round(Int8, data)`), or using the JLD package which supports all Julia types."```

(Or would you recommend another function than `round`?)

**Comment by ggggggggg** [comment]
`"Writing Bool and Array{Bool} are not supported by the HDF5 library. Consider converting to UInt8 (instead of writing `data` as argument, use `convert(UInt, data)`), or using the JLD package which supports all Julia types."`

**Comment by dourouc05** [comment]
Looks good to me!

**Comment by musm** [comment]
This is fixed 
```
using HDF5
a = [true,false,true,false]
h5 = h5open(tempname(),"w")
h5["a"]=a

julia> read(h5["a"])
4-element Vector{Bool}:
 1
 0
 1
 0
