### ISSUE TITLE
How to read all attributes

### ISSUE THREAD

**Issue by Clemens-H** [JuliaIO/HDF5.jl#414]
Hi!  Is it possible to read all attributes associated with an object and, if so, how?

Anyway, thanks for all the work on HDF5.jl.

**Comment by ggggggggg** [comment]
I'm not sure what you mean. `collect(read(attrs(o)[n]) for n in names(attrs(o)))` should give you all the values, is that what you want? (warning, I can't promise I matched all parens since I didn't test this)

**Comment by Clemens-H** [comment]
Thanks, that works.  (For some reason I didn't find it in the documentation.)
