### ISSUE TITLE
Fix for unpad

### ISSUE THREAD

**Issue by Clemens-H** [JuliaIO/HDF5.jl#415]
Hi!  I want to read a compound data set, which currently fails with `MethodError`s such as

`MethodError(HDF5.unpad, (UInt8[0x43, 0x43, 0x41, 0x54, 0x47, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], 1), 0x000000000000554e)`

The currently defined `unpad` method is too restrictive (in both of its arguments).

`function unpad(s::String, pad::Cint)`

This general catch-all-cases method makes it possible to read my file:

```
function HDF5.unpad(s, pad)
    HDF5.unpad(String(s), Cint(pad))
end
```

**Comment by musm** [comment]
PR #416  should fix this. Thanks.

**Comment by Clemens-H** [comment]
Thanks.
