### ISSUE TITLE
Incorrect hdf5 install with homebrew.

### ISSUE THREAD

**Issue by rofinn** [JuliaIO/HDF5.jl#429]
Looks like I'm `v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/hdf5.rb` doesn't existing in homebrew anymore and the only valid file is `v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/hdf5@1.8.rb`. There's also a warning stating `Use hdf5 instead of deprecated homebrew/science/hdf5`, so maybe we should just switch to that?

[Failing travis build](https://travis-ci.org/JuliaIO/HDF5.jl/jobs/254590267)

**Comment by ssfrr** [comment]
Just hit this trying to install HDF5 (as a dependency of BenchmarkTools), causing an error in `Pkg.build` (Included here for googlability):

```
LoadError: SystemError: opening file /Users/srussell/.julia/v0.6/Homebrew/deps/usr/Library/Taps/homebrew/homebrew-science/hdf5.rb: No such file or directory
while loading /Users/srussell/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 27
```

As a workaround I just copied the fix from #430.
