### ISSUE TITLE
h5write fails for new file in Julia 0.6

### ISSUE THREAD

**Issue by emcangi** [JuliaIO/HDF5.jl#440]
Attempting to run some code of ours that (in Julia 0.4.7) was able to successfully open a new HDF5 file and write to it using h5write. Now in Julia 0.6 it fails.

Julia version: 0.6
HDF5 version: 0.8.4
JLD version: 0.8.1

Example code:

```
julia> test = zeros(Float64, 2, 2)
2×2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0

julia> h5write("testfile.h5", "testsection", test)
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140264843021376:
  #000: ../../../src/H5F.c line 439 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 554 in H5F_is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'testfile.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
ERROR: Cannot access file testfile.h5
Stacktrace:
 [1] h5f_is_hdf5(::String) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:2179
 [2] #h5open#3(::Bool, ::Function, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::HDF5.HDF5Properties, ::HDF5.HDF5Properties) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:592
 [3] (::HDF5.#kw##h5open)(::Array{Any,1}, ::HDF5.#h5open, ::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::HDF5.HDF5Properties, ::HDF5.HDF5Properties) at ./<missing>:0
 [4] #h5open#4(::Bool, ::Function, ::String, ::String) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:643
 [5] h5write(::String, ::String, ::Array{Float64,2}) at /home/emc/.julia/v0.6/HDF5/src/HDF5.jl:682
```
Seems to be because h5write calls h5open using the "r+" mode. Changing the mode to "w" and just running the commands by hand at least gets it open:

```
julia> fid = h5open("testfile.h5", "w")
HDF5 data file: testfile.h5

julia> write(fid, "testsection", test)

julia> close(fid)
```
However, I've run into some other problems with our code that aren't solved as simply, even if I can manage to get the files open.

Thanks!

**Comment by una-dinosauria** [comment]
Does 
```julia
Pkg.test("HDF5")
```
work for you?

**Comment by emcangi** [comment]
Yes, all tests passed. 

Other tips welcome. I'm new to Julia (used to Python) so it is possible I have just missed something!

**Comment by una-dinosauria** [comment]
Weird. The test suite should catch that: https://github.com/JuliaIO/HDF5.jl/blob/e4052c95f9ede4bb2c56ca4e79f78b41c06a9de7/test/plain.jl#L112

I don't know how to fix it, but I get the exact same error on two machines. One machine has 
```
Julia 0.5.2
HDF5 1.8.14
```
And 
```
Julia 0.6
HDF5 1.8.16
```

Tests pass for me as well.

**Comment by una-dinosauria** [comment]
> Weird. The test suite should catch that:

I take that back! There doesn't seem to be a test for `h5write` with a string as a first argument, only with an `fid` as you mentioned on your first post.

**Comment by emcangi** [comment]
Are you saying the test suite should catch that I changed the base HDF5 code? I actually didn't do that--I just went into HDF5.jl, looked up the shortest h5write function, and then took the code out of it and put that into my code and used it that way.

I'm probably not following due to being new + it late in the day where I am. Ha.

**Comment by una-dinosauria** [comment]
So the problem is that, in the test cases, only the case when the file already exists was covered. I've added new tests and reverted the code changed that broke it. They should merge it in a day or so.

**Comment by emcangi** [comment]
Thanks! Will keep an eye on it.
