### ISSUE TITLE
HDF5 build failure on Travis CI (Linux)

### ISSUE THREAD

**Issue by pearlzli** [JuliaIO/HDF5.jl#446]
I'm getting the following error while trying to build HDF5 on Linux in Travis:

```julia
================================[ ERROR: HDF5 ]=================================
LoadError: failed process: Process(`sudo apt-get install hdf5-tools`, ProcessExited(1)) [1]
while loading /home/travis/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 40
```

Log here: https://travis-ci.org/FRBNY-DSGE/StateSpaceRoutines.jl/jobs/287085050

Thanks for your help!

**Comment by wkearn** [comment]
This happens because sudo is used to install hdf5-tools, but it is disabled for the trusty version of Linux on Travis. See travis-ci/travis-ci#8129.

The fix is to add

`sudo: required` 

to your .travis.yml

**Comment by pearlzli** [comment]
Worked for me - thanks!

**Comment by pearlzli** [comment]
Sorry to come back to this issue, but I'm having this problem again on Travis, except on OS X:

```
================================[ ERROR: HDF5 ]=================================

LoadError: failed process: Process(`/Users/travis/.julia/v0.6/Homebrew/deps/usr/bin/brew install --ignore-dependencies staticfloat/juliatranslated/gcc`, ProcessExited(1)) [1]
while loading /Users/travis/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 41
```

Log: https://travis-ci.org/FRBNY-DSGE/StateSpaceRoutines.jl/jobs/380395718/config

Does anyone know what the problem might be?
