### ISSUE TITLE
Bug: 3D array is treated as 1D array

### ISSUE THREAD

**Issue by Tagussan** [JuliaIO/HDF5.jl#449]
Hi.
I have an mat file, which includes 3d-array of complex value.
However, h5read returns the 3d-array as 1d-array. This is the screenshot: 
<img width="441" alt="capture1" src="https://user-images.githubusercontent.com/3764516/32723411-b65fd5f2-c8b0-11e7-80e0-5efb893f3ad6.PNG">

On the other hand, MAT package gives correct 3d array.
<img width="466" alt="capture2" src="https://user-images.githubusercontent.com/3764516/32723451-dafd958e-c8b0-11e7-9e7b-ffaa2b991779.PNG">

Thanks.

**Comment by ggggggggg** [comment]
`HDF5.jl` is correctly reading the file, it's just that MATLAB doesn't use HDF5 to store the array dimensions in the standard way, instead hiding the dimension in the "Dimension Array Subelement". Use the `MAT.jl` package if you don't want to deal with that yourself. See Table 1-2 [here](https://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf). Please close the issue if you are satisfied.

**Comment by Tagussan** [comment]
I will use HDF5.jl. Thank you :)
