### ISSUE TITLE
bug with permuteddimsview, but not permutedims

### ISSUE THREAD

**Issue by bjarthur** [JuliaIO/HDF5.jl#466]
here's what should be added to the tests:

```
using Base.Test, Images, HDF5
data = rand(UInt16,2,3);

pdv_data = permuteddimsview(data,(2,1));
h5write("temp.h5", "/pdv_data", pdv_data)
pdv_data_readback = h5read("temp.h5", "/pdv_data");
@test pdv_data==pdv_data_readback               ### currently evaluates to FALSE :(

pd_data = permutedims(data,(2,1));
h5write("temp.h5", "/pd_data", pd_data)
pd_data_readback = h5read("temp.h5", "/pd_data");
@test pd_data==pd_data_readback    ### works!

@test pdv_data==pd_data    ### evaluates as true, so it's not Images fault
```

**Comment by bjarthur** [comment]
this error is a direct consequence of changing `Array` to `AbstractArray` in https://github.com/JuliaIO/HDF5.jl/pull/463.  supporting the myriad types of AbstactArrays might be more trouble than it's worth.  we could consider reverting back.

**Comment by musm** [comment]
Good catch... Yeah seems like we should be safe and revert the generic dispatch to AbstractArray.  Perhaps we could add an alias to supported Array types that are defined in base (e.g.  `Union{Array,SharedArray,...}`)

**Comment by bjarthur** [comment]
`collect(A::AbstractArray)` yields an `Array` in all cases i've tested so far.  so we could just define a method which does that conversion and then proceed as normal.  will work on a PR.

**Comment by bjarthur** [comment]
closed by https://github.com/JuliaIO/HDF5.jl/pull/469
