### ISSUE TITLE
H5F_LIBVER_ LATEST is hardcoded, but the value changed

### ISSUE THREAD

**Issue by ggggggggg** [JuliaIO/HDF5.jl#474]
The value of `H5F_LIBVER_LATEST` appears to have changed. Currently the values are hard coded, but it seems better to read them from the HDF5 library. Can anybody tell me how to do this, and I'd be happy to submit a PR. There are lots of examples of reading constants with the `HDF5.read_constant` function, but I don't understand it enough to adapt it to this case.

```c++
/* Library's format versions */
typedef enum H5F_libver_t {
    H5F_LIBVER_ERROR = -1,
    H5F_LIBVER_EARLIEST = 0,    /* Use the earliest possible format for storing objects */
    H5F_LIBVER_V18 = 1,         /* Use the latest v18 format for storing objects */
    H5F_LIBVER_V110 = 2,        /* Use the latest v10 format for storing objects */
    H5F_LIBVER_NBOUNDS
} H5F_libver_t;

#define H5F_LIBVER_LATEST   H5F_LIBVER_V110
```

This causes the SWMR tests to fail on my machine. I'm not sure why they aren't failing on travis on OSX, maybe it's installing a different version of the HDF5 library? I have `1.10.2`

**Comment by musm** [comment]
Have you seen https://www.hdfgroup.org/2018/04/why-should-i-care-about-the-hdf5-1-10-2-release/

**Comment by ggggggggg** [comment]
I guess instead of reading the value from the library, I could check the library version before defining the constants. But it seems better to read it from the library if we can.

**Comment by musm** [comment]
Agreed, is the constant available in the non-cpp api? I tried some things here and there but couldn't get it to load

**Comment by ggggggggg** [comment]
How do you tell if its in the cpp or non-cpp api?
