### ISSUE TITLE
Issue with using HDF5 and Pkg.Build("HDF5")

### ISSUE THREAD

**Issue by vd2309** [JuliaIO/HDF5.jl#483]
Hello!

I have this code to run:

```julia
**using HDF5
filename = "/Untitled/Users/philip/Desktop/test.h5"
img_A = h5read(filename, "img_A")
img_B = h5read(filename, "img_B")
ans_p_1step_prevfrm = h5read(filename, "ans_p_1step_prevfrm")
ans_p_1step = h5read(filename, "ans_p_1step")
ans_p_2step = h5read(filename, "ans_p_2step")
stack = h5read(filename, "refernece")
stack_hi = h5read(filename, "refernece_highpass");
img_phase = h5read(filename, "img_phase");
img_width, img_height = size(img_A)
zStkCnt = size(stack,3);**


when I run it it says:
**INFO: Precompiling module HDF5.
ERROR: LoadError: HDF5 not properly installed. Please run Pkg.build("HDF5")
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/philip/.julia/v0.6/HDF5/src/HDF5.jl, in expression starting on line 38
ERROR: Failed to precompile HDF5 to /Users/philip/.julia/lib/v0.6/HDF5.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405**


...so i include Pkg.build("HDF5") in the code I get this error:



**INFO: Building Homebrew
Already up-to-date.
INFO: Building CMakeWrapper
INFO: Building Blosc
INFO: Building HDF5
==> Installing gcc from staticfloat/juliatranslated
Error: The following formula:
  gcc
cannot be installed as a binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install

================================[ ERROR: HDF5 ]=================================

LoadError: failed process: Process(`/Users/philip/.julia/v0.6/Homebrew/deps/usr/bin/brew install --ignore-dependencies staticfloat/juliatranslated/gcc`, ProcessExited(1)) [1]
while loading /Users/philip/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 41

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: HDF5 had build errors.

 - packages with build errors remain installed in /Users/philip/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HDF5")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Precompiling module HDF5.
ERROR: LoadError: HDF5 not properly installed. Please run Pkg.build("HDF5")
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/philip/.julia/v0.6/HDF5/src/HDF5.jl, in expression starting on line 38
Failed to precompile HDF5 to /Users/philip/.julia/lib/v0.6/HDF5.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405**
```

please help!
-Ginny

**Comment by iamed2** [comment]
```
Error: The following formula:
gcc
cannot be installed as a binary package and must be built from source.
Install the Command Line Tools:
xcode-select --install
```

Have you done so?

**Comment by mbauman** [comment]
This is indeed frustrating — Homebrew is refusing to download the compiled binary dependency (gcc), so instead it is trying to build it from scratch.  It refers to this as "pouring a bottle."  We've reported this upstream at https://github.com/Homebrew/homebrew-core/issues/27751, but it appears the attempted fix doesn't fully fix it.

So, yes, one workaround here is to install the command line tools like Eric suggests with `xcode-select --install`, which will then build gcc from source.  Unfortunately, GCC is a _very large_ source project which will take several hours to build.  It may appear as though it hung completely… but it's doing its thing!

**Comment by mbauman** [comment]
Can you run `/Users/philip/.julia/v0.6/Homebrew/deps/usr/bin/brew doctor` in the terminal and report back with its output?

**Comment by vd2309** [comment]
Hi, mbauman!

Yes:


i get this


Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/philip/anaconda3/bin/icu-config
  /Users/philip/anaconda3/bin/freetype-config
  /Users/philip/anaconda3/bin/xslt-config
  /Users/philip/anaconda3/bin/libpng16-config
  /Users/philip/anaconda3/bin/python3.6m-config
  /Users/philip/anaconda3/bin/libpng-config
  /Users/philip/anaconda3/bin/xml2-config
  /Users/philip/anaconda3/bin/python3-config
  /Users/philip/anaconda3/bin/curl-config
  /Users/philip/anaconda3/bin/ncursesw6-config
  /Users/philip/anaconda3/bin/pcre-config
  /Users/philip/anaconda3/bin/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  pkg-config

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: /usr/bin occurs before /Users/philip/.julia/v0.6/Homebrew/deps/usr/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  libtool
  strings
  git-receive-pack
  strip
  ctf_insert
  pagestuff
  git-upload-archive
  segedit
  redo_prebinding
  otool
  codesign_allocate
  nm
  ar
  lipo
  as
  git-cvsserver
  git-shell
  size
  git-upload-pack
  ranlib
  nmedit
  git
  install_name_tool
  cmpdylib

Consider setting your PATH so that /Users/philip/.julia/v0.6/Homebrew/deps/usr/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/Users/philip/.julia/v0.6/Homebrew/deps/usr/bin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
  echo 'export PATH="/Users/philip/.julia/v0.6/Homebrew/deps/usr/bin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (1) is too outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (1) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Some keg-only formulae are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  cctools
dyn-209-2-228-133:~ CristianBoboila$

**Comment by vd2309** [comment]
Hello mbauman!

I deleted the files that the brew doctor told me to, just the ones that I could delete. I was not able to delete the other files. Now when I run brew doctor I get this:


Warning: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.


Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libtcl8.6.dylib
  /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/fakemysql.h
  /usr/local/include/fakepq.h
  /usr/local/include/fakesql.h
  /usr/local/include/itcl.h
  /usr/local/include/itcl2TclOO.h
  /usr/local/include/itclDecls.h
  /usr/local/include/itclInt.h
  /usr/local/include/itclIntDecls.h
  /usr/local/include/itclMigrate2TclCore.h
  /usr/local/include/itclTclIntStubsFcn.h
  /usr/local/include/mysqlStubs.h
  /usr/local/include/odbcStubs.h
  /usr/local/include/pqStubs.h
  /usr/local/include/tcl.h
  /usr/local/include/tclDecls.h
  /usr/local/include/tclOO.h
  /usr/local/include/tclOODecls.h
  /usr/local/include/tclPlatDecls.h
  /usr/local/include/tclThread.h
  /usr/local/include/tclTomMath.h
  /usr/local/include/tclTomMathDecls.h
  /usr/local/include/tdbc.h
  /usr/local/include/tdbcDecls.h
  /usr/local/include/tdbcInt.h
  /usr/local/include/tk.h
  /usr/local/include/tkDecls.h
  /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
  /usr/local/lib/pkgconfig/tcl.pc
  /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libtclstub8.6.a
  /usr/local/lib/libtkstub8.6.a

Warning: Your Homebrew's prefix is not /usr/local.
You can install Homebrew anywhere you want but some bottles (binary packages)
can only be used with a /usr/local prefix and some formulae (packages)
may not build correctly with a non-/usr/local prefix.

Warning: Your Xcode (1) is too outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Your Xcode (1) is outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.


Warning: Some keg-only formulae are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
  cctools


My code and errors are still this:

**Pkg.build("HDF5")
println("hi")
using HDF5
println("hi1")
filename = "/Untitled/Users/philip/Desktop/test.h5"
println("hi2")
img_A = h5read(filename, "img_A")
img_B = h5read(filename, "img_B")
ans_p_1step_prevfrm = h5read(filename, "ans_p_1step_prevfrm")
ans_p_1step = h5read(filename, "ans_p_1step")
ans_p_2step = h5read(filename, "ans_p_2step")
stack = h5read(filename, "refernece")
stack_hi = h5read(filename, "refernece_highpass");
img_phase = h5read(filename, "img_phase");
img_width, img_height = size(img_A)
zStkCnt = size(stack,3);**


ERRORS ARE....below

Already up-to-date.
hi
ERROR (unhandled task failure): InterruptException:
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:216
 [3] wait(::Condition) at ./event.jl:27
 [4] stream_wait(::Timer, ::Condition, ::Vararg{Condition,N} where N) at ./stream.jl:42
 [5] wait(::Timer) at ./event.jl:357
 [6] (::Base.##302#303{IJulia.#send_stderr,Timer})() at ./event.jl:430
INFO: Building Homebrew
INFO: Building CMakeWrapper
INFO: Building Blosc
INFO: Building HDF5
Error: Your Xcode (1) is too outdated.
Please update to Xcode 9.2 (or delete it).
Xcode can be updated from the App Store.

Error: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

================================[ ERROR: HDF5 ]=================================

LoadError: failed process: Process(`/Users/philip/.julia/v0.6/Homebrew/deps/usr/bin/brew install --ignore-dependencies staticfloat/juliatranslated/gcc`, ProcessExited(1)) [1]
while loading /Users/philip/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 41

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: HDF5 had build errors.

 - packages with build errors remain installed in /Users/philip/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HDF5")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Precompiling module HDF5.
ERROR: LoadError: HDF5 not properly installed. Please run Pkg.build("HDF5")
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/philip/.julia/v0.6/HDF5/src/HDF5.jl, in expression starting on line 38
Failed to precompile HDF5 to /Users/philip/.julia/lib/v0.6/HDF5.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405

Thank you so much for your help! I also wonder if this is a homebrew problem? Again, am not sure why I am getting the error message that my Xcode and command line tools are out of date because I have Xcode 10, and the command line tools are for Xcode 10. 

Thanks again!
Ginny

**Comment by vd2309** [comment]
Hi mbauman!

It returns
/Applications/Xcode-beta.app/Contents/Developer

before it was returning something like /../.../CommandLineTools, so I googled how to change this and found a method where you just go into Xcode, go into preferences, into location, and change the option for command line tools. 

Please let me know what is going on!!
Thank you!

Ginny

**Comment by mbauman** [comment]
I'm afraid I'm just shooting in the dark here, too.

Does it work now that it has changed?  How many versions of Xcode do you have in Applications?  Which one is more recent?

**Comment by vd2309** [comment]
Morning, Matt!

No it still does not work. I am going to do these things:
check for other xcode apps on my computer and run it. 
if i cannot find any, i will uninstall everything, reinstall, and then see if it works. 
I will let you know what happens after I do these things. 

Thank you so much and I will keep you posted!
Ginny

**Comment by vd2309** [comment]
Hi, Matt

Actually downloaded JUNO and have gotten past the HDF5 hurdle. Looks like things seem to be working...for now :)

Thanks so much for your help - may reach out with other questions later. 

Thanks!
Ginny

**Comment by mbauman** [comment]
You need to be in shell mode to run `xcode-select`. Press `;` at the REPL to bring up the shell prompt:

```
shell> xcode-select -p
/Applications/Xcode.app/Contents/Developer
```

Sorry you went down this deep rabbit hole — and glad you found a workaround.

**Comment by vd2309** [comment]
Thanks, Matt!
Just a small question: can you please explain something to me? What is the "mygroup2/A" pointing to?

I see this in the main page of the github

A = collect(reshape(1:120, 15, 8))
h5write("/tmp/test2.h5", "mygroup2/A", A)
data = h5read("/tmp/test2.h5", "mygroup2/A", (2:3:15, 3:5))

I understand the data is stored in A, and that we are writing the data stored in A to the file called, "/tmp/test2.h5", but what is the "mygroup2/A" pointing to? It is also there in the h5read function. 

Thanks!
Ginny

**Comment by mbauman** [comment]
That's a better question for the [discourse message board](https://discourse.julialang.org) — could you post it there? If someone else doesn't beat me to it I'll happily answer it there.

**Comment by vd2309** [comment]
Thanks Matt, will do and follow up if no response!
Ginny

**Comment by NicLoi** [comment]
Hi guys, 
I have the same issue. Did you resolve the problem?
My code was fine a week ago but now after I did an update of the packages it doesn't work. 
In particular I want to use the JLD package but the following message appears after I run the "using JLD":

INFO: Precompiling module JLD.
ERROR: LoadError: HDF5 not properly installed. Please run Pkg.build("HDF5")
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/nicolas/.julia/v0.6/HDF5/src/HDF5.jl, in expression starting on line 38
ERROR: LoadError: Failed to precompile HDF5 to /Users/nicolasloizou/.julia/lib/v0.6/HDF5.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /Users/nicolas/.julia/v0.6/JLD/src/JLD.jl, in expression starting on line 4

I run "Pkg.build("HDF5")" and I have to code running for a long time after I Interrupt it. I get the following: 

INFO: Building Homebrew
INFO: Building CMakeWrapper
INFO: Building Blosc
INFO: Building HDF5
Error: Failed changing install name in /Users/nicolas/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib
  from @@HOMEBREW_CELLAR@@/gcc/8.1.0/lib/gcc/8/i386/libstdc++.6.dylib
    to /Users/nicolas/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libstdc++.6.dylib
Error: Updated load commands do not fit in the header of /Users/nicolas/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib. /Users/nicolas/.julia/v0.6/Homebrew/deps/usr/Cellar/gcc/8.1.0/lib/gcc/8/i386/libubsan.1.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names
Warning: Bottle installation failed: building from source.
================================[ ERROR: HDF5 ]=================================

LoadError: InterruptException:
while loading /Users/nicolas/.julia/v0.6/HDF5/deps/build.jl, in expression starting on line 41

================================================================================
ERROR (unhandled task failure): InterruptException:
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:216
 [3] wait(::Condition) at ./event.jl:27
 [4] stream_wait(::Timer, ::Condition, ::Vararg{Condition,N} where N) at ./stream.jl:42
 [5] wait(::Timer) at ./event.jl:357
 [6] (::Base.##300#301{IJulia.#send_stderr,Timer})() at ./event.jl:430

================================[ BUILD ERRORS ]================================

WARNING: HDF5 had build errors.

 - packages with build errors remain installed in /Users/nicolasloizou/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("HDF5")`
 - build a single package by running its `deps/build.jl` script

Any suggestion of how to resolve this? I also run Pkg.build("Homebrew") and everything seems to be fine with that.
I work on MacOS 10.11.6.

**Comment by stillyslalom** [comment]
Ugly workaround that "fixes" this by pinning gcc to 0.7.3 (which has a pourable bottle):

```
using Homebrew, HDF5

raw = "https://raw.githubusercontent.com/Homebrew/homebrew-core/858282eb2f1381e027e3db225da11fd2dbb13c4d/Formula/gcc.rb"
Homebrew.brew(`install --force-bottle $raw`)
Homebrew.brew(`switch gcc 7.3.0`)
Homebrew.brew(`pin gcc`)

Homebrew.update()
Pkg.build("HDF5")
```

**Comment by nickeubank** [comment]
Thanks @stillyslalom !

**Comment by nickeubank** [comment]
Seems like the Homebrew people think they've fixed it on their end (see [here](https://github.com/Homebrew/homebrew-core/issues/27751)). Did they close prematurely, or is the problem now somewhere else?

**Comment by nickeubank** [comment]
See discussion with an alternate work around [here](https://discourse.julialang.org/t/anyone-know-status-of-hdf5-build-problems/12575/3). 

More generally, though, this still seems like a big general problem for new users – being able to read data and save things seems pretty central to Julia. Surely we can make this install work better?

(Sorry – I know it’s bad form to push for a fix to something open source if you aren’t in a position to do it oneself, but in this case I know NOTHING about gcc or homebrew, so am really not in a position to offer PRs. :frowning: )

**Comment by zhangfuhan** [comment]
just do this 
 in expression starting at /home/zfh/.julia/packages/HDF5/b6QoH/deps/build.jl:39
│ Installing dependency hdf5-tools via `sudo apt-get install hdf5-tools`:

and then build HDF5 in julia is ok

**Comment by musm** [comment]
should be fixed by the latest version when it goes through #555
