### ISSUE TITLE
Build Error on 0.7

### ISSUE THREAD

**Issue by gideonsimpson** [JuliaIO/HDF5.jl#496]
```(v0.7) pkg> build HDF5
┌ Warning: Dependency graph not a DAG, linearizing anyway
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:985
  Building LibCURL ─────→ `~/.julia/packages/LibCURL/yT2TD/deps/build.log`
  Building WinRPM ──────→ `~/.julia/packages/WinRPM/rDDZz/deps/build.log`
  Building Homebrew ────→ `~/.julia/packages/Homebrew/l8kUw/deps/build.log`
  Building CMakeWrapper → `~/.julia/packages/CMakeWrapper/R7ZgO/deps/build.log`
  Building Blosc ───────→ `~/.julia/packages/Blosc/jsnGf/deps/build.log`
  Building HDF5 ────────→ `~/.julia/packages/HDF5/PegIy/deps/build.log`
┌ Error: Error building `HDF5`: 
│ ==> Installing gmp from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.high_sierra.bottle.tar.gz
│ Already downloaded: /Users/guardian/Library/Caches/Homebrew.jl/gmp-6.1.2_2.high_sierra.bottle.tar.gz
│ ==> Pouring gmp-6.1.2_2.high_sierra.bottle.tar.gz
│ Warning: The post-install step did not complete successfully
│ You can try again using `brew postinstall staticfloat/juliatranslated/gmp`
│ ==> Summary
│ 🍺  /Users/guardian/.julia/packages/Homebrew/l8kUw/deps/usr/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
│ ERROR: LoadError: failed process: Process(`/Users/guardian/.julia/packages/Homebrew/l8kUw/deps/usr/bin/brew install --ignore-dependencies staticfloat/juliatranslated/gmp`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:712 [inlined]
│  [3] #run#509(::Bool, ::Function, ::Cmd) at ./process.jl:670
│  [4] run at ./process.jl:668 [inlined]
│  [5] #brew#4(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Function, ::Cmd) at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/API.jl:19
│  [6] #brew at ./none:0 [inlined]
│  [7] #install_and_link#38(::Bool, ::Function, ::String) at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/API.jl:492
│  [8] (::getfield(Homebrew, Symbol("#kw##install_and_link")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(Homebrew.install_and_link), ::String) at ./none:0
│  [9] macro expansion at ./logging.jl:310 [inlined]
│  [10] #add#29(::Bool, ::Bool, ::Function, ::String) at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/API.jl:449
│  [11] add at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/API.jl:412 [inlined]
│  [12] install(::Array{String,1}) at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/bindeps_integration.jl:50
│  [13] (::getfield(Homebrew, Symbol("##80#81")))() at /Users/guardian/.julia/packages/Homebrew/l8kUw/src/bindeps_integration.jl:45
│  [14] run(::getfield(Homebrew, Symbol("##80#81"))) at /Users/guardian/.julia/packages/BinDeps/Z6fwm/src/BinDeps.jl:483
│  [15] macro expansion at ./logging.jl:308 [inlined]
│  [16] run(::BinDeps.SynchronousStepCollection) at /Users/guardian/.julia/packages/BinDeps/Z6fwm/src/BinDeps.jl:523
│  [17] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /Users/guardian/.julia/packages/BinDeps/Z6fwm/src/dependencies.jl:944
│  [18] satisfy!(::BinDeps.LibraryDependency) at /Users/guardian/.julia/packages/BinDeps/Z6fwm/src/dependencies.jl:922
│  [19] top-level scope at /Users/guardian/.julia/packages/BinDeps/Z6fwm/src/dependencies.jl:977
│  [20] include at ./boot.jl:317 [inlined]
│  [21] include_relative(::Module, ::String) at ./loading.jl:1038
│  [22] include(::Module, ::String) at ./sysimg.jl:29
│  [23] include(::String) at ./client.jl:398
│  [24] top-level scope at none:0
│ in expression starting at /Users/guardian/.julia/packages/HDF5/PegIy/deps/build.jl:41
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1068

```

**Comment by tpapp** [comment]
Looks like a download error, perhaps try the suggested solution, which may be
```sh
brew postinstall staticfloat/juliatranslated/gmp
```
if I am decoding the above correctly.

**Comment by gideonsimpson** [comment]
Where/how do I execute they brew command?  This is on a machine that doesn’t have home brew installed independently from Julia.

**Comment by gideonsimpson** [comment]
Regarding [issue #47 at LibCURL](https://github.com/JuliaWeb/LibCURL.jl/issues/47), I'll just note that I'm working on MacOS 10.13.6.

**Comment by PaulSoderlind** [comment]
I just mean to report "another build error"

**Comment by daxinnan** [comment]
I run julia on Win10 x64, and found one question in building HDF5.
(v0.7) pkg> build HDF5
  Building LibCURL ─→ `C:\Users\lxc\.julia\packages\LibCURL\p0LUA\deps\build.log`
  Building WinRPM ──→ `C:\Users\lxc\.julia\packages\WinRPM\rDDZz\deps\build.log`
  Building Homebrew → `C:\Users\lxc\.julia\packages\Homebrew\l8kUw\deps\build.log`
  Building CMake ───→ `C:\Users\lxc\.julia\packages\CMake\GhlEs\deps\build.log`
  Building Blosc ───→ `C:\Users\lxc\.julia\packages\Blosc\lzFr0\deps\build.log`
  Building HDF5 ────→ `C:\Users\lxc\.julia\packages\HDF5\PegIy\deps\build.log`
┌ Error: Error building `HDF5`, showing the last 100 of log:
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:151
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:151
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:158
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:158
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:516
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:516
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Bool) at xpath.jl:90
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:90
│ [ Info: Updating WinRPM package list
│ ┌ Warning: `info()` is deprecated, use `@info` instead.
│ │   caller = (::getfield(WinRPM, Symbol("#cacheget#9")){Bool,Bool,String})(::String, ::Bool) at WinRPM.jl:151
│ └ @ WinRPM C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:151
│ INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
│ INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
│ ┌ Warning: `assert` is deprecated, use `@assert` instead.
│ │   caller = xpath(::LibExpat.ETree, ::Symbol, ::LibExpat.XPath{String,Array{LibExpat.ETree,1}}, ::Array{Tuple{Symbol,Any},1}, ::Int64, ::Array{Int64,1}, ::Int64, ::LibExpat.XPath_Collector, ::Type) at xpath.jl:1171
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:1171
│ ┌ Warning: The start/next/done iteration protocol is deprecated. Use `iterate` instead.
│ │   caller = start at WinRPM.jl:214 [inlined]
│ └ @ Core C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:214
│ ┌ Warning: The start/next/done iteration protocol is deprecated. Implement `iterate(::WinRPM.Packages{Set{LibExpat.ETree}})`.
│ │   caller = ip:0x0
│ └ @ Core :-1
│ ┌ Warning: The start/next/done iteration protocol is deprecated. Use `iterate` instead.
│ │   caller = start at WinRPM.jl:214 [inlined]
│ └ @ Core C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:214
│ ┌ Warning: `replace(s::AbstractString, pat, f)` is deprecated, use `replace(s, pat => f)` instead.
│ │   caller = (::getfield(WinRPM, Symbol("##21#23")){Array{Array{AbstractString,1},1},Array{LibExpat.ETree,1}})(::LibExpat.ETree) at WinRPM.jl:413
│ └ @ WinRPM C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:413
│ ┌ Warning: `assert` is deprecated, use `@assert` instead.
│ │   caller = xpath(::Array{AbstractString,1}, ::Symbol, ::LibExpat.XPath{String,Array{LibExpat.ETree,1}}, ::Array{Tuple{Symbol,Any},1}, ::Int64, ::Array{Int64,1}, ::Int64, ::LibExpat.XPath_Collector, ::Type) at xpath.jl:1171
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:1171
│ ┌ Warning: The start/next/done iteration protocol is deprecated. Use `iterate` instead.
│ │   caller = iterate at essentials.jl:853 [inlined]
│ └ @ Core .\essentials.jl:853
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:167
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:167
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:176
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:176
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:177
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:177
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:302
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:302
│ ┌ Warning: `info()` is deprecated, use `@info` instead.
│ │   caller = macro expansion at logging.jl:312 [inlined]
│ └ @ Core .\logging.jl:312
│ INFO: Packages to install: zlib1, hdf5
│ ┌ Warning: The start/next/done iteration protocol is deprecated. Use `iterate` instead.
│ │   caller = iterate at essentials.jl:853 [inlined]
│ └ @ Core .\essentials.jl:853
│ ┌ Warning: `assert` is deprecated, use `@assert` instead.
│ │   caller = xpath(::LibExpat.ETree, ::Symbol, ::LibExpat.XPath{String,AbstractString}, ::Array{Tuple{Symbol,Any},1}, ::Int64, ::Array{Int64,1}, ::Int64, ::LibExpat.XPath_Collector, ::Array{LibExpat.ETree,1}) at xpath.jl:1171
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:1171
│ ┌ Warning: `info()` is deprecated, use `@info` instead.
│ │   caller = do_install(::WinRPM.Package) at WinRPM.jl:456
│ └ @ WinRPM C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:456
│ INFO: Downloading: zlib1
│ ┌ Warning: `info()` is deprecated, use `@info` instead.
│ │   caller = macro expansion at logging.jl:311 [inlined]
│ └ @ Core .\logging.jl:311
│ INFO: Extracting: zlib1
│ ERROR: LoadError: IOError: could not spawn `'D:\Program Files\Julia-0.7.0\bin\7z.exe' x -y 'C:\Users\lxc\.julia\packages\WinRPM\rDDZz\cache\2\noarch%2Fmingw64-zlib1-1.2.8-8.16.noarch.rpm' '-oC:\Users\lxc\.julia\packages\WinRPM\rDDZz\cache\2'`: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{Base.DevNullStream,Base.PipeEndpoint,RawFD}) at .\process.jl:370
│  [2] (::getfield(Base, Symbol("##499#500")){Cmd})(::Tuple{Base.DevNullStream,Base.PipeEndpoint,RawFD}) at .\process.jl:512
│  [3] setup_stdio(::getfield(Base, Symbol("##499#500")){Cmd}, ::Tuple{Base.DevNullStream,Pipe,IOStream}) at .\process.jl:493
│  [4] #_spawn#498(::Nothing, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,IOStream}) at .\process.jl:511
│  [5] _spawn(::Cmd, ::Tuple{Base.DevNullStream,Pipe,IOStream}) at .\process.jl:507
│  [6] #open#508(::Bool, ::Bool, ::Function, ::Cmd, ::Base.DevNullStream) at .\process.jl:601
│  [7] open at .\process.jl:591 [inlined]
│  [8] open(::Cmd, ::String, ::Base.DevNullStream) at .\process.jl:572
│  [9] open at .\process.jl:569 [inlined]
│  [10] macro expansion at .\logging.jl:317 [inlined]
│  [11] do_install(::WinRPM.Package) at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:459
│  [12] do_install(::WinRPM.Packages{Array{LibExpat.ETree,1}}) at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:447
│  [13] macro expansion at .\logging.jl:320 [inlined]
│  [14] #install#19(::Bool, ::Function, ::WinRPM.Package) at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:376
│  [15] #install at .\none:0 [inlined]
│  [16] #install#17 at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:363 [inlined]
│  [17] #install at .\none:0 [inlined] (repeats 2 times)
│  [18] (::getfield(WinRPM, Symbol("##34#35")){WinRPM.RPM})() at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\winrpm_bindeps.jl:42
│  [19] run(::getfield(WinRPM, Symbol("##34#35")){WinRPM.RPM}) at C:\Users\lxc\.julia\packages\BinDeps\Z6fwm\src\BinDeps.jl:483
│  [20] macro expansion at .\logging.jl:308 [inlined]
│  [21] run(::BinDeps.SynchronousStepCollection) at C:\Users\lxc\.julia\packages\BinDeps\Z6fwm\src\BinDeps.jl:523
│  [22] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\lxc\.julia\packages\BinDeps\Z6fwm\src\dependencies.jl:944
│  [23] satisfy!(::BinDeps.LibraryDependency) at C:\Users\lxc\.julia\packages\BinDeps\Z6fwm\src\dependencies.jl:922
│  [24] top-level scope at C:\Users\lxc\.julia\packages\BinDeps\Z6fwm\src\dependencies.jl:977
│  [25] include at .\boot.jl:317 [inlined]
│  [26] include_relative(::Module, ::String) at .\loading.jl:1038
│  [27] include(::Module, ::String) at .\sysimg.jl:29
│  [28] include(::String) at .\client.jl:398
│  [29] top-level scope at none:0
│ in expression starting at C:\Users\lxc\.julia\packages\HDF5\PegIy\deps\build.jl:41
│
│ Full log at C:\Users\lxc\.julia\packages\HDF5\PegIy\deps\build.log
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068

**Comment by daxinnan** [comment]
[build.log](https://github.com/JuliaIO/HDF5.jl/files/2293873/build.log)

**Comment by gideonsimpson** [comment]
I should add to this that I'm having the same problem on a 0.6.4 machine too.  Something is going wrong with that gmp library on MacOS.

**Comment by gideonsimpson** [comment]
It now seems to work on my 0.6.4 and 0.7.0 builds, in the sense that ``using HDF5`` doesn't result in a bunch of errors.

**Comment by musm** [comment]
Let's close this for now until further issues crop up

**Comment by musm** [comment]
@daniellivingston  try running first ` brew install gcc; brew link --overwrite gcc; brew install hdf5`

**Comment by daniellivingston** [comment]
@musm Brilliant, that worked like a charm. Thanks!

**Comment by musm** [comment]
@daniellivingston  sorry this isin't more automated. I don't use MacOs and homebrew.jl has been causing issues, so this is the best option currently.

**Comment by daniellivingston** [comment]
@musm Not a problem. I've noticed issues with Homebrew.jl as well. Appreciate your work on this critical package.

**Comment by Jo-Fleck** [comment]
@musm Thanks!
