### ISSUE TITLE
Appveyor

### ISSUE THREAD

**Issue by timholy** [JuliaIO/HDF5.jl#499]
I had far too many projects running on my Appveyor account, and they were clogging my CI queue quite badly. I've removed this one from my account, so alternative arrangements will need to be made.

**Comment by musm** [comment]
I can move it to my account. How do I update the repo to point to my account?

**Comment by musm** [comment]
I see, I don't have permissions to update the webhooks   the new url should behttps://ci.appveyor.com/api/github/webhook?id=9k4bxvy1707sr0rw

**Comment by mbauman** [comment]
I have updated the webhook URL.

**Comment by simonbyrne** [comment]
You should also update the badge in the README.

**Comment by musm** [comment]
thanks
