### ISSUE TITLE
Errors when installing HDF5 v0.9.4

### ISSUE THREAD

**Issue by nhavt** [JuliaIO/HDF5.jl#500]
Hi there, 
When using the HDF5 v0.9.4 module, I have gotten errors which you can see in the attached file
[Error HDF5.txt](https://github.com/JuliaIO/HDF5.jl/files/2296628/Error.HDF5.txt)
. Could anyone please look at it and let me know how to fix this issue? I am using Julia 1.0.0 under Windows 10. Thanks in advance!
Nha

**Comment by musm** [comment]
You need to update the packages

**Comment by nhavt** [comment]
Hi there, thanks for your comment. However, I didn't get it. Do you mean by running the command Pkg.update()? Or could you please tell me a bit more? Thanks in advance! Nha

**Comment by musm** [comment]
Yea, run` import Package; Package.update()`

**Comment by musm** [comment]
Hmm I see u have the latest version. This error should not be there.

**Comment by musm** [comment]
I think I see the problem

**Comment by nhavt** [comment]
Even I ran both commands Pkg.update() and import HDF5, I still got the same problem :(

**Comment by musm** [comment]
There's a missing deprecation, I have a PR to fix this. Please be patient until we tag a new release with the fix.

**Comment by nhavt** [comment]
Ok, thanks very much for looking at this issue!

**Comment by musm** [comment]
Actually there are downstream issues related to LibExpat.jl that prevent hdf5 building on windows on Julia 1.

**Comment by daxinnan** [comment]
I also meet one problem when building HDF5
`(v0.7) pkg> add HDF5
 Resolving package versions...
 Installed WinRPM ────────── v0.4.0
 Installed Parameters ────── v0.9.2
 Installed LibExpat ──────── v0.4.2
 Installed HTTPClient ────── v0.2.1
 Installed BufferedStreams ─ v1.0.0
 Installed Homebrew ──────── v0.7.0
 Installed HDF5 ──────────── v0.9.4
 Installed LibCURL ───────── v0.3.1
 Installed CMakeWrapper ──── v0.2.2
 Installed CMake ─────────── v1.0.1
 Installed Libz ──────────── v1.0.0
 Installed BinDeps ───────── v0.8.10
 Installed Blosc ─────────── v0.5.1
  Updating `C:\Users\lxc\.julia\environments\v0.7\Project.toml`
  [f67ccb44] + HDF5 v0.9.4
  Updating `C:\Users\lxc\.julia\environments\v0.7\Manifest.toml`
  [9e28174c] + BinDeps v0.8.10
  [a74b3585] + Blosc v0.5.1
  [e1450e63] + BufferedStreams v1.0.0
  [631607c0] + CMake v1.0.1
  [d5fb7624] + CMakeWrapper v0.2.2
  [f67ccb44] + HDF5 v0.9.4
  [0862f596] + HTTPClient v0.2.1
  [d9be37ee] + Homebrew v0.7.0
  [b27032c2] + LibCURL v0.3.1
  [522f3ed2] + LibExpat v0.4.2
  [2ec943e9] + Libz v1.0.0
  [d96e819e] + Parameters v0.9.2
  [c17dfb99] + WinRPM v0.4.0
  Building LibCURL ─→ `C:\Users\lxc\.julia\packages\LibCURL\Qs5og\deps\build.log`
  Building WinRPM ──→ `C:\Users\lxc\.julia\packages\WinRPM\rDDZz\deps\build.log`
┌ Error: Error building `WinRPM`, showing the last 100 of log:
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:424
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:424
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:426
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:426
│ ┌ Warning: `nb_available` is deprecated, use `bytesavailable` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:0
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:0
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:337
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:337
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:340
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:340
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:345
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:345
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Bool) at xpath.jl:90
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:90
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:527
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:527
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:530
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:530
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:346
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:346
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = consume_function(::String, ::Int64, ::String, ::Bool) at xpath.jl:644
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:644
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = consume_function(::String, ::Int64, ::String, ::Bool) at xpath.jl:660
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:660
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = consume_function(::String, ::Int64, ::String, ::Bool) at xpath.jl:676
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:676
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = consume_function(::String, ::Int64, ::String, ::Bool) at xpath.jl:679
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:679
│ ┌ Warning: `nb_available` is deprecated, use `bytesavailable` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:463
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:463
│ ┌ Warning: `nb_available` is deprecated, use `bytesavailable` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:428
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:428
│ ┌ Warning: `isalpha` is deprecated, use `isletter` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:433
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:433
│ ┌ Warning: `isalnum(c::Char)` is deprecated, use `isletter(c) || isnumeric(c)` instead.
│ │   caller = xpath_parse_expr(::String, ::Int64, ::Int64, ::Bool) at xpath.jl:438
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:438
│ ┌ Warning: `done(s::AbstractString, i::Integer)` is deprecated, use `i > ncodeunits(s)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:223
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:223
│ ┌ Warning: `next(s::AbstractString, i::Integer)` is deprecated, use `iterate(s, i)` instead.
│ │   caller = xpath_parse(::String, ::Int64, ::Bool) at xpath.jl:226
│ └ @ LibExpat C:\Users\lxc\.julia\packages\LibExpat\FAade\src\xpath.jl:226
│ ┌ Warning: Loop variable `installed` around C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:426 overwrites a variable in an enclosing scope. In the future the variable will be local to the loop instead.
│ └ @ C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:426
│ ERROR: LoadError: LoadError: Failed to precompile BinDeps [9e28174c-4ba2-5203-b857-d8d62c4213ee] to C:\Users\lxc\.julia\compiled\v0.7\BinDeps\iBhbp.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include at .\sysimg.jl:29 [inlined]
│  [11] include(::String) at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:3
│  [12] top-level scope at none:0
│  [13] include at .\boot.jl:317 [inlined]
│  [14] include_relative(::Module, ::String) at .\loading.jl:1038
│  [15] include(::Module, ::String) at .\sysimg.jl:29
│  [16] top-level scope at none:2
│  [17] eval at .\boot.jl:319 [inlined]
│  [18] eval(::Expr) at .\client.jl:399
│  [19] top-level scope at .\none:3
│ in expression starting at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\winrpm_bindeps.jl:3
│ in expression starting at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\src\WinRPM.jl:517
│ ERROR: LoadError: Failed to precompile WinRPM [c17dfb99-b4f7-5aad-8812-456da1ad7187] to C:\Users\lxc\.julia\compiled\v0.7\WinRPM\ko3j0.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] top-level scope at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\deps\build.jl:2
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:398
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\deps\build.jl:1
│
│ Full log at C:\Users\lxc\.julia\packages\WinRPM\rDDZz\deps\build.log
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
  Building Homebrew → `C:\Users\lxc\.julia\packages\Homebrew\l8kUw\deps\build.log`
  Building CMake ───→ `C:\Users\lxc\.julia\packages\CMake\GhlEs\deps\build.log`
┌ Error: Error building `CMake`:
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:114
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:114
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│ ERROR: LoadError: Failed to precompile BinDeps [9e28174c-4ba2-5203-b857-d8d62c4213ee] to C:\Users\lxc\.julia\compiled\v0.7\BinDeps\iBhbp.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:398
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\lxc\.julia\packages\CMake\GhlEs\deps\build.jl:1
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
  Building Blosc ───→ `C:\Users\lxc\.julia\packages\Blosc\lzFr0\deps\build.log`
┌ Error: Error building `Blosc`:
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:151
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:151
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│ ERROR: LoadError: Failed to precompile BinDeps [9e28174c-4ba2-5203-b857-d8d62c4213ee] to C:\Users\lxc\.julia\compiled\v0.7\BinDeps\iBhbp.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] top-level scope at none:2
│  [12] eval at .\boot.jl:319 [inlined]
│  [13] eval(::Expr) at .\client.jl:399
│  [14] top-level scope at .\none:3
│ in expression starting at C:\Users\lxc\.julia\packages\CMakeWrapper\8d1RU\src\CMakeWrapper.jl:6
│ ERROR: LoadError: LoadError: Failed to precompile CMakeWrapper [d5fb7624-851a-54ee-a528-d3f3bac0b4a0] to C:\Users\lxc\.julia\compiled\v0.7\CMakeWrapper\geahK.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] macro expansion at .\logging.jl:311 [inlined]
│  [5] _require(::Base.PkgId) at .\loading.jl:941
│  [6] require(::Base.PkgId) at .\loading.jl:852
│  [7] macro expansion at .\logging.jl:311 [inlined]
│  [8] require(::Module, ::Symbol) at .\loading.jl:834
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:398
│  [13] top-level scope at none:0
│  [14] include at .\boot.jl:317 [inlined]
│  [15] include_relative(::Module, ::String) at .\loading.jl:1038
│  [16] include(::Module, ::String) at .\sysimg.jl:29
│  [17] include(::String) at .\client.jl:398
│  [18] top-level scope at none:0
│ in expression starting at C:\Users\lxc\.julia\packages\Blosc\lzFr0\deps\compile.jl:2
│ in expression starting at C:\Users\lxc\.julia\packages\Blosc\lzFr0\deps\build.jl:2
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
  Building HDF5 ────→ `C:\Users\lxc\.julia\packages\HDF5\jDzcD\deps\build.log`
┌ Error: Error building `HDF5`:
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:114
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│
│ Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
│ Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffdee8bd44f -- RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ in expression starting at C:\Users\lxc\.julia\packages\BinDeps\ZEval\src\dependencies.jl:114
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ RtlReAllocateHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
│ realloc at C:\WINDOWS\System32\msvcrt.dll (unknown line)
│ ERROR: LoadError: Failed to precompile BinDeps [9e28174c-4ba2-5203-b857-d8d62c4213ee] to C:\Users\lxc\.julia\compiled\v0.7\BinDeps\iBhbp.ji.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] macro expansion at .\logging.jl:313 [inlined]
│  [3] compilecache(::Base.PkgId, ::String) at .\loading.jl:1185
│  [4] _require(::Base.PkgId) at .\logging.jl:311
│  [5] require(::Base.PkgId) at .\loading.jl:852
│  [6] macro expansion at .\logging.jl:311 [inlined]
│  [7] require(::Module, ::Symbol) at .\loading.jl:834
│  [8] include at .\boot.jl:317 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1038
│  [10] include(::Module, ::String) at .\sysimg.jl:29
│  [11] include(::String) at .\client.jl:398
│  [12] top-level scope at none:0
│ in expression starting at C:\Users\lxc\.julia\packages\HDF5\jDzcD\deps\build.jl:1
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068`

**Comment by gideonsimpson** [comment]
I've got a separate issue with 0.9.4 on MacOS with 0.7

```
  Building HDF5 ─→ `~/.julia/packages/HDF5/jDzcD/deps/build.log`
┌ Error: Error building `HDF5`: 
│ ==> Installing libmpc from staticfloat/juliatranslated
│ ==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.1.0.high_sierra.bottle.tar.gz
│ ==> Pouring libmpc-1.1.0.high_sierra.bottle.tar.gz
│ Warning: The post-install step did not complete successfully
│ You can try again using `brew postinstall staticfloat/juliatranslated/libmpc`

```

**Comment by musm** [comment]
WIndows issues now fixed, @daxinnan  and @nhavt  please run `pkg> up` and try again. 

Thanks for the report

**Comment by nhavt** [comment]
yes, it works perfectly! Thanks very much for fixing this issue!
