### ISSUE TITLE
Stop providing binaries?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaIO/HDF5.jl#504]
I'm wondering if it would be better simply to ask users to install HDF5 binaries and then use them instead of the current situation. I'm suggesting this because

1) The Mac situation is currently pretty bad and it is unlikely that we'll be able to use BinaryBuilder since HDF5 apparently can't be cross-compiled. Even if somebody decides to fix https://github.com/Homebrew/homebrew-core/issues/27751, relying on `Homebrew.jl` has proven to be a source for many problems over the years.
2) On HPC systems, you'd typically want to use the system provided libhdf5 anyway since it will be linked with the MPI on the system.

Thoughts?

**Comment by musm** [comment]
See the end of the discussion at https://github.com/JuliaIO/HDF5.jl/issues/471
I think this is the most reasonable near-term solution, give the huge number of problems with Homebrew.jl and WinRPM.jl (both have been proven unreliable over time)

**Comment by andreasnoack** [comment]
> I think this is the most reasonable

Could you clarify what *this* refers to?

**Comment by musm** [comment]
"install HDF5 binaries and then use them instead of the current situation."

**Comment by tknopp** [comment]
not providing binaries would imply Travis testing not working anymore, no?

**Comment by andreasnoack** [comment]
No, I don't think so. You would just add `libhdf5-dev` via the dependency entries in `.travis.yml`.

**Comment by musm** [comment]
Fixed by the latest version when it goes through #555
