### ISSUE TITLE
Memory leak with arrays in conjuciton with HDF5

### ISSUE THREAD

**Issue by fremling** [JuliaIO/HDF5.jl#537]
I'm quite new to julia, but i've noticed that there seems to be a memory leak in the HDF5 package in julia version 1.0.2 with the "HDF5" package is 0.10.2.

If i run the following code (Ubuntu 18.04)

    using HDF5
    using LinearAlgebra
    function HDF5MemoryLeak1(Num)
        MyArray=randn(1000,100)
        fid=h5open("testfile.hdf5","w")
        close(fid)
    end
    function HDF5MemoryLeak2(Num)
        #MyArray=randn(1000,100)
        fid=h5open("testfile.hdf5","w")
        close(fid)
    end
    function HDF5MemoryLeak3(Num)
        MyArray=randn(1000,100)
        #fid=h5open("testfile.hdf5","w")
        #close(fid)
    end
    function HDF5MemoryLeak4(Num)
        NyMarray=randn(1000,100)
        NyMarray=nothing
        fid=h5open("testfile.hdf5","w")
        close(fid)
    end

    N=2*10^3
    for j in 1:N
        println("$j of $N")
        HDF5MemoryLeak(j)
    end

If i run this file and replace in the loops HDF5MemoryLeak by HDF5MemoryLeak1, HDF5MemoryLeak2 or HDF5MemoryLeak3 i get the following reads on top

    <Call_Name>         VIRT      RES    SHR 
    HDF5MemoryLeak1 12332192   1.683g  80252
    HDF5MemoryLeak2   802256   235908  79020
    HDF5MemoryLeak3   810720   242440  79500
    HDF5MemoryLeak4    2532724 1.720g 106868

So it looks like one their own, the hdf5 module and the linear algebra package to not leak memory, but together they do?

Ive seen this discussion https://github.com/JuliaIO/HDF5.jl/issues/349 on memory leaks, but i'm not sure this is the same issue.

**Comment by ludvigak** [comment]
I believe I'm seeing the same thing (just posted in #349).

**Comment by musm** [comment]
Leaks 1 to 3 are fixed by PR https://github.com/JuliaIO/HDF5.jl/pull/629

**Comment by musm** [comment]
closed by https://github.com/JuliaIO/HDF5.jl/pull/629 thanks to @MarkusSchildhauer  !
