### ISSUE TITLE
HDF5Attributes should support keys()

### ISSUE THREAD

**Issue by dnadlinger** [JuliaIO/HDF5.jl#554]
As per the title – HDF5Attributes is indexed like a dictionary, so I constantly find myself typing `keys(a)` instead of `names(a)`. Is there a reason `keys` isn't supported?

**Comment by rafaqz** [comment]
I was also about to post this, having a method for `keys` makes sense.

**Comment by musm** [comment]
good idea, Prs always welcome 😄

**Comment by musm** [comment]
fixed by https://github.com/JuliaIO/HDF5.jl/pull/698
