### ISSUE TITLE
v0.12 depends on binaries, breaking function on all but few platforms

### ISSUE THREAD

**Issue by hrobotron** [JuliaIO/HDF5.jl#562]
Hello,

Being a long time user of Julia on i686/amd64 PC, I am trying to start using it on (embedded) ARM. Unfortunately, the crucial HDF5 (required by JLD, so practically essential) failed to build. The same reason reported by other user here:
https://stackoverflow.com/questions/57184292/gcc-aarch64-linux-gnu-is-not-supported-by-julia-package-hdf5/57325113#57325113

It seems that in v0.12 the HDF5 introduces some new binary dependency. But the binaries exist only for a few platforms. My workaround was to pin to v0.11.1.

However, I am convinced the "new" way is very bad. There is plenty of platforms and Julia shall not fail to support them without a good reason.

I can agree the new approach with binaries could be a good _alternative_ to using system-wide libhdf5, but it shall not fail so horribly. As a hotfix, I would recommend at least to broaden the error msg of unsupported binaries to something like: pin older version, and install systemwide hdf5 lib(s)...

**Comment by musm** [comment]
cc @staticfloat

**Comment by hrobotron** [comment]
With versions up to 0.11.1, it was sufficient at least on my apt-based systems to just install hdf5 libraries (OS distro binaries, no custom changes), and HDF5 & JLD just worked. I can believe that having extra source for HDF5 binaries may have some sense for certain platforms. But please _do not break the basic function on the platforms, which are not explicitly supported by the custom binaries_.

The HDF5 is a necessary prerequisite for JLD, and without JLD the whole Julia is practically unusable. I am afraid a glitch like this, with not a very understandable error msg, may divert lot of possible Julia newcomers/adopters, who do not have one of the very few architectures provided by HDF5 0.12 bins.

I think that at least for the very beginning, the same 0.12 code shall _at least_ provide a more descriptive error msg, recommending to pin to 0.11.1 as a workaround.

**Comment by musm** [comment]
It certainly wasn't the intention to break  support of other platforms. In contrast, we were trying to circumvent the numerous bugs people have had on the major operating systems with building HDF5.  We should definitely have a manual fallback if the platform isn't supported and this is something that can be implemented in the build script. Thanks for letting us know @hrobotron .

**Comment by musm** [comment]
for reference we should implement a similar fallback as in
https://github.com/stevengj/Blosc.jl/blob/master/deps/build.jl

**Comment by musm** [comment]
```
using BinaryProvider

platform_key_abi()
```

what does it spit out for your system?

**Comment by musm** [comment]
The build script should indeed throw an error with the description
`pkg> build HDF5` 
what does that spit?

**Comment by musm** [comment]
I've been testing out a manual compilation fallback at https://github.com/JuliaIO/HDF5.jl/issues/562

**Comment by musm** [comment]
If you have the time please try the PR to double check it fixes the issue for you!

**Comment by musm** [comment]
if it works we can merge it and close this issue

**Comment by musm** [comment]
@ziyixi  see master for the latest fix, can you test if possible?

**Comment by ziyixi** [comment]
@musm  I have tested to set FORCE_COMPILE_HDF5 as yes, and the package will download the source file and compile it. However, I am thinking maybe it's better to provide my own compiled library (maybe another environmental variable?), as in `compile.jl`, it will compile the serial version of HDF5, and I am planning to use the parallel version. (maybe find a way to set CC=mpicc and enable some parallel flags in compiling?) 

Also it seems compiling from the source is a little bit slow since it seems only compiling in serial, but that is not a big issue anyway.

**Comment by musm** [comment]
@ziyixi  ok thanks for feedback. I created a pull request enabling MPI hdf5 build if it is installed (i.e. make sure you have mpich installed)  and also enabled building in parallel.

**Comment by musm** [comment]
@ziyixi  please try master branch and let me know if it works better for you!

**Comment by ziyixi** [comment]
@musm Thanks for adding it! And it works better for me. I suppose the parallel version should work now, but when I run `test/mpio.jl`, it fails as `CComm` and `CInfo` have been deprecated in the newer version of MPI. I have checked the MPI git history and maybe it's related to https://github.com/JuliaParallel/MPI.jl/commit/a76657b43c68a58ff1fe24b79ec6a9ad39816e96
