### ISSUE TITLE
Julia 1.3 threaded writing segfaults

### ISSUE THREAD

**Issue by scottstanie** [JuliaIO/HDF5.jl#564]
Trying to write to different within a Threads.@threads loop in Julia 1.3:

```
julia> versioninfo()
Julia Version 1.3.0-alpha.0
Commit 6c11e7c2c4 (2019-07-23 01:46 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

julia> using HDF5

julia> function f1()
       function innerwrite(layer, i)
           h5open("testwrite$i.h5", "w") do f
               write(f, "stack", layer)
               println("writing testwrite$i on thread $(Threads.threadid())")
           end
       end
       rr = rand(800, 800, 5);
       Threads.@threads for i = 1:size(rr, 3)
           innerwrite(rr[:, :, i], i)
       end
       end
f1 (generic function with 1 method)

julia> f1()
Segmentation fault: 11
```

**Comment by evetion** [comment]
The underlying HDF5 C library is not threadsafe, so you can't use `@threads` with HDF5.jl. There is a threadsafe version of the HDF5 C library, but that won't give you speed ups as locks to one thread.

**Comment by scottstanie** [comment]
Gotcha- so the 1.3 improvements wouldn't really apply and I supposed I should close this then

**Comment by evetion** [comment]
To be fair, this is something that could be at least documented/warned against in this library, since many people will try this now that 1.3 is released.

**Comment by scottstanie** [comment]
Would it be helpful for me to add something to the README to take note of this?

**Comment by musm** [comment]
https://portal.hdfgroup.org/display/knowledge/Questions+about+thread-safety+and+concurrent+access
