### ISSUE TITLE
Permit reading values into a preexisting array buffer

### ISSUE THREAD

**Issue by rafaqz** [JuliaIO/HDF5.jl#580]
Is there a way of reading from hdf5 directly into a preexisting array buffer? 

Edit: It would also be useful to expose a version of `getindex` or ` copyto!` or something for retrieving part of an array - that let you pass in the dest array instead of [allocating it every time](https://github.com/JuliaIO/HDF5.jl/blob/master/src/HDF5.jl#L1781).

**Comment by Luapulu** [comment]
I’d be interested in this, too.

**Comment by musm** [comment]
dupe of https://github.com/JuliaIO/HDF5.jl/issues/409
