### ISSUE TITLE
write hd5 file with custom data

### ISSUE THREAD

**Issue by hshi** [JuliaIO/HDF5.jl#582]
I want to use HDF5 to write my custom data, like following. However, it failed. May I ask if there is a way to fix that? Thank you.

```
using HDF5
  
struct OneBodyUnit
   i::Int
   j::Int
   t::Float64
end

h1 = Vector{OneBodyUnit}(undef, 3)
h1[1] = OneBodyUnit(1,2,2.3)
h1[2] = OneBodyUnit(2,1,2.1)
h1[3] = OneBodyUnit(2,2,1.2)

h5open("h.h5", "w") do file
    write( file, "h1", h1 )
end
```

Error information is

> MethodError: no method matching write(::HDF5.HDF5File, ::String, ::Array{OneBodyUnit,1})

**Comment by kleinhenz** [comment]
`test/custom.jl` and `test/compound.jl` have examples of writing structs to hdf5 datasets using compound datatypes.

**Comment by musm** [comment]
We should add this to the docs
