### ISSUE TITLE
define keys instead of (or as well as) names

### ISSUE THREAD

**Issue by rafaqz** [JuliaIO/HDF5.jl#590]
`keys` is the general method for returning a list of keys in julia, such as for NamedTuple or Dict.

We should add a `Base.keys` method for datasets and depreciate `names`.

**Comment by musm** [comment]
Makes sense

**Comment by musm** [comment]
What other methods should we define `keys` makes sense?

Does it make sense to support a dict like interface

**Comment by musm** [comment]
duplicate of https://github.com/JuliaIO/HDF5.jl/issues/590
