### ISSUE TITLE
Use HDF5_jll.jl

### ISSUE THREAD

**Issue by crstnbr** [JuliaIO/HDF5.jl#594]
Are there yet any concrete plans to switch to using [HDF5_jll.jl](https://github.com/JuliaBinaryWrappers/HDF5_jll.jl) given that 1.3 will be released soon?

**Comment by musm** [comment]
Did you create the repo? I'm  not sure who made that, but hopefully we can.

**Comment by crstnbr** [comment]
> Did you create the repo? I'm not sure who made that, but hopefully we can.

No, it wasn't me. I assume it has been created by an Azure pipline based on [this `build_tarballs.jl`](https://github.com/JuliaPackaging/Yggdrasil/tree/master/H/HDF5) in Yggdrasil.

**Comment by musm** [comment]
Thanks. Let me try to see if I can wire it up here.
