### ISSUE TITLE
MPI support and HDF5_jll

### ISSUE THREAD

**Issue by jipolanco** [JuliaIO/HDF5.jl#606]
Hi,

I have noticed that the recent switch to using `HDF5_jll` (c26820bfdc) to provide the HDF5 binaries has removed the possibility to use MPI-enabled HDF5 libraries. Previously, this was possible via the `FORCE_COMPILE_HDF5` environment variable, which has no effect in the current master.

Are there any plans to bring back an approach to use parallel HDF5 libraries?

I feel like, in this case, it would be acceptable to use system provided HDF5 libraries, since often one wants to run on HPC clusters that already have some version of HDF5 compiled with parallel support. Couldn't this be done via an optional environment variable, similarly to [what MPI.jl does](https://juliaparallel.github.io/MPI.jl/latest/installation/#Building-1) to detect the system MPI implementation to use?

If this is an acceptable strategy, I could make an attempt at supporting user-provided HDF5 libraries.

**Comment by musm** [comment]
@jipolanco  we definitely want to provide a "fallback" mechanism which would allow users to compile HDF5 themselves and bypass `HDF5_jll`.  Feel free to open a PR as we would take it very seriously and is something I want to have in before we make a new release.  Take a look at how FFTW.jl handles this (albeit a different mechanism)

**Comment by jipolanco** [comment]
Ok, thanks for your answer. I'll start working on it.

**Comment by jipolanco** [comment]
Closed by e8035363e1848d1d91fcdea192c1a0c36b1238ed
