### ISSUE TITLE
Build error: signal (7)

### ISSUE THREAD

**Issue by Byrth** [JuliaIO/HDF5.jl#608]
~~~
signal (7): Bus error
in expression starting at /home/dev/.julia/packages/HDF5/Zh9on/deps/build_HDF5.v1.10.5.jl:35
(truncated)
~~~
full error log: https://gist.github.com/Byrth/4a436c204da61750240770269c7f89af

I am trying to build HDF5 (v0.12.5) on an Ubuntu 18.04 VM on Julia 1.3 with FORCE_COMPILE_HDF5="yes" set. Given that this is a bus error, I have already tried:
* pumping up the RAM to 12GB
* running build_HDF5.v1.10.5.jl line-by-line with `pwd()`=="~" (works, and FORCE_COMPILE_HDF5 is as expected)
* running `]build HDF5` and watching `top` (no spikes observed before SIGBUS)
* increasing the size of `/dev/shm` to 2GB, as limitations in that regard have resulted in Signal (7) errors in the past and you guys do seem to use Mmap

Would any other information be helpful?

**Comment by Byrth** [comment]
~~~
(v1.3) pkg> build HDF5
  Building CMake → `~/.julia/packages/CMake/nSK2r/deps/build.log`
  Building Blosc → `~/.julia/packages/Blosc/lzFr0/deps/build.log`
  Building HDF5 ─→ `~/.julia/packages/HDF5/Zh9on/deps/build.log`
┌ Error: Error building `HDF5`: 
│ ERROR: LoadError: LoadError: LibraryProduct(nothing, ["libhdf5_from_src_hl"], :libhdf5_hl, "Prefix(/home/dev/.julia/packages/HDF5/Zh9on/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at /home/dev/.julia/packages/BinaryProvider/kcGxO/src/Products.jl:414
│  [3] (::BinaryProvider.var"#kw##write_deps_file")(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at /home/dev/.julia/packages/HDF5/Zh9on/deps/build_HDF5.v1.10.5.jl:68
│  [5] include at ./boot.jl:328 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1105
│  [7] include(::Module, ::String) at ./Base.jl:31
│  [8] include(::String) at ./client.jl:424
│  [9] top-level scope at /home/dev/.julia/packages/HDF5/Zh9on/deps/build.jl:2
│  [10] include at ./boot.jl:328 [inlined]
│  [11] include_relative(::Module, ::String) at ./loading.jl:1105
│  [12] include(::Module, ::String) at ./Base.jl:31
│  [13] include(::String) at ./client.jl:424
│  [14] top-level scope at none:5
│ in expression starting at /home/dev/.julia/packages/HDF5/Zh9on/deps/build_HDF5.v1.10.5.jl:68
│ in expression starting at /home/dev/.julia/packages/HDF5/Zh9on/deps/build.jl:2
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/backwards_compatible_isolation.jl:649
~~~

After deleting .julia, the error changed to be this. I suspect that there is likely some kind of incompatible mix of versions going on here

**Comment by Byrth** [comment]
Testing previous versions:
v0.12.0 - builds successfully
v0.12.2 - builds successfully, but much slower than v0.12.0 for some reason
v0.12.3 - fails
v0.12.4 - fails with the same error as v0.12.3
v0.12.5 - fails with the same error as v0.12.3 (generated the errors posted above)

Looking at the diff between v0.12.2 and v0.12.3, it almost has to be this commit that causes the problem:
https://github.com/JuliaIO/HDF5.jl/commit/e1bae316be77be3cbd92029cd6b1b2267dae355b

**Comment by musm** [comment]
@Byrth  is the name indeed libhdf5_serial_hl ?

**Comment by musm** [comment]
BTW did you test master?
`FORCE_COMPILE_HDF5` is only available on the master build

**Comment by musm** [comment]
Also if you rename `libhdf5_serial_hl` to `libhdf5_hl` do things work?

**Comment by Byrth** [comment]
I'm not sure I understand. As seen above in the post, I do indeed have `/usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so`, but I also have `/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so`

One of them is probably libhdf5-dev and the other might be libhdf5tools.

I can check this later. Posting in hopes that I remember.

**Comment by musm** [comment]
stale
