### ISSUE TITLE
2.2x h5d_read slowdown in v >= 0.12.4

### ISSUE THREAD

**Issue by jpjones76** [JuliaIO/HDF5.jl#609]
When benchmarking file read times with HDF5, I encounter slowdown ~2.2x in calls to `h5d_read` in HDF5.jl v >= 0.12.4 relative to HDF5.jl v0.12.3. Any insights into what might cause this?

MWE, minus large test file (which I'll gladly share if necessary): 
```
using HDF5, BenchmarkTools
BenchmarkTools.DEFAULT_PARAMETERS.seconds   = 10
BenchmarkTools.DEFAULT_PARAMETERS.samples   = 100
BenchmarkTools.DEFAULT_PARAMETERS.gcsample  = true
fname = "/data2/Code/Julia/SeisIO_paper/Benchmarks/2days-40hz.h5"
f = h5open(fname, "r")
W = f["Waveforms/CI.SDD/CI.SDD..HHZ__2019-07-07T00:00:00__2019-07-09T00:00:00__hhz_"]
nx = 6912001
X = Array{Float32, 1}(undef, nx);
src_ind = 1:nx
dest_ind = 1:nx
dsel_id = HDF5.hyperslab(W, src_ind)
memtype = HDF5.datatype(X)
memspace = HDF5.dataspace(X)
HDF5.h5d_read(W.id, memtype.id, memspace.id, dsel_id, W.xfer, X)
@benchmark HDF5.h5d_read($W.id, $memtype.id, $memspace.id, $dsel_id, $W.xfer, $X)
```

Output with HDF5 v0.12.3, Julia 1.2.0:
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     82.691 ms (0.00% GC)
  median time:      84.169 ms (0.00% GC)
  mean time:        85.337 ms (0.00% GC)
  maximum time:     99.194 ms (0.00% GC)
  --------------
  samples:          34
  evals/sample:     1
```

Output with HDF5 v0.12.4, Julia 1.2.0:
```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     195.849 ms (0.00% GC)
  median time:      196.988 ms (0.00% GC)
  mean time:        197.374 ms (0.00% GC)
  maximum time:     203.277 ms (0.00% GC)
  --------------
  samples:          23
  evals/sample:     1
```

HDF5 v0.12.5 is nearly identical.

Relevant line from `@profile` in Julia 1.2.0 (note that I use `Profile.init(n = 10^9, delay = 0.0001)`):
* HDF5 v0.12.3: `3418 /home/josh/.julia/packages/HDF5/DktP4/src/HDF5.jl:2301; h5d_read`
* HDF5 v0.12.4: `7374 /home/josh/.julia/packages/HDF5/rF1Fe/src/HDF5.jl:2277; h5d_read`

Seen in Julia versions: 1.0.5, 1.1.0, 1.2.0, 1.3.1.

**Comment by musm** [comment]
That's strange looking at https://github.com/JuliaIO/HDF5.jl/compare/v0.12.3...v0.12.4 this looks to be related to changes in how we ship HDF5 and zlib binaries from BinaryBuilder?  It's really hard to tell what is causing this

**Comment by musm** [comment]
can you post the datafile where you see this?

**Comment by jpjones76** [comment]
Sure, here you are.

[2days-40hz.zip](https://github.com/JuliaIO/HDF5.jl/files/4314662/2days-40hz.zip)

**Comment by musm** [comment]
Thanks, with your test script I get identical timings with HDF5v0.13

**Comment by musm** [comment]
My machine:

```
julia> versioninfo()
Julia Version 1.4.0-rc2.0
Commit b99ed72c95 (2020-02-24 16:51 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = "C:\Program Files\Microsoft VS Code\Code.exe"
  JULIA_NUM_THREADS = 4
```

**Comment by jpjones76** [comment]
> Thanks, with your test script I get identical timings with HDF5v0.13

Please clarify: do you mean that the slowdown I saw in 0.12.4-0.12.5 has been resolved in v0.13, or do you mean that the slowdown is still present?

**Comment by musm** [comment]
I mean that  the timings for me are identical on v0.13 to v0.12.3

**Comment by jpjones76** [comment]
This gets weirder. 

When I tried installing a *new* build of Julia-v1.4.0-rc2.0, and adding HDF5, I achieved the speed of v0.12.3. For example:
```
using Pkg
Pkg.add("BenchmarkTools")
Pkg.add("HDF5")
Pkg.update()
cd("/data/Code/Julia/SeisIO/dev"); include("HDF5_609.jl")

BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     95.043 ms (0.00% GC)
  median time:      96.078 ms (0.00% GC)
  mean time:        96.638 ms (0.00% GC)
  maximum time:     103.712 ms (0.00% GC)
  --------------
  samples:          27
  evals/sample:     1
```

However, when I tried to test on v0.12.5 in Julia-v1.4.0-rc2.0, the slowdown reappeared in HDF5. Moreover, it *persists* after returning to HDF5 v0.13.0, and now I can't fix that. For example:

```
using Pkg
Pkg.add(PackageSpec(name="HDF5", version="0.12.5"))
Pkg.update()
Pkg.build("HDF5")
Pkg.add(PackageSpec(name="HDF5", version="0.13.0"))
Pkg.update()
Pkg.build("HDF5")
cd("/data/Code/Julia/SeisIO/dev"); include("HDF5_609.jl")

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     211.007 ms (0.00% GC)
  median time:      212.572 ms (0.00% GC)
  mean time:        212.627 ms (0.00% GC)
  maximum time:     214.365 ms (0.00% GC)
  --------------
  samples:          22
  evals/sample:     1
```

I tried  rm -rf ~/.julia/compiled ~/.julia/environments ~/.julia/registries/General ... no improvement. 

I tried rebuilding Julia-1.0.4 from the source tarball ... no improvement.

Current machine:
```
julia> versioninfo()
Julia Version 1.4.0-rc2.0
Commit b99ed72c95 (2020-02-24 16:51 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by musm** [comment]
Maybe restart the computer?

**Comment by musm** [comment]
Maybe some of the older dll are loaded in memory and things are not properly being freed after upgrading/downgrading

**Comment by jpjones76** [comment]
> Maybe some of the older dll are loaded in memory and things are not properly being freed after upgrading/downgrading

I don't understand how this is possible in Linux.

> Maybe restart the computer?

Tried; no change.

**Comment by musm** [comment]
We fixed some memory leaks so I wonder if that by any chance fixes the issues here

**Comment by jpjones76** [comment]
> We fixed some memory leaks so I wonder if that by any chance fixes the issues here

You got it! Great work! I just tested the new version on the computer I used to run the benchmarks when I opened the issue.

Here's HDF5 0.13.5, Julia 1.5.0:

```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     83.644 ms (0.00% GC)
  median time:      84.747 ms (0.00% GC)
  mean time:        84.604 ms (0.00% GC)
  maximum time:     86.882 ms (0.00% GC)
  --------------
  samples:          25
  evals/sample:     1
```

For completeness, here's HDF5 0.12.3, Julia 1.5.0:

```
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     82.767 ms (0.00% GC)
  median time:      84.013 ms (0.00% GC)
  mean time:        86.420 ms (0.00% GC)
  maximum time:     123.037 ms (0.00% GC)
  --------------
  samples:          26
  evals/sample:     1

```

Excellent work. My colleagues will be thrilled.

**Comment by musm** [comment]
fantastic
