### ISSUE TITLE
Can‘t build CMake on Julia

### ISSUE THREAD

**Issue by JasonZhang625** [JuliaIO/HDF5.jl#612]
Error: Error building `CMake`: 
│ ʹ�á�2���������á�DownloadFile��ʱ�����쳣:���� WebClient �����ڼ䷢���쳣����
│ ����λ�� ��:1 �ַ�: 82
│ + ... pe]::Tls12; (new-object net.webclient).DownloadFile("https://github.c ...
│ +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
│     + FullyQualifiedErrorId : WebException
 
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:794
│ [ Info: Attempting to create directory C:\Users\32817\.juliapro\JuliaPro_v1.0.5-2\packa
│ [ Info: Directory C:\Users\32817\.juliapro\JuliaPro_v1.0.5-2\packages\CMake\ULbyn\deps\
│ [ Info: Downloading file https://github.com/Kitware/CMake/releases/download/v3.15.3/cma
│ ERROR: LoadError: failed process: Process(`'C:\Windows\System32\WindowsPowerShell\v1.0\lType]::Tls12; (new-object net.webclient).DownloadFile("https://github.com/Kitware/CMake/packages\CMake\ULbyn\deps\downloads\cmake-3.15.3-win64-x64.zip")'`, ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:705 [inlined]
│  [3] #run#505(::Bool, ::Function, ::Cmd) at .\process.jl:663
│  [4] run(::Cmd) at .\process.jl:661
│  [5] run(::BinDeps.SynchronousStepCollection) at C:\Users\32817\.juliapro\JuliaPro_v1.0
│  [6] run(::FileRule) at C:\Users\32817\.juliapro\JuliaPro_v1.0.5-2\packages\BinDeps\eiJ
│  [7] run(::BinDeps.SynchronousStepCollection) at C:\Users\32817\.juliapro\JuliaPro_v1.0
│  [8] run(::FileRule) at C:\Users\32817\.juliapro\JuliaPro_v1.0.5-2\packages\BinDeps\eiJ
│  [9] run(::BinDeps.SynchronousStepCollection) at C:\Users\32817\.juliapro\JuliaPro_v1.0
│  [10] top-level scope at none:0
│  [11] include at .\boot.jl:317 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1044
│  [13] include(::Module, ::String) at .\sysimg.jl:29
│  [14] include(::String) at .\client.jl:392
│  [15] top-level scope at none:0
│ in expression starting at C:\Users\32817\.juliapro\JuliaPro_v1.0.5-2\packages\CMake\ULb
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.5\share\julia\stdlib\v1.0\Pkg\s

**Comment by musm** [comment]
try on latest
