### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on Windows

### ISSUE THREAD

**Issue by joshday** [JuliaIO/HDF5.jl#627]
I've run into an `EXCEPTION_ACCESS_VIOLATION` that I can reproduce on Windows 10, but not my Mac.  I'm unfortunately unable to share the file/code to reproduce it.

The problem is connected to `unsafe_wrap` (discovered through the assistance of @JeffBezanson) and I was able to get past the error by changing the keyword arg to `own=false` in the two functions below:

https://github.com/JuliaIO/HDF5.jl/blob/1d740136bf7225bd05e7a561fd8721c6ffedeeab/src/HDF5.jl#L1541-L1546

Does `own=false` likely cause a memory leak here?

**Comment by JeffBezanson** [comment]
I've been trying to read the libhdf5 docs, but it doesn't seem to make totally clear how this memory should be freed. Are we expected to call `malloc`, or is the memory freed when the file is closed, or something else? If we are supposed to call malloc, then on windows we might need to set up a finalizer that calls the `malloc` libhdf5 is using instead of what julia is using.

**Comment by kleinhenz** [comment]
I think that this memory is meant to be freed by calling [H5D_VLEN_RECLAIM](https://portal.hdfgroup.org/display/HDF5/H5D_VLEN_RECLAIM) so it looks to me like `own=true` is probably wrong.

**Comment by kleinhenz** [comment]
In the code for handling compound types I used
```
normalize_types(x::VariableArray) = copy(unsafe_wrap(Array, convert(Ptr{eltype(x)}, x.p), x.len, own=false))
```
so that the julia array is completely separate from the hdf5 allocated memory and then I call the reclaim function. I guess it should be done like this for all vlen types.

**Comment by simonbyrne** [comment]
Apparently it isn't safe to call `free` across shared library boundaries on Windows:
https://github.com/JuliaLang/julia/pull/7906#discussion_r26136825

**Comment by musm** [comment]
Is there anything we can do in that case to fix this ?

**Comment by simonbyrne** [comment]
The options are either to get HDF5 to use the Julia `Libc.malloc`, or just copy the data using `unsafe_string` (which is probably the easier option).

**Comment by musm** [comment]
Does anyone have repro for this?

**Comment by musm** [comment]
@kleinhenz  any chance you would like to open a PR with that change ? Seems sensible to make that change here
