### ISSUE TITLE
Type size mismatch when reading compound datatype

### ISSUE THREAD

**Issue by lunglehrt** [JuliaIO/HDF5.jl#634]
Dear developers,

I have experienced an error "_LoadError: AssertionError: Type sizes mismatch!_" when trying to read a complicated compound datatype containing a integers, reals, and string arrays produced by our simulation code. From what I could find out, this issue seems to be caused by the size of the HDF5.FixedArray{String,(1,),1} datatype not being consistent with the size of the string array in the HDF5 file.
In the attachment, I have provided a small example (a Python script to create the HDF5 file and a Julia script to read it) where the compound datatype just contains a string array. With Julia 1.4.2 and a freshly installed HDF5.jl, it produces the following output:

`ERROR: LoadError: AssertionError: Type sizes mismatch!
Stacktrace:
 [1] read(::HDF5Dataset, ::Type{Array{NamedTuple{(:name,),Tuple{HDF5.FixedArray{String,(1,),1}}},N} where N}) at /home/<username>/.julia/packages/HDF5/cvKpY/src/HDF5.jl:1490
 [2] read(::HDF5Dataset) at /home/<username>/.julia/packages/HDF5/cvKpY/src/HDF5.jl:1306
 [3] read(::HDF5File, ::String, ::Bool) at /home/<username>/.julia/packages/HDF5/cvKpY/src/HDF5.jl:1294
 [4] read(::HDF5File, ::String) at /home/<username>/.julia/packages/HDF5/cvKpY/src/HDF5.jl:1293
 [5] top-level scope at /home/<username>/tests/test_hdf5_jl_bug/read_file.jl:5
 [6] include(::Module, ::String) at ./Base.jl:377
 [7] exec_options(::Base.JLOptions) at ./client.jl:288
 [8] _start() at ./client.jl:484
in expression starting at /home/<username>/tests/test_hdf5_jl_bug/read_file.jl:5
`

I hope that this example helps to figure out the issue. Another observation I made is that with Julia 1.2 and an older version of HDF5.jl, the String arrays are recognized as UInt8 and the compound datatype can be read successfully (however, one needs to decode the String manually).

Thank you for this very useful library.

[example.zip](https://github.com/JuliaIO/HDF5.jl/files/5083647/example.zip)

**Comment by musm** [comment]
Is 
`np.dtype([('name',('S13',(1,)))])`
equivalent to
`np.dtype([('name','S13')])`

**Comment by lunglehrt** [comment]
Thank you very much for your fast reply.

No, the first line leads to a compound datatype with an **array of strings**
```
HDF5 "test.h5" {
GROUP "/" {
   DATASET "test" {
      DATATYPE  H5T_COMPOUND {
         H5T_ARRAY { [1] H5T_STRING {
            STRSIZE 13;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } } "name";
      }
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): {
            [ "Test string 1" ]
         },
      (1): {
            [ "Test string 2" ]
         }
      }
   }
}
}
```
and the second line results in a compound datatype with a **string**
```
HDF5 "test.h5" {
GROUP "/" {
   DATASET "test" {
      DATATYPE  H5T_COMPOUND {
         H5T_STRING {
            STRSIZE 13;
            STRPAD H5T_STR_NULLPAD;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         } "name";
      }
      DATASPACE  SIMPLE { ( 2 ) / ( 2 ) }
      DATA {
      (0): {
            "Test string 1"
         },
      (1): {
            "Test string 2"
         }
      }
   }
}
}
```
The first one cannot be parsed by HDF5.jl whereas the second one can.

Best regards
