### ISSUE TITLE
Testing impact to downstream packages

### ISSUE THREAD

**Issue by jmert** [JuliaIO/HDF5.jl#661]
In recent PRs (#655 and #657), I have tried to smooth over changes made by other PRs that impacted external ecosystem packages, namely by running MAT.jl and JLD.jl's tests and investigating failures. Some of them have been intended to be breaking (such as #632) and will clearly require accompanying changes in downstream packages, but others (like #631) are well-motivated fixes that nonetheless require follow-ups when used "in the wild" (e.g. JuliaIO/MAT.jl#142).

It might be useful to add a testing phase — chain-invoking MAT and JLD's own tests as a testset? a separate CI job? other? — which can protect against unintended breakages and/or clarify what intended changes will require deprecation methods or corresponding external work.

**Comment by musm** [comment]
That's a good idea. I wonder if anyone else has done anything similar?

**Comment by musm** [comment]
test-set dependencies and call `Pkg.test` on them?
