### ISSUE TITLE
mpio.jl test (in #master) fails with "Attempting to use an MPI routine before initializing MPICH" at NERSC

### ISSUE THREAD

**Issue by lyon-fnal** [JuliaIO/HDF5.jl#665]
Hi, I'm trying to run parallel HDF5 in Julia at NERSC. I'm using the #master version of HDF5.jl. I am not able to get the[ mpio.jl test](https://github.com/JuliaIO/HDF5.jl/blob/master/test/mpio.jl) to run successfully.  I'm running it in a batch job with MPI.  I get the "Attempting to use an MPI routine..." error right after the `println("A")` line below (e.g. I never see "B")...
```julia

let fileprop = p_create(HDF5.H5P_FILE_ACCESS)
    println("A")
    HDF5.h5p_set_fapl_mpio(fileprop, comm, info)
    println("B")
    h5comm, h5info = HDF5.h5p_get_fapl_mpio(fileprop)
    println("C")

    # check that the two communicators point to the same group
    if isdefined(MPI, :Comm_compare)  # requires recent MPI.jl version
        @test MPI.Comm_compare(comm, h5comm) === MPI.CONGRUENT
    end
end
```

Instrumenting the [mpio.jl file within the HDF5.jl package in src](https://github.com/JuliaIO/HDF5.jl/blob/master/src/mpio.jl) that I have checked out, the failure then occurs right after `println("CC")`

```julia
# Set MPIO properties in HDF5.
# Note: HDF5 creates a COPY of the comm and info objects.
function h5p_set_fapl_mpio(fapl_id, comm::MPI.Comm, info::MPI.Info)
    println("AA")
    h5comm = mpi_to_h5(comm)
    println("BB")
    h5info = mpi_to_h5(info)
    println("CC")
    h5p_set_fapl_mpio(fapl_id, h5comm, h5info)
    println("DD")
end
```

That is I see,
```
lyon@cori12:~/irmaAnalysis/concatHDF5> less slurm-xyz.out
A
AA
BB
CC
Attempting to use an MPI routine before initializing MPICH
```

I can run other MPI jobs without HDF5 just fine. 

Any ideas here? Thanks! -- Adam

**Comment by lyon-fnal** [comment]
The above was running at NERSC. It fails on my Mac too, and give a little more information (same instrumenting with `println` as above)...

```
A
A
A
AA
BB
CC
*** The MPI_Comm_dup() function was called before MPI_INIT was invoked.
```

```

**Comment by lyon-fnal** [comment]
Ok - well, I fixed the Mac problem by rebuilding HDF5.jl and MPI.jl and ensuring that they were using the same MPI libraries. Maybe that's my problem at NERSC. Looking...

**Comment by lyon-fnal** [comment]
Ok - never mind!! On NERSC I was building against the wrong HDF5 library. Now it works! 

Sorry for the noise!

**Comment by musm** [comment]
Great 
. I hope the master version of the MPI integration is a lot more convenient
