### ISSUE TITLE
Regression in typed `read`

### ISSUE THREAD

**Issue by jmert** [JuliaIO/HDF5.jl#669]
The following behavior to use a read statement like `read(dataset, Type)` has regressed for `String`s in current master versus v0.13.6:

With v0.13.6
```julia
(test) pkg> add HDF5@0.13.6
...

julia> using HDF5
[ Info: Precompiling HDF5 [f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f]

julia> h5open("test.h5", "w") do hfile
           hfile["dset"] = "string value"
       end
"string value"

julia> h5open("test.h5", "r") do hfile
           read(hfile["dset"], String)
       end
"string value"
```

Then on current master:
```julia
(test) pkg> add HDF5#master
...

julia> using HDF5
[ Info: Precompiling HDF5 [f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f]

julia> h5open("test.h5", "w") do hfile
           hfile["dset"] = "string value"
       end
"string value"

julia> h5open("test.h5", "r") do hfile
           read(hfile["dset"], String)
       end
ERROR: Type String does not have a definite size.
Stacktrace:
 [1] sizeof
   @ ./essentials.jl:457 [inlined]
 [2] read(::HDF5Dataset, ::Type{String})
   @ HDF5 ~/.julia/packages/HDF5/iXIFC/src/HDF5.jl:1324
...
```

**Comment by kleinhenz** [comment]
This is expected from #652 which made the meaning of `read(dset, T)` 'read dset into an array of type T where T is memory compatible with the hdf5 type (possible performing some conversion after the read). `String` is not memory compatible with any HDF5 types so this doesn't work (specifically `sizeof(String)` is not defined). 

Is the above example desired behavior? If the dataset is a string datatype then you can just use `read(dset)` and if it isn't a string datatype but you want to interpret it as a string then that custom logic needs to be implemented somewhere else. I guess I'm not exactly clear what the use case for `read(dset, String)` would be.

**Comment by musm** [comment]
Do we know what h5py does?

**Comment by jmert** [comment]
I was using that form for a variety of string values since `read(dataset, String)` type-inferred as a String value while `read(dataset)` did not.

One, I suppose that can be worked around with `read(dataset)::String`. Two, it appears I looked into the String case and then just assumed I was getting type-inferred results for all types, but it appears String is special-cased and unique. Trying other types only gets me `Any` in inferrence.

At the very least, it'd be another good thing to add to the deprecations.

**Comment by jmert** [comment]
Since my assumption that the second type argument was useful for type inference was wrong in general, I'm OK considering this issue a non-issue and closing it.

Maybe the only actionable issue is that the documentation should have an example of reading a non-trivial datatype since PR #652 made that possible in an easy way. (It looks like there are examples in both `test/compound.jl` and `test/custom.jl` that write in very similar ways, but they read back differently?)

**Comment by kleinhenz** [comment]
I think the return type annotation is the right way to deal with the inference. For the general method I think that it's expected that it won't be inferrable because the type must depend on the data.

The reason for the difference is that `test/compound.jl` is testing reading in a compound type as a named tuple. `test/custom.jl` is testing reading a compound type into a user defined struct. I agree that this would be good to add to the documentation.

**Comment by jmert** [comment]
I've been thinking about this for a couple of days, and while I now agree that "regression" isn't the correct assessment, I still think it'd be good to implement `read(::DatasetOrAttribute, ::Type{String})` here — I think there's an easy way to define the method without any duplication of effort.

Rather than this being a concern about my initially-incorrect assumption about type inferrence, I think the reason to support signatures like this is that it's the natural way to define a (de)serialization interface for custom types from/into HDF5 files. If you take a look at JuliaIO/MAT.jl#145, I've prototyped removing a couple of `read()` methods, but one that remains is for a custom `read(::DatasetOrAttribute, ::Type{MatlabString})` function to handle the peculiarities of MATLAB's (non)strings. With this new framework @kleinhenz created, there's now transparent support for a wide array of concrete (bits?) types (as evidenced by greatly simplifying Matlab's complex arrays!), but I assume there will still always be reason to do custom serialization; officially supporting that through specializations of `read(::DatasetOrAttribute, ::Type{T})` sounds like kind of an attractive option.

(If you agree with this assessment, another question is raised, though — should the method actually be defined not on `::DatasetOrAttribute` but instead `::Union{HDF5Group,HDF5Dataset,HDF5Attribute}` so that `Dict`-like (de)serialization that spans an entire group can be specialized upon? MAT.jl currently sets methods on a wider type, but in the PR to MAT.jl I'm proposing narrowing the type of the first argument to just `DatasetOrAttribute` to avoid method ambiguity problems.)

**Comment by kleinhenz** [comment]
I don't think it's necessary for this method to be defined on `::Union{HDF5Group, HDF5Dataset, HDF5Attributes}` in order to add methods which take an `HDF5Group` so I don't think the signature needs to be changed here. I do agree that having better support for serializing/deserializing objects which are mapped to groups not just datasets which be really nice though.
