### ISSUE TITLE
Parallel HDF5 is broken by commit d1e542a

### ISSUE THREAD

**Issue by lyon-fnal** [JuliaIO/HDF5.jl#683]
Hi - I'm not sure if you are doing a series of commits as a work in progress, but just so you know - commit d1e542a breaks loading HDF5 with MPI (to get parallel hdf5).  [mpio.jl](https://github.com/JuliaIO/HDF5.jl/blob/master/src/mpio.jl) uses `hdf5_prop_get_set` (see line 57). That dictionary was removed in commit d1e542a (was in HDF5.jl around line 2138).

The result of this change is that 
```
using MPI
using HDF5
``` 
spews a warning about the missing dictionary and it seems that one MPI rank that I make fails to do anything. 

I hope you're planning to update `mpio.jl` accordingly in a subsequent release. Let me know if you need help testing.

**Comment by jmert** [comment]
@lyon-fnal, could you please test #684?

**Comment by lyon-fnal** [comment]
Thanks! Trying it in a few minutes.

**Comment by lyon-fnal** [comment]
Parallel write test worked.
Parallel read test worked.

I think this is good. Thanks for making the fix!
