### ISSUE TITLE
Removing exists() for Base.haskey() is a breaking change

### ISSUE THREAD

**Issue by fergu** [JuliaIO/HDF5.jl#721]
Stumbled upon this since I switched to using the master branch over the version in the Julia repos to use the changes I submitted yesterday.

the `exists()` function was removed in PR #694. The reasoning makes perfect sense since it aligns better with the functionality one would expect from other Julia libraries. However, given that `exists()` has been the documented way to check if an object/group exists for a while now, would it be better to just pass `exists()` on to `haskey()`, perhaps with a printed warning that it's been deprecated and may be totally removed at some point, rather than jumping straight to removing it?

**Comment by jmert** [comment]
Looks like a mixture of #694 and #701 made the deprecation not work:
```
+[user@host:HDF5]$ julia --project --depwarn=yes
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.2 (2020-09-23)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> using HDF5

julia> hid = h5open("/tmp/test.h5", "w");

julia> exists(hid, "dne")
ERROR: UndefVarError: exists not defined
Stacktrace:
 [1] top-level scope at REPL[3]:1
 [2] run_repl(::REPL.AbstractREPL, ::Any) at /build/julia/src/julia-1.5.2/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288

julia> HDF5.exists(hid, "dne")
┌ Warning: `exists(parent::Union{File, Group, Dataset, Datatype, Attributes}, path::AbstractString)` is deprecated, use `Base.haskey(parent, path)` instead.
│   caller = top-level scope at REPL[4]:1
└ @ Core REPL[4]:1
false
```

That's easy enough to fix, though. Thanks for noticing this!

**Comment by musm** [comment]
Ah missed the export in `deprecations` it seems
