### ISSUE TITLE
Non-deterministic error: HDF5 is not properly installed.

### ISSUE THREAD

**Issue by tuckermcclure** [JuliaIO/HDF5.jl#734]
Over the past couple of days, I've been seeing issues with HDF5.jl intermittently in our CI builds. The error looks like this:

```
05-Nov-2020 19:43:58 | ERROR: LoadError: HDF5 is not properly installed. Please run Pkg.build("HDF5") and restart Julia.
-- | --
05-Nov-2020 19:43:58 | Stacktrace:
05-Nov-2020 19:43:58 | [1] error(::String, ::String) at ./error.jl:42
05-Nov-2020 19:43:58 | [2] top-level scope at /root/.julia/packages/HDF5/pAi1D/src/HDF5.jl:31
05-Nov-2020 19:43:58 | [3] include(::Module, ::String) at ./Base.jl:377
05-Nov-2020 19:43:58 | [4] top-level scope at none:2
05-Nov-2020 19:43:58 | [5] eval at ./boot.jl:331 [inlined]
05-Nov-2020 19:43:58 | [6] eval(::Expr) at ./client.jl:449
05-Nov-2020 19:43:58 | [7] top-level scope at ./none:3
05-Nov-2020 19:43:58 | in expression starting at /root/.julia/packages/HDF5/pAi1D/src/HDF5.jl:28
05-Nov-2020 19:43:59 | ERROR: LoadError: Failed to precompile HDF5 [f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f] to /root/.julia/compiled/v1.4/HDF5/L7Dga_pLoO2.ji.
```

This is not repeatable, and nobody's ever seen it happen locally to allow us to dig in.

Any ideas why?

**Comment by musm** [comment]
Interesting, do you know which versions?

**Comment by tuckermcclure** [comment]
From the Manifest.toml of the package that was active for the failure:

```
[[HDF5]]
deps = ["Blosc", "HDF5_jll", "Libdl", "Mmap", "Random"]
git-tree-sha1 = "7048678fa1970aaf867f3e99b90f3e85a9847124"
uuid = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
version = "0.13.2"

[[HDF5_jll]]
deps = ["Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "3dbc683172cb53428907485a4bb98a29d3874083"
uuid = "0234f1f7-429e-5d53-9886-15a909be8d59"
version = "1.10.5+6"
```

Julia is v1.4.1.

The VM is running Debian Buster, 64-bit.

**Comment by musm** [comment]
It may very well be a CI issue? We've had our CI very stable here.

**Comment by jmert** [comment]
On HDF5 v0.13.2, the error is emitted if the `deps/deps.jl` file doesn't exist: https://github.com/JuliaIO/HDF5.jl/blob/1d740136bf7225bd05e7a561fd8721c6ffedeeab/src/HDF5.jl#L28-L33

Can you check earlier in the logs for an error during either `Pkg.instantiate()` or similar?

**Comment by tuckermcclure** [comment]
Thanks @jmert. There is no output from the `instantiate` step, nor anything odd prior to the error I posted above.

Thanks @musm. I'll keep my eyes out for any other issues that might indicate a general CI issue.

I'm also trying a branch that explicitly runs `Pkg.build("HDF5")` after activating the project to see if that helps. I'm going to run this branch repeatedly a bunch of times. If the problem doesn't exist on my branch but does on the other branches in our repo, then perhaps this could be called a fix.

I'm wondering why that deps.jl file wouldn't be there...

**Comment by tuckermcclure** [comment]
After being an issue for a few days, this has mysteriously stopped being an issue. pointing to some other factor. Thanks for the info and help! I think we can probably close this ticket.
