### ISSUE TITLE
0.15 release tracker and discussion

### ISSUE THREAD

**Issue by musm** [JuliaIO/HDF5.jl#766]
Open for features for the 0.15

- [x] rename get_dims 
- [x] Remove v0.14  deprecations

Consider for next release:
- Export certain datatypes and prefix them with H5 ? (backtracking on our change to remove the HDF5 prefix). I'm not sure what's the right call for the long term. The main motivation is to be consistent with other IO packages in the Julia ecosystem. `CSV` uses `CSV.File`. Oddly, `JL2` uses `JLD2.JLDFile`. I haven't looked at other packages yet, but it is warranted.
- data marshaling of hsizet_t and Julia's native Int type: see e.g.: https://github.com/JuliaIO/HDF5.jl/blob/master/test/dataspace.jl#L4
    - Ideally, we could truncate them to `buf .% Int` for vector's although this ends up allocating a vector.

**Comment by musm** [comment]
Do we think it's ok to tag a v0.15 release soon? I'd like to get the relaxed libhdf5 requirements in a release and that would require a minor bump. A patch release for that would likely not be appropriate since it relaxes library version requirements and is not a bugfix.

**Comment by musm** [comment]
I'm not sure how appropriate it would be to remove v0.14 deprecations in that case. Presumably it should be ok, albiet the v0.14->v0.15 transition would be a quick release change.

**Comment by musm** [comment]
@jmert  Are we missing anything before making this release ?  I think I'd like to get in https://github.com/JuliaIO/HDF5.jl/pull/798 and then tag a release.  

Should we discuss 

> Export certain datatypes and prefix them with H5 ? (annoying but I think this is the right call for the long term)

Or do you prefer to save that for v0.16

**Comment by musm** [comment]
On my end I don't have anything pressing for v0.15, this I think we should go ahead with a release, unless you have any specific concerns?

**Comment by jmert** [comment]
I don't think there's anything else I'd like to see before a v0.15 release.
