### ISSUE TITLE
Deprecation errors on load

### ISSUE THREAD

**Issue by andrew-saydjari** [JuliaIO/HDF5.jl#784]
When using HDF5, I always get a long string of deprecation errors (possibly related to plots). Is this a known issue? Can I suppress some way? 

MacOS 11.0.1
Julia 1.4.2

WARNING: importing deprecated binding HDF5.HDF5Group into _hdf5_implementation.
WARNING: importing deprecated binding HDF5.HDF5Dataset into _hdf5_implementation.
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:162
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:162
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:166
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:166
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:176
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:179
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:181
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:184
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:186
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:189
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:203
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:207
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:211

  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:215
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:220
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:224
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:229
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:233
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:237
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:247
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:263
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:273
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:286
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:302
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:307
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:311
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:315
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:317
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:326
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:331
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:338
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:346
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:355
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:368
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:394
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:396
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:405
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:406
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:407
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:408
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:412
WARNING: HDF5.HDF5Dataset is deprecated, use HDF5.Dataset instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:418
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:425
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:432
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:441
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:462
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:464
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:482
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:484
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:497
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:503
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:507
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:517
WARNING: HDF5.HDF5Group is deprecated, use HDF5.Group instead.
  likely near /Users/aksaydjari/.julia/packages/Plots/uCh2y/src/backends/hdf5.jl:536

**Comment by musm** [comment]
I think the only solution on julia 1.4 is to run it with the flag ``` --depwarn=false```

**Comment by musm** [comment]
Alternatively, and a better idea, is we  should update Plots.jl to the new syntax.

**Comment by musm** [comment]
Actually https://github.com/JuliaPlots/Plots.jl/pull/3175 took care of that, if that commit is already tagged you might need to update your packages or wait for the tag.
