### ISSUE TITLE
The time to close a .h5 file increases if you repeatedly open and close it

### ISSUE THREAD

**Issue by daniel-thom** [JuliaIO/HDF5.jl#801]
I narrowed down a performance problem to HDF5.jl. The time to close a .h5 file linearly increases with the number of times open/read/close are called. This is obviously not the ideal way to use HDF5, but there does appear to be an issue here. I ran the exact same test on Python/h5py and did not observe the problem.

Minimal example: write 10 floats to a .h5 file and then read the values 100,000 times, opening and closing the file each time.

Total time for Julia: 778s
Total time for Python: 41s

![image](https://user-images.githubusercontent.com/9037606/104365745-9b960700-54d5-11eb-9486-a5d4e4520273.png)
![image](https://user-images.githubusercontent.com/9037606/104367498-26780100-54d8-11eb-8b3c-1b0edf87a382.png)

Code to reproduce:

```julia
using HDF5

function perform_read(io, filename)
    t1 = time()
    file = HDF5.h5open(filename, "r")
    t2 = time()
    data = file["data"][:]
    t3 = time()
    close(file)
    t4 = time()
    t_open = t2 - t1
    t_read = t3 - t2
    t_close = t4 - t3
    println(io, "$t_open,$t_read,$t_close")
end

function run()
    filename = "ones.h5"
    h5open(filename, "w") do file
        file["data"] = ones(10)
    end

    start = time()
    open("julia_timings.csv", "w") do io
        println(io, "open,read,close")
        for i in 1:100000
            perform_read(io, filename)
        end
    end

    duration = time() - start
    println("duration = $duration")
end

run()
```

```python
import time

import h5py


def perform_read(filename, f_out):
    t1 = time.time()
    file = h5py.File(filename, "r")
    t2 = time.time()
    data = file["data"][:]
    t3 = time.time()
    file.close()
    t4 = time.time()
    t_open = t2 - t1
    t_read = t3 - t2
    t_close = t4 - t3
    f_out.write(f"{t_open},{t_read},{t_close}\n")


def main():
    start = time.time()
    filename = "ones.h5"

    with open("python_timings.csv", "w") as f_out:
        f_out.write("open,read,close\n")
        for _ in range(100000):
            perform_read(filename, f_out)

    duration = time.time() - start
    print(f"duration = {duration}")


if __name__ == "__main__":
    main()
```

Versions:
System: macOS Catalina
julia v1.5.3
HDF5 v0.14.3
Python v3.7.9
h5py v3.1.0

**Comment by jmert** [comment]
Appears to already be fixed on HDF5 master — just need a new release:
![open_close_read](https://user-images.githubusercontent.com/2965436/104367934-13b5fa00-54e1-11eb-9817-d7ddf26d95ba.png)

**Comment by daniel-thom** [comment]
Confirmed on my side. Finished in 17s with master. Do you know when you might have a new release?

Thanks

**Comment by jmert** [comment]
It should be soon — discussion happening in https://github.com/JuliaIO/HDF5.jl/issues/766.

**Comment by musm** [comment]
Yep it should be soon just some final minor things to get in before tagging a release.

**Comment by daniel-thom** [comment]
Great, thanks.
