### ISSUE TITLE
v0.16 tracker and discussion

### ISSUE THREAD

**Issue by musm** [JuliaIO/HDF5.jl#802]
Tasks:

- Clean-up the methods: 
```
export
@read, @write,
h5open, h5read, h5write, h5rewrite, h5writeattr, h5readattr,
```

**Comment by musm** [comment]
@simonbyrne  was there anything else you planned for the v0.16 release? 
Otherwise, we might want to finalize minor cleanup tasks, if there are any and make the release.

**Comment by simonbyrne** [comment]
I had some vague plans to refactor the type conversions, but don't have time to spend on it at the moment. Maybe next release.

**Comment by musm** [comment]
Sounds good, thanks for the input.
