### ISSUE TITLE
HDF5 0.15.0 is not backwards compatible with JULIA_HDF5_LIBRARY_PATH

### ISSUE THREAD

**Issue by david-macmahon** [JuliaIO/HDF5.jl#803]
To use system-provided HDF5 libraries with HDF5.jl < 0.15.0, one had to set the environment variable `JULIA_HDF5_LIBRARY_PATH` to point to the system's HDF5 libraries.  Starting with version 0.15.0 (commit a06231c) the name of the environment variable was changed to `JULIA_HDF5_PATH`.  Comments in `deps/build.jl` imply that the "legacy" variable is still supported:

```julia
libpath = get(ENV, "JULIA_HDF5_LIBRARY_PATH", nothing)  # legacy env variable for compatibility
libpath = get(ENV, "JULIA_HDF5_PATH", nothing)
```

but the ordering of these statements renders the first one moot.  I think the intent is to accept the old name if the new name is not defined, which could look something like this:

```julia
libpath = get(ENV, "JULIA_HDF5_PATH",
          get(ENV, "JULIA_HDF5_LIBRARY_PATH", nothing))  # legacy env variable for compatibility
```

One more things (which maybe should be a separate issue?): `docs/src/index.md`  has not been updated to reflect this new variable name (but the top level `README.md` file has been updated).

**Comment by musm** [comment]
Thanks for filing the bug report, I'll  fix this later on and get a new patch release ASAP.
