### ISSUE TITLE
Avoid creating `cfunction` closures

### ISSUE THREAD

**Issue by vchuravy** [JuliaIO/HDF5.jl#813]
On [PowerPC](https://github.com/JuliaLang/julia/issues/32154) and [AArch64](https://github.com/JuliaLang/julia/issues/27174) the creation of cfunction closures like in: 

https://github.com/JuliaIO/HDF5.jl/blob/0d13166daf71a706329d06585606872bd9263b9c/src/api_helpers.jl#L145-L146

is currently not supported. 

Looking at https://support.hdfgroup.org/HDF5/doc/RM/RM_H5L.html it seems that the last argument is a custom data, so
one can use that to pass in a shallow wrapper around `f` and have a static `cfunction` that calls `f` through the obj_data.
As an example of something similar see https://github.com/JuliaParallel/UCX.jl/blob/b12064de3b60daa03466a1c2b6ee9d431c289eb1/src/UCX.jl#L321-L326

cc: @jpsamaroo who run into this while trying to use HDF5.jl on a PowerPC cluster.

**Comment by musm** [comment]
https://github.com/JuliaIO/HDF5.jl/pull/812

**Comment by musm** [comment]
We will push a fix for this soon, just finalizing the PR.
