### ISSUE TITLE
Fatal error in Julia 1.4

### ISSUE THREAD

**Issue by jd-lara** [JuliaIO/HDF5.jl#814]
After the latest update we started picking up a fatal error in the Julia 1.4 CI. Here is the log file 
https://github.com/NREL-SIIP/PowerSimulations.jl/runs/1880992442#step:5:478

This issue won't appear in Julia 1.5.2 or 1.5.3.

**Comment by musm** [comment]
Maybe related to https://github.com/JuliaIO/HDF5.jl/pull/812 ?

I'm not sure how exactly the error is triggered.
```
julia: /buildworker/worker/package_linux64/build/src/llvm-late-gc-lowering.cpp:773: int LateLowerGCFrame::Number(State&, llvm::Value*): Assertion `isSpecialPtr(V->getType())' failed.
```

You wouldn't happen to a have a reduced test case?

**Comment by jd-lara** [comment]
I can't reproduce locally with a small case. Maybe adding 1.4 to the CI can trigger the issue.

**Comment by musm** [comment]
Great, I was able to trigger this on 1.4
