### ISSUE TITLE
Problem with adding the package

### ISSUE THREAD

**Issue by AmberKamman** [JuliaIO/HDF5.jl#820]
I tried to install this package on Windows 10, but I got this error message. Could someone explain the problem and tell me what I should do? Julia version 1.0.5 (2019-09-09)

(v1.0) pkg> add HDF5
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package HDF5 [f67ccb44]:
 HDF5 [f67ccb44] log:
 ├─possible versions are: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5, 0.13.0-0.13.7, 0.14.0-0.14.3, 0.15.0-0.15.4] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5, 0.13.0-0.13.7, 0.14.0-0.14.3, 0.15.0-0.15.4]
 ├─restricted by compatibility requirements with Blosc [a74b3585] to versions: [0.13.1-0.13.7, 0.14.0-0.14.3, 0.15.0-0.15.4] or uninstalled, leaving only versions: [0.13.1-0.13.7, 0.14.0-0.14.3, 0.15.0-0.15.4]
 │ └─Blosc [a74b3585] log:
 │   ├─possible versions are: [0.5.1, 0.6.0, 0.7.0] or uninstalled
 │   └─restricted to versions 0.6.0 by an explicit requirement, leaving only versions 0.6.0
 └─restricted by julia compatibility requirements to versions: [0.9.4-0.9.5, 0.10.0-0.10.4, 0.11.0-0.11.1, 0.12.0-0.12.5] or uninstalled — no versions left

**Comment by musm** [comment]
Looks like you are on LTS, which is rather outdated at this point. Any chance you would consider upgrading to the current stable release version https://julialang.org/downloads/

**Comment by AmberKamman** [comment]
I have tried and I can now add the package. Thank you!
