### ISSUE TITLE
How to read attributes 

### ISSUE THREAD

**Issue by feanor12** [JuliaIO/HDF5.jl#824]
The documentation is missing a section which shows how to efficiently read attributes from a file.
In may case I often need to explore hdf5 files, which store the name of the dataset as an attribute.

Is there a better way of doing this?
```julia
data = h5open(filename)
dataset= read(data["node/values"])
node_attributes = attributes(node)
dataset_name = read(node_attributes["name"])
```

To quickly find out the attributes values an extended show function could also be useful.

**Comment by musm** [comment]
With https://github.com/JuliaIO/HDF5.jl/pull/839 you can now use the `[]` syntax instead of having to call `read` explicitly. Is that what you were hoping for? Note that PR is not on a tagged release yet.
