### ISSUE TITLE
`create_group` probably should throw a custom exception

### ISSUE THREAD

**Issue by ForceBru** [JuliaIO/HDF5.jl#829]
Right now there's a call to `error`:

https://github.com/JuliaIO/HDF5.jl/blob/ef228d57be54d2082a6a7581895fd4becbfe3714/src/HDF5.jl#L723

In my code, I'd like to overwrite the data in a group _if it already exists_, but currently that would make me catch a `ErrorException`:

```julia
try
    create_group(fid, grp_name)
catch e
   if e isa ErrorException
      @warn "Replacing data!"
   else
      throw(e)
   end
end
```

However, this doesn't tell me anything about where or why the `ErrorException` occurred: maybe the file was corrupt, maybe it got randomly deleted on disk - I can't tell.

It would be nice to have a _type_ of exception that would explain what caused it and let me decide how to handle it. Something like this:

```julia
try
    create_group(fid, grp_name)
catch e
   if e isa GroupExistsException
      @warn "Replacing data!"
   else
      throw(e)
   end
end
```

**Comment by musm** [comment]
I think in your use case it would be better to first check the existence of the key, instead of relying on capturing an exception.

**Comment by musm** [comment]
I'm not opposed to creating and using a custom `H5Exception <: Exception`, I'm just not convinced we need to have custom exceptions for group errors e.g. `H5GroupException` seems too redundant.

**Comment by simonbyrne** [comment]
The manual error is a bit odd, as it isn't done for other functions (which typically return a `H5Error`), and it requires an extra `haskey(parent, path)` check.
