### ISSUE TITLE
create_attribute fail

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [JuliaIO/HDF5.jl#836]
I get the error below
`MethodError: no method matching create_attribute(::HDF5.Dataset, ::String, ::Type{Int64}, ::HDF5.Dataspace)`

but I find the code below in `HDF5.jl`

```julia
function create_attribute(parent::Union{File,Object}, name::AbstractString, dtype::Datatype, dspace::Dataspace)
    attrid = h5a_create(checkvalid(parent), name, dtype, dspace, _attr_properties(name), H5P_DEFAULT)
    return Attribute(attrid, file(parent))
end
```

**Comment by jmert** [comment]
The third argument in your call is `::Type{Int64}`, but the signature requires a `::HDF5.Datatype`. You presumably want to pass `datatype(Int64)` rather than `Int64`.

**Comment by Xinyu-Wu-0000** [comment]
> The third argument in your call is `::Type{Int64}`, but the signature requires a `::HDF5.Datatype`. You presumably want to pass `datatype(Int64)` rather than `Int64`.

Thank you a lot!
