### ISSUE TITLE
create_attribute fail to write value

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [JuliaIO/HDF5.jl#837]
![image](https://user-images.githubusercontent.com/57612792/120203187-057f3500-c25a-11eb-8195-dc5ef546d7d6.png)

**Comment by Xinyu-Wu-0000** [comment]
The `create_attribute` function didn't write the "Int" to the `type_name` attribute, but the `write` function did.

**Comment by simonbyrne** [comment]
`create_attribute` doesn't write anything. It's probably easier to use the `Attributes` object:
```
Attributes(f["object"])["type_name"] = "Int"
```
