### ISSUE TITLE
Finalizing correctly when using MPI

### ISSUE THREAD

**Issue by calebwin** [JuliaIO/HDF5.jl#852]
In the [MPI example](https://github.com/JuliaIO/HDF5.jl/blob/master/test/mpio.jl), there is code like this:

```
# we need to close HDF5 and finalize the info object before finalizing MPI
finalize(info)
HDF5.API.h5_close()

MPI.Barrier(MPI.COMM_WORLD)

MPI.Finalize()
```

So is this required now for correct usage of HDF5 with MPI?

**Comment by simonbyrne** [comment]
No, it is not.
