### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by IanButterworth** [JuliaIO/HDF5.jl#856]
I'd appreciate getting #855 out. 

I don't know whether the recent changes are patch or minor?

**Comment by musm** [comment]
Recent changes on master need a minor release, but I need to get in a few other PRs before that minor release is out. 

I can backport that PR to v0.15 branch and make a patch release

**Comment by IanButterworth** [comment]
Sounds good. Thanks

**Comment by musm** [comment]
closed by @JuliaRegistrator register()
