### ISSUE TITLE
Read all attributes into a dictionary (or structure)

### ISSUE THREAD

**Issue by jpmorr** [JuliaIO/HDF5.jl#857]
I'm learning Julia at the moment, coming from a python background, and one of the most frequent things I do is read HDF5 data files using `h5py`.

In `h5py`, it's really easy to read all attributes into a dictionary, getting all of the keys and values at once: 
````
    file_attributes = dict(temp.get(group_1').attrs.items())
````

Is there an equally simple way of doing this in `HDF5.jl` of would I need to do some sort of list comprehension or for loop to achieve something similar? Calling `Dict(attributes(group_1))` thorws an error:
````
ERROR: ArgumentError: Dict(kv): kv needs to be an iterator of tuples or pairs
Stacktrace:
 [1] Dict(kv::HDF5.Attributes)
   @ Base .\dict.jl:132
 [2] top-level scope
   @ REPL[53]:1

caused by: MethodError: no method matching iterate(::HDF5.Attributes)
````

**Comment by jpmorr** [comment]
I think what's mentioned in this thread may be what I'm looking to do: https://github.com/JuliaIO/HDF5.jl/issues/815#issuecomment-778319731

**Comment by simonbyrne** [comment]
The following works with #948:
```
julia> using HDF5

julia> filename = tempname();

julia> f = h5open(filename, "w");

julia> write_attribute(f, "a", 2)

julia> Dict(attrs(f))
Dict{String, Any} with 1 entry:
  "a" => 2
```
