### ISSUE TITLE
With #839 you can now use the `[]` syntax instead of having to call `read` explicitly.

### ISSUE THREAD

**Issue by jpmorr** [JuliaIO/HDF5.jl#858]
With https://github.com/JuliaIO/HDF5.jl/pull/839 you can now use the `[]` syntax instead of having to call `read` explicitly.
```
node_attributes["name"][]
```
Is that what you were hoping for? Note that PR is not on a tagged release yet.

_Originally posted by @musm in https://github.com/JuliaIO/HDF5.jl/issues/824#issuecomment-862060195_

This doesn't seem to be working for me. If I read an attribute:
````
julia> attrs = attributes(timestep_data_group["System"])
julia> read(attrs["energy"])
0.0
````
but if I try this new method:
````
julia> attrs["energy"][]
ERROR: MethodError: no method matching getindex(::HDF5.Attribute)
Stacktrace:
 [1] top-level scope
   @ REPL[69]:1
````

Could this be a package version issue? I'm using `HDF5 v0.15.5`.

**Comment by musm** [comment]
That syntax is only available on master at the moment.

**Comment by jpmorr** [comment]
Right, OK, missed that part. That would explain it. Thanks.
