### ISSUE TITLE
create_dset triggers race condition

### ISSUE THREAD

**Issue by tbenst** [JuliaIO/HDF5.jl#862]
I believe that `create_dset` may trigger a race condition between Julia and the underlying HDF5 library. I was able to create a reproducible example using [H5Sparse.jl](https://github.com/severinson/H5Sparse.jl/issues/4), and I've subsequently rewritten the code such that the bug can be reproduced reliably with just HDF5.jl.

Note that only the main process/thread is ever accessing the hdf5 dataset. However, this particular access pattern within a Task seems critical for triggering the error, as does the explicit call to `create_group`.

```julia
using HDF5
import Base.Threads: @threads
function write_n_datasets(h5path, n, channel, blocker, type=:H5)
    h5 = h5open(h5path, "w")
    while n > 0
        @assert Threads.threadid() == 1 # we only access from the master thread
        dset_name, data = take!(channel)
        println("take $n")
        take!(blocker)
        if type == :H5
            h5[dset_name] = data
        elseif type == :create_group
            group = create_group(h5, dset_name)
            group[dset_name] = data
        elseif type == :create_dset
            group = create_group(h5, dset_name)
            create_dataset(
                group, "data", 
                eltype(data), 
                ((length(data),), (-1,)),
                chunk=HDF5.heuristic_chunk(data),
                blosc=5)[1:length(data)] = data
        elseif type == :simple_create_dset
            group = create_group(h5, dset_name)
            create_dataset(group, "data", data)
        end
        n -= 1
    end
    h5
end

function test(type=:H5, n=10, N=512*512*300)
    to_write = Channel(Inf)
    blocker = Channel(5)
    h5_path = tempname()*".h5"
    isfile(h5_path) ? rm(h5_path) : ()
    @threads for i in 1:n
        @async begin
            put!(blocker, i)
            println("start $i")
            data = collect(rand(N,1) .> 0.9)
            if type == :H5
                put!(to_write, "$i" => data)
            elseif type == :create_group
                put!(to_write, "$i" => data)
            elseif type == :create_dset
                data = reshape(data, N)
                put!(to_write, "$i" => data)
            elseif type == :simple_create_dset
                data = reshape(data, N)
                put!(to_write, "$i" => data)
            else
                error("bad type")
            end
            println("put $i")
        end
    end
    println("call write")
    h5 = write_n_datasets(h5_path, n, to_write, blocker, type)

    @show keys(h5)
    close(h5)
    rm(h5_path)
    println("succeeded")
end

test(:H5, 10) # always works
test(:H5, 50) # always works
# test(:H5, 500) # takes a long time, but works
test(:create_group, 100) # no error
test(:create_dset, 10) # no error
# test(:create_dset, 100) # usually errors
test(:simple_create_dset, 5) # usually succeeds
test(:simple_create_dset, 10) # sometimes errors
test(:simple_create_dset, 100) # usually errors

```

Edit: to show that this isn't a multi-threading issue, I added a `@assert` to the code.

**Comment by tbenst** [comment]
Note that unlike in https://github.com/JuliaIO/HDF5.jl/issues/860, we are not using any concurrency to access the underlying `HDF5.File`. If instead, we replace this code to use `@distributed` for the producers and `RemoteChannel` for the single threaded-consumer, then the code does not error: https://github.com/severinson/H5Sparse.jl/issues/4#issuecomment-900132673.

Nonetheless, something about this is breaking...perhaps a bug related to shared memory..?

**Comment by simonbyrne** [comment]
I wasn't able to reproduce this on either the latest release or master (note that on master you'll need to manually add `]filters/H5Zblosc`). There has been a new HDF5_jll release since then (1.12.1) which may have fixed it.

If you see it again can you include your Manifest.toml (so we know exactly what versions), your Julia version and OS, as well as the full stack trace.
