### ISSUE TITLE
"Problem" with v0.15.6

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaIO/HDF5.jl#866]
I got really excited seeing `v0.15.6` mentioning #782 in its [release notes](https://github.com/JuliaIO/HDF5.jl/releases/tag/v0.15.6). :rocket:

Doing some testing, I noticed that the release was actually done from the `release-0.15` branch, which essentially only contains #855. Most changes mentioned in the release notes haven't been released (https://github.com/JuliaIO/HDF5.jl/compare/v0.15.6...master).

Assuming #782 is a [non-breaking change](https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0), could you please consider adding another `v0.15` release? This way `v0.16` could still be the big release you were aiming for in https://github.com/JuliaIO/HDF5.jl/pull/782#issuecomment-873608806.

**Comment by musm** [comment]
Sure, we can do that, although I think it would still have to be v0.16 since it's technically a feature according to semver.
