### ISSUE TITLE
HDF5Plugins.jl: lz4, zstd, and bzip2 filter support

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#874]
I started a package over at https://github.com/JuliaIO/HDF5Plugins.jl to implement a few additional compression plugins for HDF5. The plugins themselves are implemented in Julia similar to the Blosc plugin in this package. I've implemented the low level interface, and I'm starting to work on the high level interface.

Should we considering merging that code into HDF5.jl proper or should we consider spinning the Blosc plugin out (and perhaps upgrading it to Blosc 2)?

**Comment by musm** [comment]
Looks good. Yeah I think we should definitely merge these here to make using them simple.  Take a look at https://github.com/JuliaIO/HDF5.jl/tree/master/src/filters  and the change that made in https://github.com/JuliaIO/HDF5.jl/pull/847 which simplified filter support substantially.

> 
(and perhaps upgrading it to Blosc 2)?

Agreed, I thought Blosc.jl was using the blosc2 library internally under the hood, but just checking it doesn't seem that that is true.  I found this https://github.com/waralex/Blosc2.jl library which wraps `Blosc2.jl`.

**Comment by mkitti** [comment]
Blosc2 is actually fairly recent. [Release 2.0.0](https://github.com/Blosc/c-blosc2/releases/tag/v2.0.0) was only on Jun 28, 2021.

One complication is that additional licensing is required to include the plugins since the original C code for the plugins (which I ported to Julia) come under various licenses.

Currently, I'm targeting the discrete package, HDF5Plugins.jl against the 0.15 branch with some consideration for the 0.16 branch. How about we keep it separate for the 0.15 branch, and consider merging it into the 0.16 branch?

**Comment by musm** [comment]
closed by https://github.com/JuliaIO/HDF5.jl/pull/880
