### ISSUE TITLE
Generalize chunk API beyond Vector{UInt8}

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#876]
Currently the chunk API has a `chunk_bytes` argument restricted to `Vector{UInt8}`.

https://github.com/JuliaIO/HDF5.jl/blob/c6dd9a7a94d6e31b8a1b7eeece9895463ffc1f8f/src/HDF5.jl#L1342-L1364

However, these bytes could easily be certain kinds of `SubArrays`. For example, `Base.FastContiguousSubArray` should work with the underlying code.  Perhaps the practical definition is where `pointer` is applicable.

SIMD.jl has a definition of `FastContiguousArray` that may be applicable here:
https://github.com/eschnett/SIMD.jl/blob/ace8eb1543e43f2b6fe834e00daf658bd5cabfbd/src/arrayops.jl#L35-L44

The other thought would be just allowing any `AbstractVector{UInt8}` and letting `ccall` throw the error. The user would then have to use their judgement if certain arrays will work.

**Comment by musm** [comment]
I agree it's likely unnecessarily restrictive.  `AbstractVector{UInt8}`  is probably the correct change here.

**Comment by mkitti** [comment]
OK, I'll develop a PR using for changing everything to `AbstractVector{UInt8}`.
