### ISSUE TITLE
Nightly CI runs are running for 6 hours and then timing out

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#877]
I noticed that the nightly CI runs are running for 6 hours and then timing out. The last run to succeed was for https://github.com/JuliaIO/HDF5.jl/pull/865/commits/24d9480b3de757318160dd5056fd270b5e71d42f . Every nightly CI run since https://github.com/JuliaIO/HDF5.jl/pull/865/commits/5c2055bb171bfd96f50ea831d6fdceee9e66559e has failed.

I suggest that we either disable the nightly CI runs or add a timeout while we investigate the issue.

**Comment by musm** [comment]
closed by https://github.com/JuliaIO/HDF5.jl/pull/878
