### ISSUE TITLE
0.16 changes `filter` keyword to `filters`

### ISSUE THREAD

**Issue by david-macmahon** [JuliaIO/HDF5.jl#884]
It looks like the `filter` keyword was changed to `filters` in 1c2ccb5.  Is this is an intentional or inadvertent breaking change from 0.15?

**Comment by texadactyl** [comment]
I wonder if "filter" is the intended keyword and "filters" is simply being ignored .
It's hard to tell considering the lack of filter coverage in the documentation.

**Comment by mkitti** [comment]
I think that was quite an intentional change by @simonbyrne . That's why the coming version is 0.16 and not 0.15.8

**Comment by musm** [comment]
I think the idea was that since you can pass in a  series of   compression filters, it would make sense to change the keyword argument to `filters`. 

I wonder if there's a style guide recommendation here whether to prefer the plural or singular. Since you can pass in a single filter `filters=Filters.Deflate(3)` or a list as in `filters=[Filters.Shuffle(), Filters.Deflate(3)]`.

**Comment by mkitti** [comment]
Would it be worth enabling a backwards compatible filter keyword that just uses the the new infrastructure? So `filter=x` just translated to `filters=[x]`?

**Comment by musm** [comment]
Yes that's my plan, but like to first confirm we are sticking to the `filters` name.  I'll try to dig around to see if there's a style guide suggestion on this.  I don't have a strong preference on whether the singular or plural makes sense. For the singular case, you can think of passing in the list of filters as a single object (a single list). In that way the singlar could be argued to also make as much sense as the plural.

**Comment by david-macmahon** [comment]
Since one can pass `Tuple{Int}` to employ a single filter or `Tuple{Tuple{Integer}}` to create a composite filter from a sequence of filters, there will always be singular/plural mismatch potential: either `<singular_keyword>=<plural_filter_specs>` or `<plural_keyword>=<singular_filter_spec>`.

I think the singular keyword `filter` is preferable (less unpreferable?) because one can think of multiple filters applied in sequence as forming a single composite filter.

I suppose we could get really pedantic and force the users to use the singular `filter` keyword for a `Tuple{Integer}` singular filter specification and the `filters` keyword for a `Tuple{Tuple{Integer}}` plural filter specification.  But that seems overly detailed IMHO.

**Comment by musm** [comment]
@david-macmahon  I'm also in favor or your logic, and was leaning towards that. I'll go ahead and make a PR with the changes tonight.

**Comment by musm** [comment]
Come to rethink things I felt that it would be more appropriate to keep the change as `filters` much of libhdf5's documentation refers to this argument by `filters` as well. Thus I've instead added a deprecation for the `filter` keyword argument.
