### ISSUE TITLE
Segmentation fault in building HDF5 in project

### ISSUE THREAD

**Issue by Chiil** [JuliaIO/HDF5.jl#929]
Recently, my HDF5 fails to build while running `build` from the Julia package manager. I do not know how to solve this problem, but I get the following error message:

```
    Building HDF5 ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/36df177c1ce5f399a8de959e5f4b75216fe6c834/build.log`
ERROR: Error building `HDF5`: 

signal (11): Segmentation fault: 11
in expression starting at /Users/chiel/.julia/packages/HDF5/THb0i/deps/build.jl:8

signal (4): Illegal instruction: 4
in expression starting at /Users/chiel/.julia/packages/HDF5/THb0i/deps/build.jl:8
```

On line 8 of `build.jl` is the statement
```
new_contents = if libpath === nothing
```

I don't know whether the problem is on the HDF5 side or mine, but I am stuck with this for a few weeks now and have no idea how to solve it. I use a system provided MPI-enabled HDF5. My project is [MicroHH.jl](https://github.com/Chiil/MicroHH.jl)

**Comment by Chiil** [comment]
I discovered that my issues are related to `MPI` not being loaded at the moment `build` is triggered. Running a `using MPI` before upgrading the project solves my problem.

**Comment by musm** [comment]
Glad to hear that was the issue

**Comment by Chiil** [comment]
I do not know how to solve this, but it might be good to let the build script load MPI in case the system provided HDF5 library has MPI enabled. The error is a little bit obscure as I do not understand how an `if` statement would trigger a illegal instruction.

**Comment by musm** [comment]
>  I do not know how to solve this, but it might be good to let the build script load MPI in case the system provided HDF5 library has MPI enabled. The error is a little bit obscure as I do not understand how an if statement would trigger a illegal instruction.

Loading MPI automatically if  an  MPI enabled HDF5 library is detected doesn't sound unreasonable, but I'm not 100% sure we should auto-load packages without prompting users?  

CC @jipolanco  as he has worked on the MPI interface. Wondering if he has any thoughts on this.

**Comment by Chiil** [comment]
Same error as with the HDF5 update:
```
julia> using Libdl

julia> libpath = ENV["JULIA_HDF5_PATH"]  # assuming "$libpath/libhdf5.so" exists

"/usr/local"

julia> libhdf5 = find_library("libhdf5", [libpath]) # returns "", as if it didn't find a working libhdf5.so

signal (11): Segmentation fault: 11
in expression starting at none:0

signal (4): Illegal instruction: 4
in expression starting at none:0
Illegal instruction: 4
```

**Comment by jipolanco** [comment]
Thanks, then I guess it's a different issue.

> Loading MPI automatically if an MPI enabled HDF5 library is detected doesn't sound unreasonable, but I'm not 100% sure we should auto-load packages without prompting users?

Maybe I'm misunderstanding, but the thing is, we can't detect an MPI enabled HDF5 library if we're unable to load libhdf5 in the first place...

In principle I'd be against loading MPI automatically at build time, since the result would depend on whether MPI.jl is in the current Julia environment, making things quite unpredictable to the user. I'd rather add an entry to the docs ("known issues"?) explicitly describing the issue and the workaround found by @Chiil.

**Comment by Chiil** [comment]
It seems your finding is close to the true problem. Why would `find_library` throw a segfault? Your test has one minor issue, and that is that the library is in the `/lib` folder of the `ENV["JULIA_HDF5_PATH"]` and not in the folder itself.

**Comment by jipolanco** [comment]
> Your test has one minor issue, and that is that the library is in the `/lib` folder of the `ENV["JULIA_HDF5_PATH"]` and not in the folder itself.

Actually, the library is allowed to be in `ENV["JULIA_HDF5_PATH"]` itself (even though the docs don't say this...):

https://github.com/JuliaIO/HDF5.jl/blob/b862c843e58716fcc731382df87e0224623211be/deps/build.jl#L19

> But if we could find out what goes wrong in `find_library`, the problem could be solved hopefully.

I think `find_library` tries to open the found libraries using `dlopen`. I'd guess this is where the segfault is thrown. You can try:

```julia
lib = dlopen("/usr/local/lib/libhdf5.so")
```

**Comment by Chiil** [comment]
`lib = dlopen("/usr/local/lib/libhdf5.dylib")` works without crash

**Comment by jipolanco** [comment]
Now I think I'm able to reproduce the issue. In my tests, the segfault actually happens at `dlclose(lib)`.

Apparently, passing `RTLD_NODELETE` to `dlopen` works around the issue. I'll push a PR with this workaround.
