### ISSUE TITLE
h5p_set_meta_block_size(..) duplicated in code

### ISSUE THREAD

**Issue by NicholasWMRitchie** [JuliaIO/HDF5.jl#936]
The definition for the api function `h5p_set_meta_block_size(fapl_id, size)` is duplicated on lines 2776 and 2831.

**Comment by musm** [comment]
Good catch, easy fix. Will push later today.

**Comment by mkitti** [comment]
My fault. Will you push soon?

**Comment by musm** [comment]
Feel free to push the fix!
