### ISSUE TITLE
how to copy the file structure of a hdf5 file

### ISSUE THREAD

**Issue by kongdd** [JuliaIO/HDF5.jl#941]
For a beginer user, it is hard to define the file structure.
Any idea how to copy the file structure of a hdf5 file?
![image](https://user-images.githubusercontent.com/9815742/169197019-5aeaa699-3e22-4ce7-b84b-e48c9d12e929.png)

**Comment by mkitti** [comment]
Sorry for the delay. Where would you like to copy the tree structure to? There is no "file structure". The entire tree is contained within a single file.

**Comment by kongdd** [comment]
thank u
