### ISSUE TITLE
Summer maintainership?

### ISSUE THREAD

**Issue by mkitti** [JuliaIO/HDF5.jl#991]
Hi @musm,

Would you mind if I moved forward on #979 , #982, #983, #984, and #989 next week? I notice that your Github activity has a lull over the summer.

-Mark

**Comment by musm** [comment]
Sorry I've been on vacation last few weeks and just starting to catch up on emails.

**Comment by mkitti** [comment]
No worries. I was just giving fair notice in case I needed to move forward with something.
